import type { DocumentEventRecord, DocumentEventType, DocumentRevisionRecord, LourexDocument, PaymentRecord, VaultPayload } from '../types.js';
import { duplicateDocument, emptyItem } from './documents.js';
import { makeId } from './id.js';
import { calculateTotals, decimalToScaled } from './money.js';

function centsString(cents:bigint):string{const sign=cents<0n?'-':'';const abs=cents<0n?-cents:cents;return `${sign}${abs/100n}.${(abs%100n).toString().padStart(2,'0')}`; }
export function isCreditNote(doc:LourexDocument):boolean{return doc.role==='credit-note';}
export function isVoided(doc:LourexDocument):boolean{return doc.lifecycleStatus==='voided';}
export function documentRevision(doc:LourexDocument):number{return Math.max(1,Math.trunc(doc.revision||1));}
export function activeFinalCreditNotes(invoiceId:string,documents:LourexDocument[]):LourexDocument[]{return documents.filter(doc=>doc.role==='credit-note'&&doc.creditForId===invoiceId&&doc.status==='final'&&doc.lifecycleStatus!=='voided');}
export function invoiceCreditCapacity(invoice:LourexDocument,documents:LourexDocument[],payments:PaymentRecord[],excludeCreditId=''):{total:string;paid:string;credited:string;available:string}{
  const total=decimalToScaled(calculateTotals(invoice.items,invoice.adjustments).grandTotal,2);
  let paid=0n;for(const payment of payments)if(payment.invoiceId===invoice.id)paid+=decimalToScaled(payment.amount,2);
  let credited=0n;for(const credit of activeFinalCreditNotes(invoice.id,documents))if(credit.id!==excludeCreditId)credited+=decimalToScaled(calculateTotals(credit.items,credit.adjustments).grandTotal,2);
  const available=total-paid-credited;return{total:centsString(total),paid:centsString(paid),credited:centsString(credited),available:centsString(available>0n?available:0n)};
}
export function createDocumentEvent(doc:LourexDocument,type:DocumentEventType,note='',related?:LourexDocument,amount=''):DocumentEventRecord{const now=new Date().toISOString();return{id:makeId('event'),documentId:doc.id,documentNumber:doc.number,type,at:now,note,relatedDocumentId:related?.id||'',relatedDocumentNumber:related?.number||'',amount,currency:doc.currency};}
export function createRevisionRecord(doc:LourexDocument):DocumentRevisionRecord{return{id:makeId('revision'),documentId:doc.id,documentNumber:doc.number,revision:documentRevision(doc),snapshot:structuredClone(doc),createdAt:new Date().toISOString()};}
export function beginRevisionDraft(doc:LourexDocument):LourexDocument{if(doc.status!=='final'||doc.lifecycleStatus==='voided')throw new Error('Only an active final document can start a revision.');if(doc.role==='credit-note')throw new Error('Void a final credit note and create a replacement instead of revising it.');return{...structuredClone(doc),status:'draft',revision:documentRevision(doc)+1,updatedAt:new Date().toISOString()};}
export function restoreRevisionSnapshot(current:LourexDocument,revisions:DocumentRevisionRecord[]):LourexDocument{const targetRevision=documentRevision(current)-1;const record=[...revisions].filter(item=>item.documentId===current.id&&item.revision===targetRevision).sort((a,b)=>b.createdAt.localeCompare(a.createdAt))[0];if(!record)throw new Error('Previous final revision snapshot was not found.');return{...structuredClone(record.snapshot),updatedAt:new Date().toISOString()};}
export function createCreditNoteDraft(source:LourexDocument,number:string,available:string):LourexDocument{if(source.kind!=='invoice'||source.role==='credit-note'||source.status!=='final'||source.lifecycleStatus==='voided')throw new Error('Credit notes can only be created from an active final invoice.');const copy=duplicateDocument(source,number);const sourceTotal=calculateTotals(source.items,source.adjustments).grandTotal;const fullCredit=decimalToScaled(available,2)===decimalToScaled(sourceTotal,2);let items=copy.items;let adjustments=copy.adjustments;if(!fullCredit){const item=emptyItem();item.descriptionEn=`Credit against ${source.number}`;item.descriptionAr=`إشعار دائن مقابل ${source.number}`;item.quantity='1';item.unit='Unit';item.unitPrice=available;items=[item];adjustments={discountEnabled:false,discountMode:'fixed',discountValue:'0.00',shippingEnabled:false,shipping:'0.00',otherChargesEnabled:false,otherCharges:'0.00',taxEnabled:false,taxPercent:'0'};}const reference=source.language==='ar'?`مرجع الفاتورة: ${source.number}`:source.language==='bilingual'?`Credit against ${source.number} / مرجع الفاتورة: ${source.number}`:`Credit against ${source.number}`;const remarks=[reference,copy.terms.remarks.trim()].filter(Boolean).join('\n');return{...copy,kind:'invoice',role:'credit-note',status:'draft',lifecycleStatus:'active',revision:1,creditForId:source.id,creditForNumber:source.number,voidedAt:'',voidReason:'',convertedFromId:'',dueDate:'',items,adjustments,appearance:{...copy.appearance,showBank:false},terms:{...copy.terms,remarks}};}
export function assertDocumentLifecycleInvariant(doc:LourexDocument,documents:LourexDocument[],payments:PaymentRecord[]):void{
  if(doc.lifecycleStatus==='voided'&&doc.status!=='final')throw new Error('A voided document must remain final.');
  if(doc.role==='credit-note'){const source=documents.find(item=>item.id===doc.creditForId);if(!source||source.kind!=='invoice'||source.role==='credit-note')throw new Error('Credit note source invoice was not found.');if(source.lifecycleStatus==='voided')throw new Error('A voided invoice cannot receive a credit note.');if(source.currency!==doc.currency)throw new Error('Credit note currency must match the source invoice.');if((source.customerSnapshot?.sourceCustomerId||'')!==(doc.customerSnapshot?.sourceCustomerId||''))throw new Error('Credit note customer must match the source invoice.');if(doc.status==='final'){const amount=decimalToScaled(calculateTotals(doc.items,doc.adjustments).grandTotal,2);if(amount<=0n)throw new Error('Credit note total must be greater than 0.');const capacity=invoiceCreditCapacity(source,documents,payments,doc.id);if(amount>decimalToScaled(capacity.available,2))throw new Error('Credit note cannot exceed the remaining invoice balance after payments and prior credits.');}return;}
  if(doc.kind==='invoice'){const credits=activeFinalCreditNotes(doc.id,documents);let creditCents=0n;for(const credit of credits){if(credit.currency!==doc.currency)throw new Error('Invoice currency cannot change after a credit note is issued.');if((credit.customerSnapshot?.sourceCustomerId||'')!==(doc.customerSnapshot?.sourceCustomerId||''))throw new Error('Invoice customer cannot change after a credit note is issued.');creditCents+=decimalToScaled(calculateTotals(credit.items,credit.adjustments).grandTotal,2);}let paid=0n;for(const payment of payments)if(payment.invoiceId===doc.id)paid+=decimalToScaled(payment.amount,2);const total=decimalToScaled(calculateTotals(doc.items,doc.adjustments).grandTotal,2);if(paid+creditCents>total)throw new Error('Invoice total cannot be reduced below payments plus issued credit notes.');}
}
export function voidFinalDocument(doc:LourexDocument,reason:string,documents:LourexDocument[],payments:PaymentRecord[]):LourexDocument{const clean=reason.trim();if(!clean)throw new Error('A reason is required to void or cancel a document.');if(doc.status!=='final'||doc.lifecycleStatus==='voided')throw new Error('Only an active final document can be voided.');if(doc.kind==='invoice'&&doc.role==='standard'){if(payments.some(payment=>payment.invoiceId===doc.id))throw new Error('An invoice with recorded payments cannot be voided. Use a credit note instead.');if(activeFinalCreditNotes(doc.id,documents).length)throw new Error('An invoice with issued credit notes cannot be voided.');}return{...doc,lifecycleStatus:'voided',voidedAt:new Date().toISOString(),voidReason:clean,updatedAt:new Date().toISOString()};}
export function lifecycleEventLabel(type:DocumentEventType,arabic=false):string{const en:Record<DocumentEventType,string>={created:'Created',issued:'Issued',reissued:'Reissued','revision-started':'Revision started','revision-discarded':'Revision discarded',voided:'Voided / Cancelled','credit-note-created':'Credit note created','payment-recorded':'Payment recorded','payment-deleted':'Payment deleted',converted:'Converted to invoice'};const ar:Record<DocumentEventType,string>={created:'تم الإنشاء',issued:'تم الإصدار',reissued:'إعادة إصدار','revision-started':'بدء مراجعة','revision-discarded':'إلغاء المراجعة',voided:'إلغاء / Void','credit-note-created':'إنشاء إشعار دائن','payment-recorded':'تسجيل دفعة','payment-deleted':'حذف دفعة',converted:'تحويل إلى فاتورة'};return (arabic?ar:en)[type];}
export function auditedDocument(vault:Pick<VaultPayload,'documentEvents'|'documentRevisions'>,doc:LourexDocument):boolean{return doc.status==='final'||doc.lifecycleStatus==='voided'||documentRevision(doc)>1||vault.documentEvents.some(event=>event.documentId===doc.id&&event.type!=='created')||vault.documentRevisions.some(revision=>revision.documentId===doc.id);}
