export type CompanyAssetKind='generic'|'logo'|'signature'|'stamp';

function readFileAsDataUrl(file:File):Promise<string>{return new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result));reader.onerror=()=>reject(new Error('Unable to read image file.'));reader.readAsDataURL(file);});}
function loadImage(src:string):Promise<HTMLImageElement>{return new Promise((resolve,reject)=>{const image=new Image();image.onload=()=>resolve(image);image.onerror=()=>reject(new Error('Unable to process image file.'));image.src=src;});}

interface BackgroundModel{red:number;green:number;blue:number;luma:number;saturation:number;spread:number;dominance:number;}
interface LogoBackgroundProfile{red:number;green:number;blue:number;lumaLow:number;lumaHigh:number;saturationHigh:number;distanceHigh:number;neutral:boolean;}
interface Bounds{left:number;top:number;right:number;bottom:number;}

function clamp(value:number,minimum:number,maximum:number):number{return Math.max(minimum,Math.min(maximum,value));}
function percentile(values:number[],ratio:number):number{if(!values.length)return 0;const sorted=[...values].sort((a,b)=>a-b);const index=Math.min(sorted.length-1,Math.max(0,Math.round((sorted.length-1)*ratio)));return sorted[index]??0;}
function median(values:number[]):number{return percentile(values,.5);}
function pixelLuma(red:number,green:number,blue:number):number{return red*.2126+green*.7152+blue*.0722;}
function pixelSaturation(red:number,green:number,blue:number):number{const maximum=Math.max(red,green,blue),minimum=Math.min(red,green,blue);return maximum<=0?0:(maximum-minimum)/maximum;}
function colorDistance(data:Uint8ClampedArray,index:number,model:{red:number;green:number;blue:number}):number{const red=(data[index]??0)-model.red,green=(data[index+1]??0)-model.green,blue=(data[index+2]??0)-model.blue;return Math.sqrt((red*red+green*green+blue*blue)/3);}

function borderPixelIndexes(width:number,height:number):number[]{const indexes:number[]=[];const perimeter=Math.max(1,2*(width+height)),step=Math.max(1,Math.floor(perimeter/2400));const depths=[0,Math.min(2,Math.floor(Math.min(width,height)/40))].filter((value,index,array)=>array.indexOf(value)===index);for(const depth of depths){const left=depth,right=Math.max(left,width-1-depth),top=depth,bottom=Math.max(top,height-1-depth);for(let x=left;x<=right;x+=step){indexes.push((top*width+x)*4);if(bottom!==top)indexes.push((bottom*width+x)*4);}for(let y=top+step;y<bottom;y+=step){indexes.push((y*width+left)*4);if(right!==left)indexes.push((y*width+right)*4);}}return indexes;}
function backgroundModel(data:Uint8ClampedArray,width:number,height:number):BackgroundModel|null{const indexes=borderPixelIndexes(width,height).filter(index=>(data[index+3]??0)>24);if(indexes.length<8)return null;const reds=indexes.map(index=>data[index]??0),greens=indexes.map(index=>data[index+1]??0),blues=indexes.map(index=>data[index+2]??0);const red=median(reds),green=median(greens),blue=median(blues);const provisional:BackgroundModel={red,green,blue,luma:pixelLuma(red,green,blue),saturation:pixelSaturation(red,green,blue),spread:0,dominance:0};const distances=indexes.map(index=>colorDistance(data,index,provisional)),spread=percentile(distances,.9),dominanceRadius=clamp(spread+18,24,86),dominance=distances.filter(distance=>distance<=dominanceRadius).length/distances.length;return{...provisional,spread,dominance};}

function logoCornerIndexes(width:number,height:number):number[]{const indexes:number[]=[];const patchWidth=Math.max(4,Math.round(width*.14)),patchHeight=Math.max(4,Math.round(height*.14)),estimated=Math.max(1,patchWidth*patchHeight*4),step=Math.max(1,Math.floor(Math.sqrt(estimated/7000)));const regions:[number,number,number,number][]=[[0,0,patchWidth,patchHeight],[Math.max(0,width-patchWidth),0,width,patchHeight],[0,Math.max(0,height-patchHeight),patchWidth,height],[Math.max(0,width-patchWidth),Math.max(0,height-patchHeight),width,height]];for(const [left,top,right,bottom] of regions){for(let y=top;y<bottom;y+=step){for(let x=left;x<right;x+=step)indexes.push((y*width+x)*4);}}return indexes;}
function logoBackgroundProfile(data:Uint8ClampedArray,width:number,height:number):LogoBackgroundProfile|null{const indexes=logoCornerIndexes(width,height).filter(index=>(data[index+3]??0)>24);if(indexes.length<16)return null;const reds=indexes.map(index=>data[index]??0),greens=indexes.map(index=>data[index+1]??0),blues=indexes.map(index=>data[index+2]??0),red=median(reds),green=median(greens),blue=median(blues),provisional={red,green,blue};const lumas=indexes.map(index=>pixelLuma(data[index]??0,data[index+1]??0,data[index+2]??0)),saturations=indexes.map(index=>pixelSaturation(data[index]??0,data[index+1]??0,data[index+2]??0)),distances=indexes.map(index=>colorDistance(data,index,provisional));return{red,green,blue,lumaLow:percentile(lumas,.02),lumaHigh:percentile(lumas,.98),saturationHigh:percentile(saturations,.97),distanceHigh:percentile(distances,.98),neutral:percentile(saturations,.9)<.22};}

function transparencyRatio(data:Uint8ClampedArray):number{let transparent=0,sampled=0;const pixels=data.length/4,step=Math.max(1,Math.floor(pixels/12000));for(let pixel=0;pixel<pixels;pixel+=step){sampled+=1;if((data[pixel*4+3]??0)<235)transparent+=1;}return sampled?transparent/sampled:0;}
function smoothstep(edge0:number,edge1:number,value:number):number{if(edge1<=edge0)return value>=edge1?1:0;const x=clamp((value-edge0)/(edge1-edge0),0,1);return x*x*(3-2*x);}

function applySignatureMatte(data:Uint8ClampedArray,width:number,height:number,model:BackgroundModel):boolean{if(model.dominance<.42)return false;const softStart=clamp(model.spread*1.65+10,18,72),softEnd=clamp(softStart+48+model.spread*.35,softStart+38,132);let changed=0,visible=0;for(let index=0;index<data.length;index+=4){const originalAlpha=data[index+3]??0;if(originalAlpha===0)continue;const distance=colorDistance(data,index,model),factor=smoothstep(softStart,softEnd,distance),alpha=Math.round(originalAlpha*factor);if(alpha<originalAlpha-2)changed+=1;data[index+3]=alpha;if(alpha>12)visible+=1;}const total=width*height;if(visible<Math.max(8,total*.00035))return false;return changed>Math.max(12,total*.003);}
function edgeThreshold(model:BackgroundModel,kind:CompanyAssetKind):number{const neutral=model.saturation<.22,light=model.luma>176&&neutral,dark=model.luma<92&&neutral;if(kind==='stamp'&&!light)return 0;if(light)return clamp(model.spread*2.45+24,46,108);if(dark)return clamp(model.spread*2.2+22,42,98);return clamp(model.spread*1.85+18,32,76);}
function applyEdgeBackgroundRemoval(data:Uint8ClampedArray,width:number,height:number,model:BackgroundModel,kind:CompanyAssetKind):boolean{if(model.dominance<.43)return false;const threshold=edgeThreshold(model,kind);if(threshold<=0)return false;const total=width*height,visited=new Uint8Array(total),queue=new Int32Array(total);let start=0,end=0;const enqueue=(pixel:number):void=>{if(pixel<0||pixel>=total||visited[pixel])return;const index=pixel*4;if((data[index+3]??0)<=8||colorDistance(data,index,model)>threshold)return;visited[pixel]=1;queue[end++]=pixel;};for(let x=0;x<width;x+=1){enqueue(x);if(height>1)enqueue((height-1)*width+x);}for(let y=1;y<height-1;y+=1){enqueue(y*width);if(width>1)enqueue(y*width+width-1);}const clearUntil=threshold*.5;let changed=0;while(start<end){const pixel=queue[start++]!,x=pixel%width,y=Math.floor(pixel/width),index=pixel*4,originalAlpha=data[index+3]??0,distance=colorDistance(data,index,model),alpha=Math.round(originalAlpha*smoothstep(clearUntil,threshold,distance));if(alpha<originalAlpha-2)changed+=1;data[index+3]=alpha;if(x>0)enqueue(pixel-1);if(x+1<width)enqueue(pixel+1);if(y>0)enqueue(pixel-width);if(y+1<height)enqueue(pixel+width);}return changed>Math.max(12,total*.004);}

function logoPixelMetrics(data:Uint8ClampedArray,index:number,profile:LogoBackgroundProfile):{distance:number;luma:number;saturation:number}{const red=data[index]??0,green=data[index+1]??0,blue=data[index+2]??0;return{distance:colorDistance(data,index,profile),luma:pixelLuma(red,green,blue),saturation:pixelSaturation(red,green,blue)};}
function isDarkNeutralLogoBackground(profile:LogoBackgroundProfile):boolean{return profile.neutral&&profile.lumaHigh<145;}
function isLightNeutralLogoBackground(profile:LogoBackgroundProfile):boolean{return profile.neutral&&profile.lumaLow>145;}
function logoCoreEvidence(data:Uint8ClampedArray,index:number,profile:LogoBackgroundProfile):boolean{if((data[index+3]??0)<=12)return false;const{distance,luma,saturation}=logoPixelMetrics(data,index,profile),saturationGate=Math.max(.26,profile.saturationHigh+.08),distanceGate=Math.max(24,profile.distanceHigh+10);if(saturation>=saturationGate&&distance>=distanceGate)return true;if(isDarkNeutralLogoBackground(profile))return saturation>=Math.max(.13,profile.saturationHigh+.025)&&luma>=profile.lumaHigh+38&&distance>=profile.distanceHigh+20;if(isLightNeutralLogoBackground(profile))return saturation>=Math.max(.12,profile.saturationHigh+.02)&&luma<=profile.lumaLow-38&&distance>=profile.distanceHigh+20;return false;}
function logoBackgroundLike(data:Uint8ClampedArray,index:number,profile:LogoBackgroundProfile):boolean{if((data[index+3]??0)<=8)return true;const{distance,luma,saturation}=logoPixelMetrics(data,index,profile),saturationLimit=Math.max(.34,profile.saturationHigh+.16);if(saturation>saturationLimit)return false;if(isDarkNeutralLogoBackground(profile)){const lumaLimit=clamp(profile.lumaHigh+68,82,196);return luma<=lumaLimit||distance<=profile.distanceHigh+96;}if(isLightNeutralLogoBackground(profile)){const lumaLimit=clamp(profile.lumaLow-68,58,178);return luma>=lumaLimit||distance<=profile.distanceHigh+96;}return distance<=profile.distanceHigh+72;}
function histogramPercentile(counts:Uint32Array,total:number,ratio:number):number{if(!total)return 0;const target=Math.max(1,Math.ceil(total*ratio));let cumulative=0;for(let index=0;index<counts.length;index+=1){cumulative+=counts[index]??0;if(cumulative>=target)return index;}return Math.max(0,counts.length-1);}
function dilateMask(mask:Uint8Array,width:number,height:number,iterations:number):Uint8Array{let current=mask;const total=width*height;for(let iteration=0;iteration<iterations;iteration+=1){const next=new Uint8Array(current);for(let pixel=0;pixel<total;pixel+=1){if(!current[pixel])continue;const x=pixel%width,y=Math.floor(pixel/width);if(x>0)next[pixel-1]=1;if(x+1<width)next[pixel+1]=1;if(y>0)next[pixel-width]=1;if(y+1<height)next[pixel+width]=1;}current=next;}return current;}
function expandedBounds(bounds:Bounds,width:number,height:number,margin:number):Bounds{return{left:Math.max(0,bounds.left-margin),top:Math.max(0,bounds.top-margin),right:Math.min(width-1,bounds.right+margin),bottom:Math.min(height-1,bounds.bottom+margin)};}
function pointInBounds(x:number,y:number,bounds:Bounds):boolean{return x>=bounds.left&&x<=bounds.right&&y>=bounds.top&&y<=bounds.bottom;}

function removeDetachedLogoNoise(data:Uint8ClampedArray,width:number,height:number,core:Uint8Array,roi:Bounds,coreCount:number):number{const total=width*height,visited=new Uint8Array(total),queue=new Int32Array(total),component=new Int32Array(total),smallLimit=Math.max(28,Math.round(coreCount*.018));let cleared=0;for(let seed=0;seed<total;seed+=1){if(visited[seed]||(data[seed*4+3]??0)<=12)continue;let start=0,end=0,count=0,coreHits=0,left=width,top=height,right=-1,bottom=-1;visited[seed]=1;queue[end++]=seed;while(start<end){const pixel=queue[start++]!;component[count++]=pixel;if(core[pixel])coreHits+=1;const x=pixel%width,y=Math.floor(pixel/width);if(x<left)left=x;if(x>right)right=x;if(y<top)top=y;if(y>bottom)bottom=y;const visit=(neighbor:number):void=>{if(neighbor<0||neighbor>=total||visited[neighbor]||(data[neighbor*4+3]??0)<=12)return;visited[neighbor]=1;queue[end++]=neighbor;};if(x>0)visit(pixel-1);if(x+1<width)visit(pixel+1);if(y>0)visit(pixel-width);if(y+1<height)visit(pixel+width);}if(coreHits>0)continue;const centerX=(left+right)/2,centerY=(top+bottom)/2,outside=!pointInBounds(centerX,centerY,roi);if(!outside&&count>smallLimit)continue;for(let index=0;index<count;index+=1){data[component[index]!*4+3]=0;cleared+=1;}}return cleared;}

function applyColorCoreLogoRemoval(data:Uint8ClampedArray,width:number,height:number,profile:LogoBackgroundProfile):boolean{if(!profile.neutral)return false;const total=width*height,original=new Uint8ClampedArray(data),core=new Uint8Array(total),xCounts=new Uint32Array(width),yCounts=new Uint32Array(height);let coreCount=0,originalVisible=0;for(let pixel=0;pixel<total;pixel+=1){const index=pixel*4;if((original[index+3]??0)>12)originalVisible+=1;if(!logoCoreEvidence(original,index,profile))continue;core[pixel]=1;coreCount+=1;const x=pixel%width,y=Math.floor(pixel/width);xCounts[x]=(xCounts[x]??0)+1;yCounts[y]=(yCounts[y]??0)+1;}if(coreCount<Math.max(60,Math.round(total*.00035)))return false;const tight:Bounds={left:histogramPercentile(xCounts,coreCount,.01),top:histogramPercentile(yCounts,coreCount,.01),right:histogramPercentile(xCounts,coreCount,.99),bottom:histogramPercentile(yCounts,coreCount,.99)},coreWidth=tight.right-tight.left+1,coreHeight=tight.bottom-tight.top+1;if(coreWidth<Math.max(10,width*.025)||coreHeight<Math.max(10,height*.025)||coreWidth>width*.84||coreHeight>height*.84)return false;const minimum=Math.min(width,height),margin=Math.max(7,Math.round(Math.max(coreWidth,coreHeight)*.10),Math.round(minimum*.012)),roi=expandedBounds(tight,width,height,margin),selectedCore=new Uint8Array(total),allowance=expandedBounds(tight,width,height,Math.max(2,Math.round(minimum*.006)));let selectedCoreCount=0;for(let pixel=0;pixel<total;pixel+=1){if(!core[pixel])continue;const x=pixel%width,y=Math.floor(pixel/width);if(!pointInBounds(x,y,allowance))continue;selectedCore[pixel]=1;selectedCoreCount+=1;}if(selectedCoreCount<coreCount*.80)return false;const protect=dilateMask(selectedCore,width,height,clamp(Math.round(minimum*.018),5,24));let changed=0;for(let pixel=0;pixel<total;pixel+=1){const index=pixel*4;if((data[index+3]??0)<=12)continue;const x=pixel%width,y=Math.floor(pixel/width);if(!pointInBounds(x,y,roi)){data[index+3]=0;changed+=1;continue;}if(protect[pixel])continue;if(logoBackgroundLike(original,index,profile)){data[index+3]=0;changed+=1;}}removeDetachedLogoNoise(data,width,height,selectedCore,roi,selectedCoreCount);let remaining=0,coreRemaining=0;for(let pixel=0;pixel<total;pixel+=1){if((data[pixel*4+3]??0)<=12)continue;remaining+=1;if(selectedCore[pixel])coreRemaining+=1;}if(coreRemaining<selectedCoreCount*.995||remaining<selectedCoreCount||changed<Math.max(16,originalVisible*.015)){data.set(original);return false;}return true;}
function applyLogoBackgroundRemoval(data:Uint8ClampedArray,width:number,height:number):boolean{const profile=logoBackgroundProfile(data,width,height);if(profile&&applyColorCoreLogoRemoval(data,width,height,profile))return true;const model=backgroundModel(data,width,height);if(!model)return false;return applyEdgeBackgroundRemoval(data,width,height,model,'logo');}

function cropTransparentCanvas(canvas:HTMLCanvasElement,pixels:ImageData):string{const width=canvas.width,height=canvas.height;let left=width,top=height,right=-1,bottom=-1;for(let index=0;index<pixels.data.length;index+=4){if((pixels.data[index+3]??0)<=12)continue;const pixel=index/4,x=pixel%width,y=Math.floor(pixel/width);if(x<left)left=x;if(x>right)right=x;if(y<top)top=y;if(y>bottom)bottom=y;}if(right<left||bottom<top)return canvas.toDataURL('image/png');const padding=Math.max(4,Math.round(Math.min(width,height)*.025)),cropLeft=Math.max(0,left-padding),cropTop=Math.max(0,top-padding),cropRight=Math.min(width-1,right+padding),cropBottom=Math.min(height-1,bottom+padding),cropWidth=Math.max(1,cropRight-cropLeft+1),cropHeight=Math.max(1,cropBottom-cropTop+1);if(cropWidth===width&&cropHeight===height)return canvas.toDataURL('image/png');const output=document.createElement('canvas');output.width=cropWidth;output.height=cropHeight;const outputContext=output.getContext('2d');if(!outputContext)return canvas.toDataURL('image/png');outputContext.clearRect(0,0,cropWidth,cropHeight);outputContext.drawImage(canvas,cropLeft,cropTop,cropWidth,cropHeight,0,0,cropWidth,cropHeight);return output.toDataURL('image/png');}
async function normalizeImage(src:string,kind:CompanyAssetKind):Promise<string>{const image=await loadImage(src),naturalWidth=image.naturalWidth||image.width,naturalHeight=image.naturalHeight||image.height;if(!naturalWidth||!naturalHeight)return src;const maxDimension=1400,scale=Math.min(1,maxDimension/Math.max(naturalWidth,naturalHeight)),width=Math.max(1,Math.round(naturalWidth*scale)),height=Math.max(1,Math.round(naturalHeight*scale)),canvas=document.createElement('canvas');canvas.width=width;canvas.height=height;const context=canvas.getContext('2d',{willReadFrequently:true});if(!context)return src;context.clearRect(0,0,width,height);context.drawImage(image,0,0,width,height);const pixels=context.getImageData(0,0,width,height),alreadyTransparent=transparencyRatio(pixels.data)>.06;let changed=false;if(!alreadyTransparent){if(kind==='logo')changed=applyLogoBackgroundRemoval(pixels.data,width,height);else{const model=backgroundModel(pixels.data,width,height);if(model){if(kind==='signature')changed=applySignatureMatte(pixels.data,width,height,model);if(!changed)changed=applyEdgeBackgroundRemoval(pixels.data,width,height,model,kind);}}}if(changed)context.putImageData(pixels,0,0);return cropTransparentCanvas(canvas,pixels);}

export async function cleanImageDataUrl(src:string,kind:CompanyAssetKind='generic'):Promise<string>{if(!src||!src.startsWith('data:image/'))return src;try{return await normalizeImage(src,kind);}catch{return src;}}
export async function fileToRawDataUrl(file:File,maxBytes=4*1024*1024):Promise<string>{if(file.size>maxBytes)throw new Error('Image is too large. Please use a file smaller than 4 MB.');if(!/^image\/(png|webp|jpeg|svg\+xml)$/i.test(file.type))throw new Error('Use PNG, WebP, JPEG, or SVG image files.');return readFileAsDataUrl(file);}
export async function fileToDataUrl(file:File,maxBytes=4*1024*1024,kind:CompanyAssetKind='generic'):Promise<string>{const src=await fileToRawDataUrl(file,maxBytes);return cleanImageDataUrl(src,kind);}
