import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {emptyVault} from '../dist/src/lib/defaults.js';
import {parseAiPartyMasterIntent,prepareAiPartyMaster,applyAiPartyMaster} from '../dist/src/lib/ai-party-master.js';
import {createAiToolRuntime,deterministicAiToolPlan,executeAiToolPlan} from '../dist/src/lib/ai-tool-orchestrator.js';
import {applyApprovedToolExecution} from '../dist/src/lib/ai-tool-actions.js';
import {registerVaultMutationBridge} from '../dist/src/storage/vault-mutation-bridge.js';

const vault=()=>emptyVault();
const runtime=v=>createAiToolRuntime(v,{assistantRuntime:{scope:'business',workspaceId:v.appSettings.activeWorkspaceId||'default',branchId:'main',entity:null}});
const input='Create customer: Coastal Trade LLC; phone: +905392411642; email: sales@coastal.example; city: Istanbul; country: Turkey';
test('B06: explicit English and Arabic party commands parse into exact locally sourced values',()=>{
  assert.deepEqual(parseAiPartyMasterIntent(input),{party:'customer',mode:'create',name:'Coastal Trade LLC',fields:{phone:'+905392411642',email:'sales@coastal.example',city:'Istanbul',country:'Turkey'}});
  assert.deepEqual(parseAiPartyMasterIntent('أضف عميل: شركة اليسر؛ الهاتف: +905392411642؛ البريد: sales@example.com'),{party:'customer',mode:'create',name:'شركة اليسر',fields:{phone:'+905392411642',email:'sales@example.com'}});
  assert.deepEqual(parseAiPartyMasterIntent('عدّل مورد: Turkish Foods؛ المدينة: Istanbul'),{party:'supplier',mode:'update',name:'Turkish Foods',fields:{city:'Istanbul'}});
  assert.equal(parseAiPartyMasterIntent('List all customers'),null);
  assert.equal(parseAiPartyMasterIntent('Do not create customer: Coastal Trade LLC; phone: +905392411642'),null);
  assert.equal(parseAiPartyMasterIntent('لا تسجل عميل: شركة اليسر؛ الهاتف: +905392411642'),null);
  assert.equal(parseAiPartyMasterIntent('Create customer: Coastal Trade LLC'),null);
});
test('B06: customer create is one deterministic, reviewable tool approval, never an implicit save',()=>{
  const v=vault(),before=JSON.stringify(v),plan=deterministicAiToolPlan(input,runtime(v));
  assert.equal(plan?.calls[0].tool,'customer.master');
  const output=executeAiToolPlan(runtime(v),plan);
  assert.equal(output.proposal?.tool,'customer.master');
  assert.equal(output.proposal?.args.mode,'create');
  assert.equal(output.proposal.preview.length,1);
  assert.equal(output.proposal.preview[0].after.phone,'+905392411642');
  assert.equal(output.proposal.preview[0].after.email,'sales@coastal.example');
  assert.equal(JSON.stringify(v),before);
  const after=applyAiPartyMaster(v,output.proposal.args);
  assert.equal(after.customers.length,1);
  assert.equal(after.customers[0].companyNameEn,'Coastal Trade LLC');
  assert.equal(after.customers[0].phone,'+905392411642');
  assert.equal(after.customers[0].email,'sales@coastal.example');
  assert.equal(after.customers[0].paymentDueDays,'');
  assert.equal(after.customers[0].paymentTerms,'');
  assert.equal(v.customers.length,0);
});
test('B06: Arabic customer name is stored in Arabic field without invented English translation',()=>{
  const v=vault(),intent=parseAiPartyMasterIntent('سجل عميل: مؤسسة النور؛ الجوال: +905392411642');
  const staged=prepareAiPartyMaster(v,intent);
  const saved=applyAiPartyMaster(v,staged);
  assert.equal(saved.customers[0].companyNameAr,'مؤسسة النور');
  assert.equal(saved.customers[0].companyNameEn,'');
  assert.equal(saved.customers[0].email,'');
  assert.equal(saved.customers[0].creditLimit,'');
});
test('B06: supplier create and exact existing-name update preserve unrelated fields and company',()=>{
  const v=vault();
  const create=prepareAiPartyMaster(v,parseAiPartyMasterIntent('Create supplier: Turkish Foods; email: office@turkish.example; phone: +905390001122'));
  const created=applyAiPartyMaster(v,create);
  assert.equal(created.suppliers.length,1);
  assert.equal(created.suppliers[0].nameEn,'Turkish Foods');
  assert.equal(created.suppliers[0].address,'');
  const update=prepareAiPartyMaster(created,parseAiPartyMasterIntent('Update supplier: Turkish Foods; city: Istanbul; payment terms: Net 30'));
  assert.equal(update.mode,'update');
  assert.equal(update.preview.before.city,'');
  assert.equal(update.preview.after.city,'Istanbul');
  const next=applyAiPartyMaster(created,update);
  assert.equal(next.suppliers[0].city,'Istanbul');
  assert.equal(next.suppliers[0].paymentTerms,'Net 30');
  assert.equal(next.suppliers[0].email,'office@turkish.example');
  assert.equal(created.suppliers[0].city,'');
});
test('B06: save is atomic and checked after one explicit click',async()=>{
  let current=vault(),calls=0;
  registerVaultMutationBridge(async mutation=>{calls++;current=mutation(current);return current;});
  const staged=prepareAiPartyMaster(current,parseAiPartyMasterIntent('Add supplier: Oasis FMCG; email: partner@oasis.example'));
  const applied=await applyApprovedToolExecution({capability:'tool.execute',tool:'supplier.master',args:staged,label:'Review supplier',rationale:'User approved'});
  assert.equal(calls,1);
  assert.equal(current.suppliers.length,1);
  assert.equal(current.suppliers[0].id,applied.id);
  assert.match(applied.summary,/created after explicit approval/);
});
test('B06: duplicate email or name, unsupported fields, invalid email and forged fields fail closed',()=>{
  let v=vault();
  const first=prepareAiPartyMaster(v,parseAiPartyMasterIntent(input));
  v=applyAiPartyMaster(v,first);
  assert.throws(()=>prepareAiPartyMaster(v,parseAiPartyMasterIntent('Add customer: Coastal Trade LLC; phone: +905000000111')),/already exists/);
  assert.throws(()=>prepareAiPartyMaster(v,parseAiPartyMasterIntent('Add customer: Rival LLC; email: sales@coastal.example')),/Duplicate/);
  assert.throws(()=>parseAiPartyMasterIntent('Add customer: Rival LLC; bank account: IBAN123'),/Unsupported contact field/);
  assert.throws(()=>parseAiPartyMasterIntent('Add customer: Rival LLC; email: wrong-email'),/Invalid contact email/);
  assert.throws(()=>parseAiPartyMasterIntent('Add customer: Rival LLC; phone: 12'),/Invalid contact phone/);
  assert.throws(()=>parseAiPartyMasterIntent('Add customer: Rival LLC; city: Paris; city: London'),/Repeated contact field/);
  const staged=prepareAiPartyMaster(v,parseAiPartyMasterIntent('Add customer: Rival LLC; city: Paris'));
  staged.after.creditLimit='99999';
  assert.throws(()=>applyAiPartyMaster(v,staged),/Unapproved party field/);
  assert.equal(v.customers.length,1);
});
test('B06: stale, ambiguous, company changes and multi-action plans cannot accidentally save',()=>{
  const v=vault(),created=applyAiPartyMaster(v,prepareAiPartyMaster(v,parseAiPartyMasterIntent(input)));
  const intent=parseAiPartyMasterIntent('Update customer: Coastal Trade LLC; city: Ankara');
  const update=prepareAiPartyMaster(created,intent);
  const changed=structuredClone(created);
  changed.customers[0].updatedAt='2026-10-09T00:00:00Z';
  assert.throws(()=>applyAiPartyMaster(changed,update),/changed since preview/);
  const other=structuredClone(created);other.appSettings.activeWorkspaceId='other';
  assert.throws(()=>applyAiPartyMaster(other,update),/Active company changed/);
  assert.throws(()=>prepareAiPartyMaster(other,intent),/No exact customer/);
  const plan=deterministicAiToolPlan(input,runtime(v));
  const mixed=executeAiToolPlan(runtime(v),{...plan,calls:[...plan.calls,{id:'extra',tool:'task.create',args:{title:'second write'},reason:'second write'}]});
  assert.equal(mixed.proposal,null);
  assert.equal(v.customers.length,0);
});
test('B06: planner cannot invent customer/supplier master changes; UI previews all fields',async()=>{
 const client=await readFile('src/lib/ai-tool-client.ts','utf8');
 const ui=await readFile('scripts/ai-conversation-owner-stage4-tools.mjs','utf8');
 assert.match(client,/call\.tool==='customer\.master'\|\|call\.tool==='supplier\.master'/);
 assert.match(ui,/customer\.master/);
 assert.match(ui,/supplier\.master/);
 assert.match(ui,/contactPerson/);
 assert.match(ui,/paymentTerms/);
});
