import test from 'node:test';
import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
const read=path=>readFile(path,'utf8');

test('v132 adds encrypted document events revisions and dedicated credit note numbering',async()=>{const [types,defaults,merge,vault,docs]=await Promise.all([read('src/types.ts'),read('src/lib/defaults.ts'),read('src/storage/vault-merge.ts'),read('src/storage/vault.ts'),read('src/lib/documents.ts')]);assert.match(types,/DocumentEventRecord/);assert.match(types,/DocumentRevisionRecord/);assert.match(types,/creditNotePrefix/);assert.match(defaults,/APP_SCHEMA_VERSION = 8/);assert.match(defaults,/documentEvents: []/);assert.match(defaults,/documentRevisions: []/);assert.match(merge,/documentEvents:mergeRecords/);assert.match(merge,/documentRevisions:mergeRecords/);assert.match(vault,/document event/);assert.match(vault,/document revision/);assert.match(docs,/nextCreditNoteNumber/);});

test('v132 safe revision snapshots final before opening a draft revision',async()=>{const [core,app,lifecycle]=await Promise.all([read('src/components/EditorPageCore.tsx'),read('src/app/App.tsx'),read('src/lib/document-lifecycle.ts')]);assert.match(core,/onBeginRevision/);assert.match(core,/Create a safe revision/);assert.doesNotMatch(core,/const doc={...structuredClone(this.state.doc),status:'draft'/);assert.match(app,/createRevisionRecord(current)/);assert.match(app,/beginRevisionDraft(current)/);assert.match(lifecycle,/snapshot:structuredClone(doc)/);assert.match(app,/restoreRevisionSnapshot/);});

test('v132 final documents preserve audit history through void and block destructive delete',async()=>{const [app,lifecycle,panel]=await Promise.all([read('src/app/App.tsx'),read('src/lib/document-lifecycle.ts'),read('src/components/DocumentLifecyclePanel.tsx')]);assert.match(lifecycle,/An invoice with recorded payments cannot be voided/);assert.match(lifecycle,/An invoice with issued credit notes cannot be voided/);assert.match(app,/Issued or audited documents cannot be deleted/);assert.match(panel,/Confirm Void/);assert.match(panel,/reason/);assert.match(panel,/Timeline/);});

test('v132 credit notes are linked capped and cannot accept payments',async()=>{const [lifecycle,payments,renderer,docs]=await Promise.all([read('src/lib/document-lifecycle.ts'),read('src/lib/payments.ts'),read('src/templates/TemplateRenderer.tsx'),read('src/components/DocumentsPage.tsx')]);assert.match(lifecycle,/Credit note cannot exceed the remaining invoice balance after payments and prior credits/);assert.match(lifecycle,/creditForId:source.id/);assert.match(payments,/invoice.role==='credit-note'/);assert.match(renderer,/CREDIT NOTE/);assert.match(renderer,/Source Invoice/);assert.match(docs,/Credit Note/);});

test('v132 ships lifecycle UI offline and preserves prior cache compatibility markers',async()=>{const [html,sw]=await Promise.all([read('index.html'),read('public/sw.js')]);assert.ok(html.includes('document-lifecycle-v132.css'));assert.ok(html.indexOf('document-lifecycle-v132.css')<html.indexOf('performance-polish-v100.css'));for(const asset of ['document-lifecycle-v132.css','DocumentLifecyclePanel.js','document-lifecycle.js'])assert.ok(sw.includes(asset),asset);assert.match(sw,/const CACHE = 'lourex-invoice-v132'/);assert.match(sw,/const CACHE = 'lourex-invoice-v131'/);assert.match(sw,/const CACHE = 'lourex-invoice-v120'/);});


test('v132 blocks revision after financial activity and keeps ordinary drafts deletable',async()=>{const [app,lifecycle,editor]=await Promise.all([read('src/app/App.tsx'),read('src/lib/document-lifecycle.ts'),read('src/components/EditorPage.tsx')]);assert.match(app,/payments or issued credit notes cannot be revised/);assert.doesNotMatch(app,/Number\(capacity\.available\)/);assert.match(lifecycle,/event.type!==['"]created['"]/);assert.match(editor,/lifecycleStatus!==['"]voided['"]/);assert.match(app,/cancelled quote cannot be converted/);});
