import test from 'node:test';
import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import { defaultCompany, emptyVault } from '../dist/src/lib/defaults.js';
import { createBlankDocument } from '../dist/src/lib/documents.js';
import { calculateProfitability } from '../dist/src/lib/profitability.js';
import { invoicePaymentSummary } from '../dist/src/lib/payments.js';
import { customerStatement, receivablesByCurrency } from '../dist/src/lib/receivables.js';
import { createCreditNoteDraft } from '../dist/src/lib/document-lifecycle.js';
import { createManualInventoryMovement, createPurchase, createPurchaseItem, postPurchase, reverseManualInventoryMovement, reversePurchase } from '../dist/src/lib/operations.js';

function finalInvoice(){const doc=createBlankDocument('invoice','INV-2026-9001',defaultCompany());doc.status='final';doc.issueDate='2026-01-01';doc.dueDate='2026-01-31';doc.customerSnapshot={sourceCustomerId:'cust',companyNameEn:'Customer',companyNameAr:'',contactPerson:'',addressEn:'',addressAr:'',city:'',country:'',phone:'',email:'',vatTaxNumber:'',commercialRegistration:''};doc.items[0].descriptionEn='Bulk';doc.items[0].quantity='10000';doc.items[0].unitPrice='1.00';doc.items[0].unitCost='0.1234';return doc;}

test('v138 keeps 4-decimal unit cost precision until line-total rounding',()=>{const doc=finalInvoice();const p=calculateProfitability(doc);assert.equal(p.itemCost,'1234.00');assert.equal(p.netRevenue,'10000.00');assert.equal(p.grossProfit,'8766.00');});

test('v138 excludes future payments and future credit notes from as-of receivables and statements',()=>{const invoice=finalInvoice();invoice.items[0].quantity='1';invoice.items[0].unitPrice='1000.00';invoice.items[0].unitCost='500.00';const futureCredit=createCreditNoteDraft(invoice,'CN-2026-9001','200.00');futureCredit.status='final';futureCredit.issueDate='2026-03-01';const payments=[{id:'p1',invoiceId:invoice.id,invoiceNumber:invoice.number,customerId:'cust',customerNameEn:'Customer',customerNameAr:'',currency:'USD',amount:'300.00',date:'2026-03-10',method:'cash',reference:'',notes:'',createdAt:'2026-03-10T00:00:00.000Z',updatedAt:'2026-03-10T00:00:00.000Z'}];const docs=[invoice,futureCredit];const jan=invoicePaymentSummary(invoice,payments,'2026-01-31',docs);assert.equal(jan.credits,'0.00');assert.equal(jan.paid,'0.00');assert.equal(jan.remaining,'1000.00');const march=invoicePaymentSummary(invoice,payments,'2026-03-31',docs);assert.equal(march.credits,'200.00');assert.equal(march.paid,'300.00');assert.equal(march.remaining,'500.00');assert.equal(receivablesByCurrency(docs,payments,'2026-01-31')[0].outstanding,'1000.00');const statement=customerStatement('cust',docs,payments,'2026-01-31')[0];assert.equal(statement.entries.length,1);assert.equal(statement.outstanding,'1000.00');});

test('v138 excludes invoices issued after the as-of date',()=>{const invoice=finalInvoice();invoice.issueDate='2026-04-01';assert.equal(receivablesByCurrency([invoice],[],'2026-03-31').length,0);});

test('v138 partial credit note resets inherited internal overhead and remains cost-incomplete',()=>{const invoice=finalInvoice();invoice.internalCosts={shippingCost:'100.00',otherCost:'50.00'};const credit=createCreditNoteDraft(invoice,'CN-2026-9002','100.00');assert.deepEqual(credit.internalCosts,{shippingCost:'0.00',otherCost:'0.00'});assert.equal(credit.items[0].unitCost,'');assert.equal(calculateProfitability(credit).complete,false);});

test('v138 purchase reversal uses reversal-day stock date and manual movement reverses instead of deleting history',()=>{const item={id:'item-1',createdAt:'x',updatedAt:'x',descriptionEn:'Item',descriptionAr:'',hsCode:'',origin:'',packing:'',unit:'PCS',lastUnitPrice:'',lastCurrency:'USD',lastUnitCost:'1.00',lastCostCurrency:'USD',usageCount:0,lastUsedAt:''};const supplier={id:'s1',createdAt:'x',updatedAt:'x',nameEn:'S',nameAr:'',contactPerson:'',address:'',city:'',country:'',phone:'',email:'',vatTaxNumber:'',commercialRegistration:'',defaultCurrency:'USD',paymentTerms:'',notes:''};let purchase=createPurchase([], [supplier], 'USD');purchase.date='2026-01-01';purchase.items=[createPurchaseItem(item)];purchase.items[0].descriptionEn='Item';purchase.items[0].quantity='2';purchase.items[0].unitCost='1.00';const posted=postPurchase(purchase,[item],[]);const reversed=reversePurchase(posted.purchase,'cancel',posted.movements,posted.savedItems);assert.notEqual(reversed.movements[0].date,'2026-01-01');const manual=createManualInventoryMovement(item,'opening','5','2026-01-01');const undo=reverseManualInventoryMovement(manual,'2026-02-01');assert.equal(undo.quantity,'-5');assert.equal(undo.date,'2026-02-01');assert.equal(undo.sourceId,manual.id);});

test('v138 source contains referential guards and print uses canonical saveDocument issue path',async()=>{const app=await readFile('src/app/App.tsx','utf8');const build=await readFile('scripts/build.mjs','utf8');const sw=await readFile('public/sw.js','utf8');assert.match(app,/purchase or inventory history and cannot be deleted/);assert.match(app,/historical expenses and cannot be deleted/);assert.match(app,/reverseManualInventoryMovement/);assert.ok(app.includes('await this.saveDocument(target,false)'));assert.doesNotMatch(app,/await this.persist({...vault,documents});}const customer=target/);assert.match(build,/without Vercel Git source metadata/);assert.match(sw,/const CACHE = 'lourex-invoice-v138'/);});
