import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
const read=p=>readFile(p,'utf8');
test('Batch 8 stays inside Products & Inventory',async()=>{const w=await read('src/components/ProductsInventoryWorkspace.tsx');assert.match(w,/type Tab='products'\|'prices'\|'inventory'\|'planning'\|'movements'/);assert.match(w,/id:'prices'/);assert.match(w,/<ProductPriceLists/);assert.doesNotMatch(w,/window\.location/);});
test('price policies preserve legacy product model and issued documents',async()=>{const [engine,types]=await Promise.all([read('src/lib/price-lists.ts'),read('src/types.ts')]);assert.match(engine,/@lourex:pricing:v1:/);assert.match(engine,/lastUnitPrice:next\.retail\|\|item\.lastUnitPrice/);assert.match(types,/lastUnitPrice: string/);assert.doesNotMatch(engine,/LourexDocument/);});
test('pricing resolves deterministic quantity tiers and blocks hidden FX',async()=>{const e=await read('src/lib/price-lists.ts');assert.match(e,/q>=distributorMin/);assert.match(e,/q>=wholesaleMin/);assert.match(e,/item\.lastCurrency!==currency/);assert.match(e,/source:'none'/);assert.match(e,/marginWarning/);});
test('pricing validation protects hierarchy and margin floor',async()=>{const e=await read('src/lib/price-lists.ts');assert.match(e,/Wholesale price cannot exceed retail price/);assert.match(e,/Distributor price cannot exceed wholesale price/);assert.match(e,/Minimum margin must be between 0 and 100 percent/);});
test('price lists are bilingual and mobile responsive',async()=>{const [c,s]=await Promise.all([read('src/components/ProductPriceLists.tsx'),read('src/styles/pricing-batch8.css')]);assert.match(c,/قوائم الأسعار/);assert.match(c,/الموزع/);assert.match(c,/المستندات الصادرة سابقًا/);assert.match(s,/@media\(max-width:640px\)/);assert.match(s,/min-height:44px/);assert.match(s,/html\[dir="rtl"\]/);});
