import type { AppSettings, CompanySettings, Customer, DocumentKind, LourexDocument, UiLanguage, VaultPayload } from '../types.js';
import { defaultCompany, emptyVault } from '../lib/defaults.js';
import { createBlankDocument, convertToInvoice, duplicateDocument, nextDocumentNumber, validateDocument } from '../lib/documents.js';
import { exportBackup, readBackup } from '../lib/backup.js';
import { safeFilename } from '../lib/id.js';
import { getPublicPreferences, getSecurity, hasSecurity, putPublicPreferences } from '../storage/db.js';
import { changePin, restoreVaultWithCurrentKey, saveVault, setupVault, unlockVault } from '../storage/vault.js';
import { verifyPin } from '../crypto/crypto.js';
import { setUiLanguage, t } from '../lib/i18n.js';
import { AuthScreenSelector } from './AuthScreenSelector.js';
import { DocumentsPage } from '../components/DocumentsPage.js';
import { CustomersPage } from '../components/CustomersPage.js';
import { EditorPage } from '../components/EditorPage.js';
import { SettingsModal } from '../components/SettingsModal.js';
import { Brand, Button, ConfirmDialog, Icon, IconButton, Toast } from '../components/UI.js';
import { TemplateRenderer } from '../templates/TemplateRenderer.js';

interface State {
  loading:boolean; firstRun:boolean; unlocked:boolean; key:CryptoKey|null; vault:VaultPayload|null;
  screen:'documents'|'customers'|'editor'; editorDoc:LourexDocument|null; settingsOpen:boolean; newMenu:boolean;
  deletingDoc:LourexDocument|null; toast:string; toastTone:'default'|'success'|'error'; printDoc:LourexDocument|null;
  publicLogo:string; uiLanguage:UiLanguage;
}

export class App extends React.Component<{},State> {
  state:State={loading:true,firstRun:false,unlocked:false,key:null,vault:null,screen:'documents',editorDoc:null,settingsOpen:false,newMenu:false,deletingDoc:null,toast:'',toastTone:'default',printDoc:null,publicLogo:'./brand/lourex-logo.svg',uiLanguage:'en'};
  private lockTimer:number|undefined; private toastTimer:number|undefined;
  componentDidMount():void{void this.initialize();['pointerdown','keydown','touchstart'].forEach(ev=>window.addEventListener(ev,this.activity,{passive:true}));window.addEventListener('afterprint',this.afterPrint);}
  componentWillUnmount():void{['pointerdown','keydown','touchstart'].forEach(ev=>window.removeEventListener(ev,this.activity));window.removeEventListener('afterprint',this.afterPrint);if(this.lockTimer)clearTimeout(this.lockTimer);if(this.toastTimer)clearTimeout(this.toastTimer);}
  private initialize=async()=>{try{const [configured,preferences]=await Promise.all([hasSecurity(),getPublicPreferences()]);const uiLanguage=preferences?.uiLanguage??'en';const publicLogo=preferences?.logoDataUrl||'./brand/lourex-logo.svg';setUiLanguage(uiLanguage);this.setState({loading:false,firstRun:!configured,unlocked:false,uiLanguage,publicLogo});}catch(e){this.setState({loading:false});this.showToast(e instanceof Error?e.message:t('Unable to access local storage.','تعذر الوصول إلى التخزين المحلي.'),'error');}};
  private activity=()=>{if(this.state.unlocked)this.resetAutoLock();};
  private resetAutoLock=()=>{if(this.lockTimer)window.clearTimeout(this.lockTimer);const mins=this.state.vault?.appSettings.autoLockMinutes??15;if(mins>0)this.lockTimer=window.setTimeout(()=>this.lock(),mins*60_000);};
  private showToast=(toast:string,tone:'default'|'success'|'error'='default')=>{if(this.toastTimer)clearTimeout(this.toastTimer);this.setState({toast,toastTone:tone});this.toastTimer=window.setTimeout(()=>this.setState({toast:''}),3600);};
  private normalizedVault=(vault:VaultPayload):VaultPayload=>({...vault,appSettings:{...vault.appSettings,uiLanguage:vault.appSettings.uiLanguage??this.state.uiLanguage??'en'}});
  private syncPublicPreferences=async(logoDataUrl:string,uiLanguage:UiLanguage)=>{const publicLogo=logoDataUrl||'./brand/lourex-logo.svg';setUiLanguage(uiLanguage);await putPublicPreferences({logoDataUrl:publicLogo,uiLanguage});this.setState({publicLogo,uiLanguage});};
  private changePublicLanguage=async(uiLanguage:UiLanguage)=>{setUiLanguage(uiLanguage);this.setState({uiLanguage});await putPublicPreferences({logoDataUrl:this.state.publicLogo||'./brand/lourex-logo.svg',uiLanguage});};
  private finishSetup=async(pin:string,company:CompanySettings)=>{const base=emptyVault();const vault={...base,company,appSettings:{...base.appSettings,uiLanguage:this.state.uiLanguage}};const setup=await setupVault(pin,vault);await this.syncPublicPreferences(company.logoDataUrl,this.state.uiLanguage);this.setState({firstRun:false,unlocked:true,key:setup.key,vault:setup.vault,screen:'documents'},this.resetAutoLock);this.showToast(t('LOUREX Invoice is ready.','نظام LOUREX Invoice جاهز.'),'success');};
  private unlock=async(pin:string)=>{const result=await unlockVault(pin);const needsMigration=!result.vault.appSettings.uiLanguage;const vault=this.normalizedVault(result.vault);if(needsMigration)await saveVault(result.key,vault);await this.syncPublicPreferences(vault.company.logoDataUrl,vault.appSettings.uiLanguage);this.setState({unlocked:true,key:result.key,vault,screen:'documents',editorDoc:null},this.resetAutoLock);};
  private lock=()=>{if(this.lockTimer)window.clearTimeout(this.lockTimer);this.setState({unlocked:false,key:null,vault:null,editorDoc:null,screen:'documents',settingsOpen:false,newMenu:false});};
  private persist=async(vault:VaultPayload)=>{if(!this.state.key)throw new Error(t('App is locked.','التطبيق مقفل.'));await saveVault(this.state.key,vault);this.setState({vault});};
  private reserveDocument=async(kind:DocumentKind):Promise<{doc:LourexDocument;vault:VaultPayload}>=>{const vault=this.requireVault();const next=nextDocumentNumber(vault,kind);await this.persist(next.vault);return{doc:createBlankDocument(kind,next.number,next.vault.company),vault:next.vault};};
  private newDocument=async(kind:DocumentKind)=>{try{const {doc}=await this.reserveDocument(kind);this.setState({screen:'editor',editorDoc:doc,newMenu:false});}catch(e){this.showToast(e instanceof Error?e.message:t('Unable to create document.','تعذر إنشاء المستند.'),'error');}};
  private saveDocument=async(doc:LourexDocument,auto=false)=>{const vault=this.requireVault();if(vault.documents.some(d=>d.id!==doc.id&&d.number.trim().toLowerCase()===doc.number.trim().toLowerCase()))throw new Error(t('Document number already exists.','رقم المستند مستخدم بالفعل.'));const index=vault.documents.findIndex(d=>d.id===doc.id);const documents=[...vault.documents];const updated={...doc,updatedAt:new Date().toISOString()};if(index>=0)documents[index]=updated;else documents.push(updated);await this.persist({...vault,documents});this.setState({editorDoc:updated});if(!auto)this.showToast(t('Document saved.','تم حفظ المستند.'),'success');};
  private openDocument=(doc:LourexDocument)=>this.setState({screen:'editor',editorDoc:structuredClone(doc)});
  private duplicate=async(source:LourexDocument)=>{try{const {doc:blank,vault}=await this.reserveDocument(source.kind);const copy=duplicateDocument(source,blank.number);const next={...vault,documents:[...vault.documents,copy]};await this.persist(next);this.setState({screen:'editor',editorDoc:copy});this.showToast(t('Duplicate created.','تم إنشاء نسخة.'),'success');}catch(e){this.showToast(e instanceof Error?e.message:t('Duplicate failed.','تعذر إنشاء نسخة.'),'error');}};
  private convert=async(source:LourexDocument)=>{try{const current=this.requireVault();const errors=validateDocument(source);if(Object.keys(errors).length)throw new Error(t('Save a valid Proforma before converting it.','احفظ فاتورة مبدئية صالحة قبل تحويلها.'));if(current.documents.some(d=>d.id!==source.id&&d.number.trim().toLowerCase()===source.number.trim().toLowerCase()))throw new Error(t('Document number already exists.','رقم المستند مستخدم بالفعل.'));const savedSource={...source,updatedAt:new Date().toISOString()};const sourceIndex=current.documents.findIndex(d=>d.id===source.id);const sourceDocuments=[...current.documents];if(sourceIndex>=0)sourceDocuments[sourceIndex]=savedSource;else sourceDocuments.push(savedSource);const withSource={...current,documents:sourceDocuments};const numbered=nextDocumentNumber(withSource,'invoice');const converted=convertToInvoice(savedSource,numbered.number);const next={...numbered.vault,documents:[...sourceDocuments,converted]};await this.persist(next);this.setState({screen:'editor',editorDoc:converted});this.showToast(t(`Created ${converted.number}.`,`تم إنشاء ${converted.number}.`),'success');}catch(e){this.showToast(e instanceof Error?e.message:t('Conversion failed.','فشل التحويل.'),'error');}};
  private deleteDocument=async()=>{const target=this.state.deletingDoc;if(!target)return;try{const vault=this.requireVault();await this.persist({...vault,documents:vault.documents.filter(d=>d.id!==target.id)});this.setState({deletingDoc:null});this.showToast(t('Document deleted.','تم حذف المستند.'),'success');}catch(e){this.showToast(e instanceof Error?e.message:t('Delete failed.','فشل الحذف.'),'error');}};
  private saveCustomer=async(customer:Customer)=>{const vault=this.requireVault();const index=vault.customers.findIndex(c=>c.id===customer.id);const customers=[...vault.customers];if(index>=0)customers[index]={...customer,updatedAt:new Date().toISOString()};else customers.push(customer);await this.persist({...vault,customers});};
  private deleteCustomer=async(customer:Customer)=>{const vault=this.requireVault();await this.persist({...vault,customers:vault.customers.filter(c=>c.id!==customer.id)});this.showToast(t('Customer deleted.','تم حذف العميل.'),'success');};
  private saveCompany=async(company:CompanySettings)=>{const vault=this.requireVault();await this.persist({...vault,company});await this.syncPublicPreferences(company.logoDataUrl,vault.appSettings.uiLanguage);};
  private saveAppSettings=async(appSettings:AppSettings)=>{const vault=this.requireVault();const next={...appSettings,uiLanguage:appSettings.uiLanguage??'en'};await this.persist({...vault,appSettings:next});await this.syncPublicPreferences(vault.company.logoDataUrl,next.uiLanguage);this.resetAutoLock();};
  private changePin=async(currentPin:string,newPin:string)=>{const result=await changePin(currentPin,newPin);this.setState({key:result.key});this.showToast(t('PIN changed.','تم تغيير رمز PIN.'),'success');};
  private backup=async(pin:string)=>{const security=await getSecurity();if(!security)throw new Error(t('Security settings are missing.','إعدادات الأمان غير موجودة.'));await verifyPin(pin,security);await exportBackup(pin,this.requireVault());};
  private restore=async(file:File,pin:string)=>{if(!this.state.key)throw new Error(t('App is locked.','التطبيق مقفل.'));const restored=this.normalizedVault(await readBackup(file,pin));const vault=await restoreVaultWithCurrentKey(this.state.key,restored);await this.syncPublicPreferences(vault.company.logoDataUrl,vault.appSettings.uiLanguage);this.setState({vault,screen:'documents',editorDoc:null},this.resetAutoLock);};
  private requireVault():VaultPayload{if(!this.state.vault)throw new Error(t('App is locked.','التطبيق مقفل.'));return this.state.vault;}
  private requestPrint=async(doc:LourexDocument,mode:'print'|'pdf'|'share')=>{try{const errors=validateDocument(doc);if(Object.keys(errors).length)throw new Error(t('Complete the required document fields before printing or sharing.','أكمل الحقول المطلوبة قبل الطباعة أو المشاركة.'));let target={...doc,status:'final' as const,updatedAt:new Date().toISOString()};const vault=this.requireVault();if(vault.documents.some(d=>d.id!==target.id&&d.number.trim().toLowerCase()===target.number.trim().toLowerCase()))throw new Error(t('Document number already exists.','رقم المستند مستخدم بالفعل.'));const idx=vault.documents.findIndex(d=>d.id===target.id);const documents=[...vault.documents];if(idx>=0)documents[idx]=target;else documents.push(target);await this.persist({...vault,documents});const customer=target.customerSnapshot?.companyNameEn||target.customerSnapshot?.companyNameAr||'Customer';const prefix=`LOUREX-${safeFilename(target.number)}-${safeFilename(customer)}`;document.title=prefix;this.setState({printDoc:target},()=>{document.body.classList.add('printing');window.setTimeout(()=>window.print(),70);});if(mode==='pdf')this.showToast(t('PDF print view opened — choose “Save as PDF”.','تم فتح نافذة الطباعة — اختر «حفظ كملف PDF».'),'default');else if(mode==='share')this.showToast(t('System print view opened — save/share the PDF from your device.','تم فتح نافذة النظام — احفظ أو شارك ملف PDF من جهازك.'),'default');}catch(e){this.showToast(e instanceof Error?e.message:t('Unable to prepare document.','تعذر تجهيز المستند.'),'error');}};
  private afterPrint=()=>{document.body.classList.remove('printing');document.title='LOUREX Invoice';this.setState({printDoc:null});};
  private closeEditor=()=>{this.setState({screen:'documents',editorDoc:null});};
  render():any{
    const activeLanguage=this.state.vault?.appSettings.uiLanguage??this.state.uiLanguage;setUiLanguage(activeLanguage);
    if(this.state.loading)return <div className="loading-screen"><Brand logoDataUrl={this.state.publicLogo} language={activeLanguage}/><span className="loading-line"/></div>;
    if(this.state.firstRun)return <AuthScreenSelector mode="setup" company={defaultCompany()} logoDataUrl={this.state.publicLogo} language={activeLanguage} onLanguageChange={this.changePublicLanguage} onFinish={this.finishSetup}/>;
    if(!this.state.unlocked)return <AuthScreenSelector mode="unlock" logoDataUrl={this.state.publicLogo} language={activeLanguage} onLanguageChange={this.changePublicLanguage} onUnlock={this.unlock}/>;
    const vault=this.requireVault();
    return <div className="app-root"><div className="app-ui"><header className="app-header"><button className="header-brand" disabled={this.state.screen==='editor'} onClick={()=>this.setState({screen:'documents',editorDoc:null})}><Brand compact logoDataUrl={vault.company.logoDataUrl} language={activeLanguage}/></button>{this.state.screen!=='editor'?<nav className="main-nav"><button className={this.state.screen==='documents'?'active':''} onClick={()=>this.setState({screen:'documents',editorDoc:null})}><Icon name="file"/>{t('Documents','المستندات')}</button><button className={this.state.screen==='customers'?'active':''} onClick={()=>this.setState({screen:'customers',editorDoc:null})}><Icon name="users"/>{t('Customers','العملاء')}</button></nav>:<div className="header-editor-context">{t('Document Editor','محرر المستند')}</div>}<div className="header-actions">{this.state.screen!=='editor'?<div className="new-doc-menu"><Button icon="plus" variant="primary" onClick={()=>this.setState({newMenu:!this.state.newMenu})}>{t('New Document','مستند جديد')}</Button>{this.state.newMenu?<div className="new-menu"><button onClick={()=>void this.newDocument('proforma')}><Icon name="proforma"/><span><strong>{t('Proforma Invoice','فاتورة مبدئية')}</strong><small>{t('Commercial quotation','عرض تجاري')}</small></span></button><button onClick={()=>void this.newDocument('invoice')}><Icon name="invoice"/><span><strong>{t('Invoice','فاتورة')}</strong><small>{t('Final invoice','فاتورة نهائية')}</small></span></button></div>:null}</div>:null}<IconButton icon="settings" label={t('Settings','الإعدادات')} onClick={()=>this.setState({settingsOpen:true})}/></div></header>
      <main className={this.state.screen==='editor'?'editor-main':'main-content'}>{this.state.screen==='documents'?<DocumentsPage documents={vault.documents} onNew={(k)=>void this.newDocument(k)} onOpen={this.openDocument} onDuplicate={(d)=>void this.duplicate(d)} onPrint={(d,m)=>void this.requestPrint(d,m)} onDelete={(d)=>this.setState({deletingDoc:d})}/>:null}{this.state.screen==='customers'?<CustomersPage customers={vault.customers} onSave={this.saveCustomer} onDelete={this.deleteCustomer}/>:null}{this.state.screen==='editor'&&this.state.editorDoc?<EditorPage document={this.state.editorDoc} customers={vault.customers} company={vault.company} onClose={this.closeEditor} onSave={this.saveDocument} onSaveCustomer={this.saveCustomer} onConvert={this.convert} onPrint={(d,m)=>void this.requestPrint(d,m)}/>:null}</main>
      <SettingsModal open={this.state.settingsOpen} company={vault.company} appSettings={vault.appSettings} onClose={()=>this.setState({settingsOpen:false})} onSaveCompany={this.saveCompany} onSaveAppSettings={this.saveAppSettings} onChangePin={this.changePin} onLock={this.lock} onBackup={this.backup} onRestore={this.restore}/>
      <ConfirmDialog open={Boolean(this.state.deletingDoc)} title={t(`Delete ${this.state.deletingDoc?.number ?? 'document'}?`,`حذف ${this.state.deletingDoc?.number ?? 'المستند'}؟`)} message={t('This action cannot be undone.','لا يمكن التراجع عن هذا الإجراء.')} onCancel={()=>this.setState({deletingDoc:null})} onConfirm={()=>void this.deleteDocument()}/><Toast text={this.state.toast} tone={this.state.toastTone}/></div>
      <div className="print-portal">{this.state.printDoc?<TemplateRenderer document={this.state.printDoc} scale={1}/>:null}</div></div>;
  }
}
