import {conversationalReview,type ConversationalSession} from '../lib/ai-conversational-engine.js';

const R=React as any;

/** Escaped React nodes only: model Markdown never becomes executable HTML. */
export function ConversationMarkdown({text}:{text:string}):any{
  const inline=(value:string)=>value.split(/(\*\*[^*]+\*\*|`[^`]+`)/g).map((part,i)=>part.startsWith('**')?<strong key={i}>{part.slice(2,-2)}</strong>:part.startsWith('`')?<code key={i}>{part.slice(1,-1)}</code>:part);
  const lines=text.split('\n');const blocks:any[]=[];
  for(let i=0;i<lines.length;i++){
    const line=lines[i]!;
    if(line.includes('|')&&/^\s*\|?\s*:?-{3,}/.test(lines[i+1]||'')){
      const cells=(s:string)=>s.trim().replace(/^\||\|$/g,'').split('|').map(v=>v.trim());const head=cells(line),rows:string[][]=[];i+=2;
      while(i<lines.length&&lines[i]!.includes('|')){rows.push(cells(lines[i]!));i++;}i--;
      blocks.push(<div className="lx-conversation-table" key={i} tabIndex={0}><table><thead><tr>{head.map((v,j)=><th key={j}>{inline(v)}</th>)}</tr></thead><tbody>{rows.map((r,k)=><tr key={k}>{head.map((_,j)=><td key={j}>{inline(r[j]||'')}</td>)}</tr>)}</tbody></table></div>);continue;
    }
    if(/^#{1,3}\s/.test(line))blocks.push(<h3 key={i}>{inline(line.replace(/^#{1,3}\s/,''))}</h3>);
    else if(/^[-*]\s/.test(line))blocks.push(<p className="lx-conversation-list" key={i}>• {inline(line.slice(2))}</p>);
    else if(line.trim())blocks.push(<p key={i}>{inline(line)}</p>);
  }
  return <div className="lx-conversation-markdown" dir="auto">{blocks}</div>;
}

export function CommercialDraftView({session,ar,busy,onSelect}:{session:ConversationalSession;ar:boolean;busy:boolean;onSelect:(index:number)=>void;}):any{
  const draft=session.draft;if(!draft)return null;const review=conversationalReview(draft,session.customers);
  const customer=session.customers.find(c=>c.id===draft.customerId);
  return <section className="lx-commercial-draft" aria-label={ar?'معاينة عرض السعر':'Quotation preview'}>
    <div className="lx-draft-heading"><div><small>{ar?'مسودة غير محفوظة':'Unsaved draft'} · {draft.revision}</small><h3>{ar?'عرض السعر الجاري':'Your quotation'}</h3></div><bdi>{draft.currency||'—'}</bdi></div>
    {customer?<p>{ar?'العميل: ':'Customer: '}{customer.name}</p>:<div className="lx-customer-options"><strong>{ar?'اختر العميل عندما تكون جاهزًا':'Choose a customer when ready'}</strong>{session.customers.length?session.customers.map((c,index)=><button type="button" key={c.id} disabled={busy} onClick={()=>onSelect(index+1)}><span>{index+1}</span><bdi>{c.name}</bdi></button>):<p>{ar?'لا يوجد عملاء مسجلون في هذه الشركة. يمكنك إكمال مراجعة الأصناف ثم إضافة العميل من قسم العملاء.':'This company has no saved customers. You can review the products before adding a customer.'}</p>}</div>}
    <div className="lx-conversation-table" tabIndex={0}><table><thead><tr><th>#</th><th>{ar?'الصنف':'Product'}</th><th>{ar?'الكمية':'Quantity'}</th><th>{ar?'سعر الوحدة':'Unit price'}</th><th>{ar?'الإجمالي':'Total'}</th></tr></thead><tbody>{review.lines.map((row,i)=><tr key={row.id}><td>{i+1}</td><td>{row.name}{row.unit?<small>{row.unit}</small>:null}</td><td><bdi>{row.quantity||'—'}</bdi></td><td><bdi>{row.price||'—'}</bdi></td><td><bdi>{row.total||'—'}</bdi></td></tr>)}</tbody></table></div>
    {review.totals?<dl className="lx-draft-totals"><div><dt>{ar?'مجموع الأصناف':'Subtotal'}</dt><dd><bdi>{review.totals.subtotal} {draft.currency}</bdi></dd></div><div><dt>{ar?'الشحن':'Shipping'}</dt><dd><bdi>{review.totals.shipping} {draft.currency}</bdi></dd></div><div><dt>{ar?'الإجمالي':'Total'}</dt><dd><bdi>{review.totals.grandTotal} {draft.currency}</bdi></dd></div></dl>:null}
    <p className="lx-draft-basis">{ar?'الأرقام محسوبة محليًا. الإجمالي المعروض لا يشمل الضريبة أو الخصومات.':'Calculated locally. Displayed total excludes tax and discounts.'}</p>
    <dl className="lx-draft-terms">{[['delivery',ar?'التسليم':'Delivery'],['paymentTerms',ar?'الدفع':'Payment'],['incoterm','Incoterm'],['pallets',ar?'الطبالي':'Pallets'],['containers',ar?'الحاويات':'Containers'],['notes',ar?'ملاحظات':'Notes']].filter(([key])=>draft[key as keyof typeof draft]).map(([key,label])=><div key={key}><dt>{label}</dt><dd>{String(draft[key as keyof typeof draft])}</dd></div>)}</dl>
    {draft.changes.length?<details className="lx-draft-changes" open><summary>{ar?'التغييرات الأخيرة':'Latest changes'}</summary>{draft.changes.map((change,i)=><div key={i}><span>{change.label}</span><del><bdi>{change.before||'—'}</bdi></del><strong><bdi>{change.after}</bdi></strong></div>)}</details>:null}
    {review.missing.length?<div className="lx-draft-missing"><strong>{ar?'نحتاج توضيحًا قبل الحفظ':'Clarify before saving'}</strong><ul>{review.missing.map((v,i)=><li key={i}>{v}</li>)}</ul></div>:<p className="lx-draft-ready">{ar?'جاهز للمراجعة. الحفظ يتطلب زر الموافقة أدناه.':'Ready for review. Saving requires the approval button below.'}</p>}
  </section>;
}

function collect(node:any,predicate:(n:any)=>boolean,out:any[]=[]):any[]{if(!R.isValidElement(node))return out;if(predicate(node)){out.push(node);return out;}R.Children.toArray(node.props.children).forEach((child:any)=>collect(child,predicate,out));return out;}
export function renderConversationWorkspace(instance:any,legacyPanel:any):any{
  const ar=instance.props.language==='ar';const state=instance.state;const session=state.conversationalSession as ConversationalSession|undefined;
  const byClass=(cls:string)=>collect(legacyPanel,n=>String(n.props.className||'').split(' ').includes(cls));
  const header=byClass('lourex-ai-head')[0],navigation=byClass('lourex-ai-context-shell')[0],composer=byClass('lourex-ai-compose')[0],approval=byClass('lourex-ai-proposal')[0];
  const others=R.Children.toArray(legacyPanel.props.children).filter((child:any)=>R.isValidElement(child)&&!['lourex-ai-head','lourex-ai-context-shell','lourex-ai-messages','lourex-ai-proposal','lourex-ai-compose'].some(c=>String(child.props.className||'').split(' ').includes(c)));
  const lastAssistant=[...state.messages].reverse().find((m:any)=>m.role==='assistant');
  return R.cloneElement(legacyPanel,{'data-conversational-workspace':'true',className:'lourex-ai-panel lx-conversation-workspace'},
    <style>{WORKSPACE_CSS}</style>,header,navigation,
    <div className="lx-conversation-body">
      <nav className="lx-conversation-history" aria-label={ar?'سجل المحادثات':'Conversation history'}><strong>LOUREX AI</strong><button type="button" disabled={state.busy} onClick={()=>instance.__lourexNewConversation?.()}>{ar?'＋ محادثة جديدة':'＋ New conversation'}</button>{(state.assistantThreads||[]).map((thread:any)=><button type="button" key={thread.id} disabled={state.busy} onClick={()=>instance.__lourexOpenThread?.(thread.id)} aria-current={thread.id===instance.__lourexAssistantThreadId?'page':undefined}>{thread.title}</button>)}<small>{ar?'الأعمال · شخصي · مؤقت':'Business · Personal · Temporary'}</small></nav>
      <main className="lx-conversation-main"><div className="lx-conversation-transcript" aria-live="polite" role="log">{!state.messages.length?<div className="lx-conversation-welcome"><span>LOUREX AI</span><h2>{ar?'شو بدنا نجهّز اليوم؟':'What shall we work on?'}</h2><p>{ar?'أرسل أفكارك أو الأصناف أو الملفات. نرتّبها معًا ونراجع التفاصيل خطوة بخطوة.':'Send your ideas, products or files. We’ll work through the details together.'}</p><button type="button" onClick={()=>instance.ask(ar?'خلينا نجهز عرض سعر ونراجع الأصناف أولاً':'Let’s prepare a quotation and review the products first')}>{ar?'تجهيز عرض سعر':'Prepare a quotation'}</button></div>:null}{state.messages.map((message:any)=><article key={message.id} className={'lx-conversation-message '+message.role}><small>{message.role==='user'?(ar?'أنت':'You'):'LOUREX'}</small><ConversationMarkdown text={message.text}/>{message.artifact?<div className="lx-saved-document"><strong>{message.artifact.document.number}</strong><button type="button" onClick={()=>window.dispatchEvent(new CustomEvent('lourex-global-search-open',{detail:{query:message.artifact.document.number,autoOpenUnique:true}}))}>{ar?'فتح المستند':'Open document'}</button></div>:null}<div className="lx-conversation-message-actions"><button type="button" onClick={()=>navigator.clipboard?.writeText(message.text)}>{ar?'نسخ':'Copy'}</button>{message.role==='user'?<button type="button" disabled={state.busy} onClick={()=>instance.setState({input:message.text})}>{ar?'تعديل':'Edit'}</button>:message===lastAssistant?<button type="button" disabled={state.busy} onClick={()=>instance.__lourexRetryLast?.()}>{ar?'إعادة الرد':'Regenerate'}</button>:null}</div></article>)}{state.busy||state.attachmentBusy?<div className="lx-conversation-processing" role="status"><span/>{state.attachmentBusy?(ar?'أقرأ الملفات…':'Reading files…'):(ar?'أفهم الطلب وأراجع التفاصيل…':'Understanding your request and checking details…')}<button type="button" onClick={()=>instance.__lourexStopConversation?.()}>{ar?'إيقاف':'Stop'}</button></div>:null}{session?.draft?<CommercialDraftView session={session} ar={ar} busy={state.busy} onSelect={index=>instance.ask(ar?'اختر العميل رقم '+index:'Choose customer number '+index)}/>:null}{approval}{others}</div>{composer}</main>
    </div>);
}

const WORKSPACE_CSS=`
html body #root #lourex-ai-panel[data-conversational-workspace]{position:fixed!important;inset:24px!important;width:auto!important;max-width:1480px!important;margin:auto!important;height:calc(var(--lx-conversation-vh,100dvh) - 48px)!important;max-height:none!important;display:grid!important;grid-template-rows:auto auto minmax(0,1fr)!important;border-radius:24px!important;background:var(--lx-chat-canvas,#f5f7fb)!important;color:var(--lx-chat-text,#172136)!important;overflow:hidden!important;box-shadow:0 30px 110px #0005!important;}
.lx-conversation-body{display:grid;grid-template-columns:230px minmax(0,1fr);min-height:0;overflow:hidden;direction:ltr;}
[dir=rtl] .lx-conversation-body{direction:rtl;}
.lx-conversation-history{background:var(--lx-chat-surface,#fff);border-inline-end:1px solid var(--lx-chat-line,#dce2ec);padding:24px 14px;display:flex;flex-direction:column;gap:10px;overflow:auto;min-height:0;}
.lx-conversation-history strong{font-size:17px;letter-spacing:.07em;margin-bottom:14px;}.lx-conversation-history button{border:0;background:transparent;color:inherit;text-align:start;padding:12px;border-radius:12px;min-height:44px;overflow-wrap:anywhere;}.lx-conversation-history button:hover,.lx-conversation-history button[aria-current]{background:var(--lx-chat-surface-2,#eaf0fc);}.lx-conversation-history small{margin-top:auto;color:var(--lx-chat-muted,#59677b);}
.lx-conversation-main{display:grid;grid-template-rows:minmax(0,1fr) auto;min-height:0;min-width:0;overflow:hidden;}
.lx-conversation-transcript{overflow:auto;overscroll-behavior:contain;min-width:0;padding:32px max(24px,calc((100% - 900px)/2));scroll-padding-bottom:24px;}
.lx-conversation-message{max-width:100%;margin:0 0 26px;overflow-wrap:anywhere;line-height:1.75;}.lx-conversation-message>small{font-size:12px;font-weight:700;color:var(--lx-chat-muted,#59677b);}.lx-conversation-message.user{width:fit-content;max-width:85%;margin-left:auto;background:var(--lx-chat-user-bg,#e5edff);color:var(--lx-chat-text,#172136);padding:12px 20px;border-radius:20px 20px 5px 20px;}.lx-conversation-message.assistant{padding:2px 0 18px;border-bottom:1px solid var(--lx-chat-line,#dce2ec);}
.lx-conversation-markdown p{margin:8px 0;white-space:pre-wrap;}.lx-conversation-markdown h3{font-size:18px;margin:12px 0 8px;}.lx-conversation-markdown code{background:var(--lx-chat-surface-2,#eaf0fc);border-radius:5px;padding:2px 5px;}.lx-conversation-message-actions{display:flex;gap:6px;margin-top:10px;}.lx-conversation-message-actions button{border:0;background:transparent;color:var(--lx-chat-muted,#59677b);padding:8px 10px;min-height:44px;}
.lx-conversation-welcome{padding:8vh 0;max-width:600px;margin:auto;}.lx-conversation-welcome>span{color:var(--lx-chat-accent,#326ce5);font-weight:700;letter-spacing:.12em;}.lx-conversation-welcome h2{font-size:clamp(26px,4vw,40px);margin:14px 0;}.lx-conversation-welcome p{line-height:1.8;color:var(--lx-chat-muted,#59677b);}.lx-conversation-welcome button{padding:12px 18px;border:1px solid var(--lx-chat-line,#dce2ec);border-radius:12px;background:var(--lx-chat-surface,#fff);color:inherit;min-height:44px;}
.lx-commercial-draft{margin:18px 0 24px;padding:22px;border:1px solid var(--lx-chat-line,#dce2ec);border-radius:18px;background:var(--lx-chat-surface,#fff);}.lx-draft-heading{display:flex;align-items:center;justify-content:space-between;gap:16px;}.lx-draft-heading h3{margin:5px 0 16px;}.lx-draft-heading small{color:var(--lx-chat-muted,#59677b);}.lx-draft-heading>bdi{font-weight:700;color:var(--lx-chat-accent,#326ce5);}
.lx-conversation-table{overflow:auto;max-width:100%;border:1px solid var(--lx-chat-line,#dce2ec);border-radius:12px;margin:12px 0;}.lx-conversation-table table{width:100%;border-collapse:collapse;text-align:start;font-size:14px;}.lx-conversation-table :is(th,td){padding:12px 14px;border-bottom:1px solid var(--lx-chat-line,#dce2ec);text-align:start;white-space:nowrap;}.lx-conversation-table th{background:var(--lx-chat-surface-2,#eaf0fc);font-size:12px;}.lx-conversation-table td small{display:block;color:var(--lx-chat-muted,#59677b);}.lx-conversation-table td:nth-child(2){white-space:normal;min-width:140px;}
.lx-customer-options{display:grid;grid-template-columns:repeat(auto-fit,minmax(180px,1fr));gap:8px;margin:12px 0 18px;}.lx-customer-options>strong,.lx-customer-options>p{grid-column:1/-1;}.lx-customer-options button{display:flex;align-items:center;gap:12px;min-height:52px;border:1px solid var(--lx-chat-line,#dce2ec);border-radius:12px;background:var(--lx-chat-surface-2,#eaf0fc);color:inherit;padding:10px 12px;text-align:start;}.lx-customer-options button span{color:var(--lx-chat-accent,#326ce5);font-weight:700;}
.lx-draft-totals{max-width:380px;margin-inline-start:auto;}.lx-draft-totals>div,.lx-draft-terms>div{display:flex;justify-content:space-between;gap:18px;padding:8px 0;}.lx-draft-totals dd,.lx-draft-terms dd{margin:0;}.lx-draft-totals>div:last-child{border-top:1px solid var(--lx-chat-line,#dce2ec);font-size:18px;font-weight:700;}.lx-draft-terms{font-size:13px;color:var(--lx-chat-muted,#59677b);}.lx-draft-changes{padding:12px 0;}.lx-draft-changes>div{display:flex;flex-wrap:wrap;gap:12px;padding-top:8px;font-size:13px;}.lx-draft-changes del{color:var(--lx-chat-muted,#59677b);}.lx-draft-changes strong{color:var(--lx-chat-accent,#326ce5);}.lx-draft-missing{background:var(--lx-chat-surface-2,#eaf0fc);border-radius:12px;padding:14px;font-size:13px;}.lx-draft-missing ul{padding-inline-start:20px;}.lx-draft-ready{color:var(--lx-chat-accent,#326ce5);font-size:13px;}
.lx-conversation-processing{display:flex;gap:12px;align-items:center;padding:18px 0;color:var(--lx-chat-muted,#59677b);}.lx-conversation-processing>span{width:8px;height:8px;border-radius:50%;background:var(--lx-chat-accent,#326ce5);}.lx-conversation-processing button{margin-inline-start:auto;min-height:44px;padding:8px 14px;border-radius:10px;border:1px solid var(--lx-chat-line,#dce2ec);background:var(--lx-chat-surface,#fff);color:inherit;}
html body #root #lourex-ai-panel[data-conversational-workspace] .lourex-ai-compose{width:100%!important;max-width:none!important;padding:14px max(24px,calc((100% - 900px)/2)) max(14px,env(safe-area-inset-bottom))!important;}.lx-saved-document{border:1px solid var(--lx-chat-line,#dce2ec);border-radius:12px;padding:12px;display:flex;justify-content:space-between;gap:12px;}
@media(max-width:1024px){.lx-conversation-body{grid-template-columns:180px minmax(0,1fr);}.lx-conversation-transcript{padding:24px;}}
@media(max-width:820px){html body #root #lourex-ai-panel[data-conversational-workspace]{inset:0!important;top:var(--lx-conversation-top,0px)!important;bottom:auto!important;height:var(--lx-conversation-vh,100dvh)!important;width:100vw!important;border-radius:0!important;padding-top:env(safe-area-inset-top)!important;}.lx-conversation-body{grid-template-columns:minmax(0,1fr);}.lx-conversation-history{display:none;}.lx-conversation-transcript{padding:20px 14px;}.lx-commercial-draft{padding:14px;}.lx-conversation-table :is(th,td){padding:10px;}.lx-conversation-message.user{max-width:90%;}html body #root #lourex-ai-panel[data-conversational-workspace] .lourex-ai-compose{padding:10px 8px max(10px,env(safe-area-inset-bottom))!important;}}
`;
