import { askBusinessRecords, type BusinessSearchAnswer } from '../lib/business-search-ai.js';
import { isArabic, t } from '../lib/i18n.js';
import { resumeVaultSession } from '../storage/vault.js';
import { Button, Field, Input, Modal } from './UI.js';

interface State{open:boolean;busy:boolean;query:string;answer:BusinessSearchAnswer|null;error:string;}
function openCanonical(label:string):void{window.dispatchEvent(new CustomEvent('lourex-global-search-open',{detail:{query:label,autoOpenUnique:true}}));}
function advisorInput(answer:BusinessSearchAnswer,query:string):void{
  const input=document.querySelector<HTMLInputElement>('#lourex-ai-panel .lourex-ai-compose input');if(!input)return;
  const facts=answer.facts.slice(0,5).map(row=>`${row.label}: ${row.value} (${row.detail})`).join('; ');const prompt=isArabic()?`فسر نتيجة بحث LOUREX التالية بدون اختراع أي بيانات: السؤال: ${query}. النتيجة الحتمية: ${answer.summary}. ${facts}. القيود: ${answer.limitations.join('، ')}.`:`Explain this deterministic LOUREX search result without inventing data. Question: ${query}. Result: ${answer.summary}. ${facts}. Limitations: ${answer.limitations.join(', ')}.`;
  const setter=Object.getOwnPropertyDescriptor(HTMLInputElement.prototype,'value')?.set;if(setter)setter.call(input,prompt.slice(0,1000));else input.value=prompt.slice(0,1000);input.dispatchEvent(new Event('input',{bubbles:true}));input.focus();input.setSelectionRange(input.value.length,input.value.length);
}
export class BusinessSearchTool extends React.Component<{},State>{
  state:State={open:false,busy:false,query:'',answer:null,error:''};
  private open=()=>this.setState({open:true,query:'',answer:null,error:''});
  private search=async()=>{const query=this.state.query.trim();if(!query||this.state.busy)return;this.setState({busy:true,error:''});try{const resumed=await resumeVaultSession();if(!resumed)throw new Error(t('Unlock LOUREX before searching business records.','افتح قفل LOUREX قبل البحث في سجلات الأعمال.'));this.setState({busy:false,answer:askBusinessRecords(resumed.vault,query)});}catch(error){this.setState({busy:false,error:error instanceof Error?error.message:String(error)});}};
  private ask=()=>{const answer=this.state.answer;if(!answer)return;advisorInput(answer,this.state.query);this.setState({open:false});};
  render():any{const answer=this.state.answer;return <><Button icon="search" onClick={this.open}>{t('Ask Anything','اسأل عن أي شيء')}</Button><Modal open={this.state.open} title={t('LOUREX Business Search','بحث أعمال LOUREX')} size="lg" onClose={()=>{if(!this.state.busy)this.setState({open:false});}}><Field label={t('Ask about customers, documents, products, suppliers or purchases','اسأل عن العملاء أو المستندات أو المنتجات أو الموردين أو المشتريات')}><Input autoFocus value={this.state.query} onChange={(event:any)=>this.setState({query:event.target.value,answer:null,error:''})} onKeyDown={(event:any)=>{if(event.key==='Enter'){event.preventDefault();void this.search();}}} placeholder={t('e.g. last purchase price for Nescafe','مثال: كم آخر سعر شراء للنسكافيه؟')}/></Field><div className="ta-customer-modal-actions"><Button variant="primary" disabled={this.state.busy||!this.state.query.trim()} onClick={()=>void this.search()}>{this.state.busy?t('Searching…','جارٍ البحث…'):t('Search LOUREX','ابحث في LOUREX')}</Button></div>{this.state.error?<div role="alert">{this.state.error}</div>:null}{answer?<div><h3>{answer.summary}</h3>{answer.facts.length?<div>{answer.facts.map((fact,index)=><article key={`${fact.label}-${index}`} style={{padding:'8px 0'}}><strong><bdi dir="auto">{fact.label}</bdi></strong><span style={{display:'block'}}><bdi dir="auto">{fact.value}</bdi></span><small><bdi dir="auto">{fact.detail}</bdi></small></article>)}</div>:null}{answer.results.length?<div>{answer.results.map(result=><button type="button" key={`${result.kind}-${result.id}`} onClick={()=>{this.setState({open:false});window.setTimeout(()=>openCanonical(result.label),0);}} style={{display:'block',width:'100%',textAlign:isArabic()?'right':'left',padding:'10px',marginTop:'6px'}}><strong><bdi dir="auto">{result.label}</bdi></strong><small style={{display:'block'}}>{result.kind} · <bdi dir="auto">{result.detail}</bdi></small></button>)}</div>:null}{answer.limitations.length?<p><small>{t('Limits','القيود')}: {answer.limitations.join(' · ')}</small></p>:null}<div className="ta-customer-modal-actions"><Button onClick={this.ask}>{t('Ask LOUREX to explain','اطلب من LOUREX الشرح')}</Button></div></div>:null}</Modal></>;}
}
