import { isArabic, t } from '../lib/i18n.js';
import { buildBusinessMemory, type BusinessMemoryEntry } from '../lib/business-memory.js';
import { resumeVaultSession } from '../storage/vault.js';
import { Button, Icon, Modal } from './UI.js';

interface State{open:boolean;busy:boolean;entries:BusinessMemoryEntry[];error:string;}
function kindLabel(kind:BusinessMemoryEntry['kind']):string{if(kind==='opportunity')return t('Opportunity','فرصة متابعة');if(kind==='customer-pattern')return t('Customer pattern','نمط عميل');if(kind==='supplier-pattern')return t('Supplier pattern','نمط مورد');if(kind==='product-pattern')return t('Product pattern','نمط منتج');return t('Commercial pattern','نمط تجاري');}
function askAdvisor(entry:BusinessMemoryEntry):void{const input=document.querySelector<HTMLInputElement>('#lourex-ai-panel .lourex-ai-compose input');if(!input)return;const text=isArabic()?`اشرح لي هذه الإشارة من ذاكرة الأعمال وقل لي ما الخطوة المناسبة للمراجعة، بدون تنفيذ تلقائي: ${entry.title} — ${entry.detail}`:`Explain this LOUREX Business Memory signal and the appropriate review action without taking any automatic action: ${entry.title} — ${entry.detail}`;const setter=Object.getOwnPropertyDescriptor(HTMLInputElement.prototype,'value')?.set;if(setter)setter.call(input,text.slice(0,1000));else input.value=text.slice(0,1000);input.dispatchEvent(new Event('input',{bubbles:true}));window.setTimeout(()=>input.form?.requestSubmit(),0);}

export class BusinessMemoryPanel extends React.Component<{},State>{
  state:State={open:false,busy:false,entries:[],error:''};
  private open=async()=>{this.setState({open:true,busy:true,error:''});try{const resumed=await resumeVaultSession();if(!resumed)throw new Error(t('Unlock LOUREX before reading Business Memory.','افتح قفل LOUREX قبل قراءة ذاكرة الأعمال.'));const memory=buildBusinessMemory(resumed.vault);this.setState({entries:memory.entries,busy:false});}catch(error){this.setState({busy:false,error:error instanceof Error?error.message:String(error)});}};
  private close=()=>this.setState({open:false,error:''});
  private ask=(entry:BusinessMemoryEntry)=>{this.close();askAdvisor(entry);};
  render():any{return <><Button icon="bot" onClick={()=>void this.open()}>{t('Memory Insights','رؤى الذاكرة')}</Button><Modal open={this.state.open} title={t('LOUREX Business Memory','ذاكرة أعمال LOUREX')} size="lg" onClose={this.close}><div>{this.state.busy?<div role="status"><Icon name="bot"/> {t('Deriving patterns from approved history…','اشتقاق الأنماط من السجل المعتمد…')}</div>:null}<div className="product-import-mapping-note"><Icon name="lock"/><span>{t('These are derived suggestions, not official master data. Nothing is permanently stored as a new memory and no default, message or price is applied automatically.','هذه اقتراحات مشتقة وليست بيانات رئيسية رسمية. لا يتم تخزينها كذاكرة جديدة ولا يتم تطبيق أي إعداد افتراضي أو رسالة أو سعر تلقائيًا.')}</span></div>{this.state.entries.length?<div>{this.state.entries.map(entry=><article key={entry.key} style={{padding:'10px 0'}}><small>{kindLabel(entry.kind)} · {entry.confidence==='high'?t('High evidence','أدلة قوية'):t('Medium evidence','أدلة متوسطة')} · {entry.evidenceCount}</small><strong style={{display:'block'}}><bdi dir="auto">{entry.title}</bdi></strong><p><bdi dir="auto">{entry.detail}</bdi></p><Button onClick={()=>this.ask(entry)}>{t('Ask LOUREX about this','اسأل LOUREX عن هذا')}</Button></article>)}</div>:!this.state.busy?<p>{t('Not enough approved history yet to derive durable patterns.','لا يوجد سجل معتمد كافٍ بعد لاشتقاق أنماط ثابتة.')}</p>:null}{this.state.error?<div className="inline-error" role="alert">{this.state.error}</div>:null}<div className="ta-customer-modal-actions"><Button onClick={this.close}>{t('Close','إغلاق')}</Button></div></div></Modal></>;}
}
