import type { CloudUser } from '../cloud/firebase.js';
import { installCloudVault } from '../cloud/firebase.js';
import { t } from '../lib/i18n.js';
import { Button, Field, Input, Modal } from './UI.js';

interface Props {
  open:boolean;
  user:CloudUser|null;
  syncState:'local'|'queued'|'syncing'|'synced'|'offline'|'error';
  syncMessage:string;
  onClose:()=>void;
  onSignIn:(email:string,password:string)=>Promise<void>;
  onCreate:(email:string,password:string)=>Promise<void>;
  onReset:(email:string)=>Promise<void>;
  onSync:()=>Promise<void>;
  onSignOut:()=>Promise<void>;
}
interface State { mode:'signin'|'create'; email:string; password:string; confirm:string; busy:boolean; error:string; message:string; }

export class CloudAccountModal extends React.Component<Props,State>{
  state:State={mode:'signin',email:'',password:'',confirm:'',busy:false,error:'',message:''};
  componentDidUpdate(prev:Props):void{if(this.props.open&&!prev.open)this.setState({mode:'signin',email:this.props.user?.email||'',password:'',confirm:'',busy:false,error:'',message:''});}
  private requestClose=()=>{if(!this.state.busy)this.props.onClose();};
  private run=async(action:()=>Promise<void>,success='')=>{if(this.state.busy)return;this.setState({busy:true,error:'',message:''});try{await action();this.setState({busy:false,password:'',confirm:'',message:success});}catch(e){this.setState({busy:false,error:e instanceof Error?e.message:t('Account operation failed.','فشلت عملية الحساب.')});}};
  private submit=async(e:any)=>{e.preventDefault();if(this.state.busy)return;const email=this.state.email.trim();if(!email||!this.state.password)return this.setState({error:t('Enter your email and password.','أدخل البريد الإلكتروني وكلمة المرور.')});if(this.state.mode==='create'&&this.state.password!==this.state.confirm)return this.setState({error:t('Password confirmation does not match.','تأكيد كلمة المرور غير مطابق.')});if(this.state.mode==='create'&&this.state.password.length<6)return this.setState({error:t('Password must contain at least 6 characters.','يجب أن تحتوي كلمة المرور على 6 أحرف على الأقل.')});await this.run(()=>this.state.mode==='create'?this.props.onCreate(email,this.state.password):this.props.onSignIn(email,this.state.password));};
  private restoreFromCloud=async()=>{const user=this.props.user;if(!user||this.state.busy)return;this.setState({busy:true,error:'',message:''});try{const restored=await installCloudVault(user.uid,false);if(!restored)throw new Error(t('No cloud data exists for this account yet.','لا توجد بيانات سحابية محفوظة لهذا الحساب حتى الآن.'));this.setState({message:t('Account data restored from the cloud.','تم استرجاع بيانات الحساب من السحابة.')});window.setTimeout(()=>window.location.reload(),220);}catch(e){this.setState({busy:false,error:e instanceof Error?e.message:t('Unable to restore account data.','تعذر استرجاع بيانات الحساب.')});}};
  render():any{return <Modal open={this.props.open} title={t('Account','الحساب')} size="sm" onClose={this.requestClose}>{this.props.user?<div className="cloud-account-panel"><div className="cloud-account-identity"><div><strong>{this.props.user.email}</strong><small>{t('Your LOUREX data is saved automatically to this account.','يتم حفظ بيانات LOUREX تلقائيًا في هذا الحساب.')}</small></div></div>{this.state.error?<div className="auth-error" role="alert">{this.state.error}</div>:null}{this.state.message?<div className="settings-message success" role="status">{this.state.message}</div>:null}<div className="cloud-account-actions"><Button variant="primary" disabled={this.state.busy} onClick={()=>void this.restoreFromCloud()}>{this.state.busy?t('Restoring…','جارٍ الاسترجاع…'):t('Restore from Cloud','استرجاع من السحابة')}</Button><Button disabled={this.state.busy} onClick={()=>void this.run(this.props.onSignOut)}>{t('Sign Out','تسجيل الخروج')}</Button></div></div>:<form className="cloud-auth-form" onSubmit={this.submit}><div className="segmented cloud-auth-tabs"><button type="button" disabled={this.state.busy} className={this.state.mode==='signin'?'active':''} onClick={()=>this.setState({mode:'signin',error:'',message:''})}>{t('Sign In','تسجيل الدخول')}</button><button type="button" disabled={this.state.busy} className={this.state.mode==='create'?'active':''} onClick={()=>this.setState({mode:'create',error:'',message:''})}>{t('Create Account','إنشاء حساب')}</button></div><Field label={t('Email','البريد الإلكتروني')}><Input type="email" autoComplete="email" value={this.state.email} onChange={(e:any)=>this.setState({email:e.target.value,error:''})}/></Field><Field label={t('Password','كلمة المرور')}><Input type="password" autoComplete={this.state.mode==='create'?'new-password':'current-password'} value={this.state.password} onChange={(e:any)=>this.setState({password:e.target.value,error:''})}/></Field>{this.state.mode==='create'?<Field label={t('Confirm Password','تأكيد كلمة المرور')}><Input type="password" autoComplete="new-password" value={this.state.confirm} onChange={(e:any)=>this.setState({confirm:e.target.value,error:''})}/></Field>:null}{this.state.error?<div className="auth-error" role="alert">{this.state.error}</div>:null}{this.state.message?<div className="settings-message success" role="status">{this.state.message}</div>:null}<Button variant="primary" disabled={this.state.busy} type="submit">{this.state.busy?t('Please wait…','يرجى الانتظار…'):this.state.mode==='create'?t('Create Account','إنشاء حساب'):t('Sign In','تسجيل الدخول')}</Button>{this.state.mode==='signin'?<button type="button" className="cloud-reset-link" disabled={this.state.busy||!this.state.email.trim()} onClick={()=>void this.run(()=>this.props.onReset(this.state.email.trim()),t('Password reset email sent.','تم إرسال رسالة إعادة تعيين كلمة المرور.'))}>{t('Forgot password?','نسيت كلمة المرور؟')}</button>:null}</form>}</Modal>;}
}
