import { buildCollectionTasks, type CollectionInvoiceReference, type CollectionTask } from '../lib/collections-workflow.js';
import { todayIso } from '../lib/id.js';
import { isArabic, t } from '../lib/i18n.js';
import { resumeVaultSession } from '../storage/vault.js';
import { Button, Icon, Modal } from './UI.js';

interface Props{launcher?:boolean;}
interface State{open:boolean;busy:boolean;rows:CollectionTask[];asOf:string;error:string;}
const OPEN_EVENT='lourex-ai-open-collections';

function moneyRows(customer:CollectionTask,key:'outstanding'|'overdue'):string{return customer.currencies.map(row=>`${row[key]} ${row.currency}`).filter(value=>!value.startsWith('0.00 ')).join(' · ')||'0';}
function agingText(customer:CollectionTask):string{return customer.currencies.map(row=>`${row.currency}: 1–30 ${row.aging.days1to30} · 31–60 ${row.aging.days31to60} · 61–90 ${row.aging.days61to90} · 90+ ${row.aging.days90plus}`).join(' | ');}
function dayNumber(iso:string):number{const [y,m,d]=iso.split('-').map(Number);return Math.floor(Date.UTC(y||0,(m||1)-1,d||1)/86_400_000);}
function daysLate(invoice:CollectionInvoiceReference|null,asOf:string):number{if(!invoice?.dueDate)return 0;return Math.max(0,dayNumber(asOf)-dayNumber(invoice.dueDate));}
function advisorPrompt(prompt:string):void{const input=document.querySelector<HTMLInputElement>('#lourex-ai-panel .lourex-ai-compose input');if(!input)return;const setter=Object.getOwnPropertyDescriptor(HTMLInputElement.prototype,'value')?.set;if(setter)setter.call(input,prompt.slice(0,1000));else input.value=prompt.slice(0,1000);input.dispatchEvent(new Event('input',{bubbles:true}));window.setTimeout(()=>input.form?.requestSubmit(),0);}
function globalAction(detail:any):void{window.dispatchEvent(new CustomEvent('lourex-global-action',{detail}));}

export class CollectionsAiTool extends React.Component<Props,State>{
  state:State={open:false,busy:false,rows:[],asOf:'',error:''};
  componentDidMount():void{window.addEventListener(OPEN_EVENT,this.handleOpen);}
  componentWillUnmount():void{window.removeEventListener(OPEN_EVENT,this.handleOpen);}
  private handleOpen=()=>{void this.open();};
  private open=async()=>{if(this.state.busy)return;this.setState({open:true,busy:true,error:''});try{const resumed=await resumeVaultSession();if(!resumed)throw new Error(t('Unlock LOUREX before opening Collections AI.','افتح قفل LOUREX قبل فتح ذكاء التحصيل.'));const asOf=todayIso();const rows=buildCollectionTasks(resumed.vault,asOf);this.setState({busy:false,rows,asOf});}catch(error){this.setState({busy:false,error:error instanceof Error?error.message:String(error)});}};
  private close=()=>this.setState({open:false,error:''});
  private draftReminder=(row:CollectionTask,strong=false)=>{const late=daysLate(row.oldestOverdueInvoice,this.state.asOf||todayIso());const prompt=isArabic()?`جهز رسالة تحصيل ${strong?'حازمة ومهنية':'لطيفة ومهنية'} للعميل ${row.customerName}. لا ترسلها. استخدم فقط هذه الحقائق من LOUREX: المستحق ${moneyRows(row,'outstanding')}، المتأخر ${moneyRows(row,'overdue')}${row.oldestOverdueInvoice?`، أقدم فاتورة متأخرة ${row.oldestOverdueInvoice.number} ومتأخرة ${late} يوم`:''}. لا تخترع وعد دفع أو رقم فاتورة غير موجود، وأعطني مسودة رسالة فقط.`:`Draft a ${strong?'firm but professional':'polite professional'} collection reminder for ${row.customerName}. Do not send it. Use only these LOUREX facts: outstanding ${moneyRows(row,'outstanding')}; overdue ${moneyRows(row,'overdue')}${row.oldestOverdueInvoice?`; oldest overdue invoice ${row.oldestOverdueInvoice.number}, ${late} days late`:''}. Do not invent payment promises or invoice numbers. Return a message draft only.`;this.close();advisorPrompt(prompt);};
  private showInvoices=(row:CollectionTask)=>{this.close();window.dispatchEvent(new CustomEvent('lourex-global-search-open',{detail:{query:row.customerName,autoOpenUnique:false}}));};
  private statement=(row:CollectionTask)=>{this.close();globalAction({action:'statement',customerId:row.customerId});};
  private payment=(row:CollectionTask)=>{if(!row.oldestOpenInvoice)return;this.close();globalAction({action:'payment',invoiceId:row.oldestOpenInvoice.invoiceId});};
  render():any{return <>{this.props.launcher===false?null:<Button icon="invoice" onClick={()=>void this.open()}>{t('Collections AI','ذكاء التحصيل')}</Button>}<Modal portal open={this.state.open} title={t('Customers Requiring Follow-up Today','العملاء الذين يحتاجون متابعة اليوم')} size="xl" onClose={this.close}>{this.state.busy?<p role="status">{t('Calculating receivables, aging and payment behavior…','حساب المستحقات وأعمار الديون وسلوك الدفع…')}</p>:this.state.error?<div className="inline-error" role="alert">{this.state.error}</div>:<div><div className="product-import-mapping-note"><Icon name="lock"/><span>{t('Priorities are derived from recorded receivables, aging and payment history. Draft Reminder never sends a message automatically. Currencies stay separate.','الأولويات مشتقة من المستحقات وأعمار الديون وسجل الدفع. زر مسودة التذكير لا يرسل أي رسالة تلقائيًا. تبقى العملات منفصلة.')}</span></div>{this.state.rows.length?this.state.rows.map(row=>{const late=daysLate(row.oldestOverdueInvoice,this.state.asOf);return <article key={row.customerId} style={{padding:'12px 0'}}><header><small>{row.priority==='high'?t('High priority','أولوية عالية'):row.priority==='medium'?t('Medium priority','أولوية متوسطة'):t('Follow-up','متابعة')}</small><strong style={{display:'block'}}>{row.customerName}</strong></header><p><strong>{t('Outstanding','المستحق')}:</strong> {moneyRows(row,'outstanding')} · <strong>{t('Overdue','المتأخر')}:</strong> {moneyRows(row,'overdue')}</p><p><small>{t('Oldest open invoice','أقدم فاتورة مفتوحة')}: {row.oldestOpenInvoice?`${row.oldestOpenInvoice.number} · ${row.oldestOpenInvoice.issueDate}`:'—'}{row.oldestOverdueInvoice?` · ${t('oldest overdue','أقدم متأخر')} ${late} ${t('days','يوم')}`:''}</small><br/><small>{t('Average days to pay','متوسط أيام الدفع')}: {row.averageDaysToPay??'—'} · {t('Average days late','متوسط أيام التأخير')}: {row.averageDaysLate??'—'} · {t('Open invoices','الفواتير المفتوحة')}: {row.openInvoices.length} · {t('Last activity','آخر نشاط')}: {row.lastActivity||'—'}</small></p><details><summary>{t('Aging details','تفاصيل أعمار الديون')}</summary><small>{agingText(row)}</small></details><div className="ta-customer-modal-actions"><Button onClick={()=>this.draftReminder(row,false)}>{t('Draft Reminder','مسودة تذكير')}</Button>{late>=45?<Button onClick={()=>this.draftReminder(row,true)}>{t('Draft Stronger Reminder','مسودة أقوى')}</Button>:null}<Button onClick={()=>this.showInvoices(row)}>{t('Show Invoices','عرض الفواتير')}</Button><Button onClick={()=>this.statement(row)}>{t('Open Statement','فتح كشف الحساب')}</Button><Button variant="primary" disabled={!row.oldestOpenInvoice} onClick={()=>this.payment(row)}>{t('Record Payment','تسجيل دفعة')}</Button></div></article>;}):<p>{t('No customer currently has an outstanding balance requiring follow-up.','لا يوجد حاليًا عميل لديه رصيد مستحق يحتاج متابعة.')}</p>}</div>}</Modal></>;}
}
