import type { Customer } from '../types.js';
import { makeId } from '../lib/id.js';
import { isArabic, t } from '../lib/i18n.js';
import { Button, ConfirmDialog, Field, Icon, IconButton, Input, Modal, Textarea } from './UI.js';

export function blankCustomer(): Customer { const now=new Date().toISOString(); return { id:makeId('customer'),createdAt:now,updatedAt:now,companyNameEn:'',companyNameAr:'',contactPerson:'',addressEn:'',addressAr:'',city:'',country:'',phone:'',email:'',vatTaxNumber:'',commercialRegistration:'',notes:''}; }

interface FormProps { customer: Customer; onChange: (c:Customer)=>void; }
export function CustomerForm({customer,onChange}:FormProps): any {
  const set=(key:keyof Customer,value:string)=>onChange({...customer,[key]:value,updatedAt:new Date().toISOString()});
  const arabic=isArabic();
  return <div className="form-grid two"><Field label={t('Company Name English','اسم الشركة بالإنجليزية')}><Input autoFocus={!arabic} value={customer.companyNameEn} onChange={(e:any)=>set('companyNameEn',e.target.value)}/></Field><Field label={t('Company Name Arabic','اسم الشركة بالعربية')}><Input autoFocus={arabic} dir="rtl" value={customer.companyNameAr} onChange={(e:any)=>set('companyNameAr',e.target.value)}/></Field><Field label={t('Contact Person','جهة الاتصال')}><Input value={customer.contactPerson} onChange={(e:any)=>set('contactPerson',e.target.value)}/></Field><Field label={t('Email','البريد الإلكتروني')}><Input type="email" autoComplete="email" value={customer.email} onChange={(e:any)=>set('email',e.target.value)}/></Field><Field label={t('Address English','العنوان بالإنجليزية')}><Input value={customer.addressEn} onChange={(e:any)=>set('addressEn',e.target.value)}/></Field><Field label={t('Address Arabic','العنوان بالعربية')}><Input dir="rtl" value={customer.addressAr} onChange={(e:any)=>set('addressAr',e.target.value)}/></Field><Field label={t('City','المدينة')}><Input value={customer.city} onChange={(e:any)=>set('city',e.target.value)}/></Field><Field label={t('Country','الدولة')}><Input value={customer.country} onChange={(e:any)=>set('country',e.target.value)}/></Field><Field label={t('Phone','الهاتف')}><Input type="tel" inputMode="tel" autoComplete="tel" value={customer.phone} onChange={(e:any)=>set('phone',e.target.value)}/></Field><Field label={t('VAT / Tax Number','رقم الضريبة / القيمة المضافة')}><Input value={customer.vatTaxNumber} onChange={(e:any)=>set('vatTaxNumber',e.target.value)}/></Field><Field label={t('Commercial Registration','السجل التجاري')}><Input value={customer.commercialRegistration} onChange={(e:any)=>set('commercialRegistration',e.target.value)}/></Field><Field label={t('Notes','ملاحظات')} className="span-2"><Textarea rows="3" value={customer.notes} onChange={(e:any)=>set('notes',e.target.value)}/></Field></div>;
}

interface Props { customers: Customer[]; onSave: (customer:Customer)=>Promise<void>; onDelete:(customer:Customer)=>Promise<void>; }
interface State { query:string; editing:Customer|null; deleting:Customer|null; error:string; busy:boolean; }
export class CustomersPage extends React.Component<Props,State> {
  state:State={query:'',editing:null,deleting:null,error:'',busy:false};
  private filtered():Customer[]{const q=this.state.query.trim().toLowerCase();const arabic=isArabic();return this.props.customers.filter(c=>!q||c.companyNameEn.toLowerCase().includes(q)||c.companyNameAr.includes(this.state.query.trim())||c.contactPerson.toLowerCase().includes(q)).sort((a,b)=>{const an=(arabic?(a.companyNameAr||a.companyNameEn):(a.companyNameEn||a.companyNameAr)).trim();const bn=(arabic?(b.companyNameAr||b.companyNameEn):(b.companyNameEn||b.companyNameAr)).trim();return an.localeCompare(bn,arabic?'ar':'en',{sensitivity:'base'});});}
  private save=async()=>{const c=this.state.editing;if(!c)return;if(!c.companyNameEn.trim()&&!c.companyNameAr.trim()){this.setState({error:t('Company name is required.','اسم الشركة مطلوب.')});return;}this.setState({busy:true,error:''});try{await this.props.onSave(c);this.setState({editing:null,busy:false,error:''});}catch(e){this.setState({error:e instanceof Error?e.message:t('Unable to save customer.','تعذر حفظ العميل.'),busy:false});}};
  private remove=async()=>{const c=this.state.deleting;if(!c||this.state.busy)return;this.setState({busy:true,error:''});try{await this.props.onDelete(c);this.setState({deleting:null,busy:false,error:''});}catch(e){this.setState({busy:false,error:e instanceof Error?e.message:t('Unable to delete customer.','تعذر حذف العميل.')});}};
  render():any{const customers=this.filtered();return <section className="page customers-page"><div className="page-heading"><div><p className="eyebrow">{t('Address book','دليل العملاء')}</p><h1>{t('Customers','العملاء')}</h1></div><Button icon="plus" variant="primary" onClick={()=>this.setState({editing:blankCustomer(),error:''})}>{t('Add Customer','إضافة عميل')}</Button></div><div className="list-toolbar customers-toolbar"><div className="search-box"><Icon name="search"/><Input aria-label={t('Search customers','بحث في العملاء')} placeholder={t('Search customers','ابحث في العملاء')} value={this.state.query} onChange={(e:any)=>this.setState({query:e.target.value})}/></div></div>{this.state.error&&!this.state.editing?<div className="inline-error" role="alert">{this.state.error}</div>:null}{customers.length?<div className="customer-list">{customers.map(c=>{const primary=isArabic()?(c.companyNameAr||c.companyNameEn):(c.companyNameEn||c.companyNameAr);return <article className="customer-card" key={c.id}><div className="customer-avatar">{(primary||'C').trim().charAt(0).toUpperCase()}</div><div className="customer-info"><strong>{primary}</strong>{c.companyNameAr&&c.companyNameEn?<span dir={isArabic()?'ltr':'rtl'}>{isArabic()?c.companyNameEn:c.companyNameAr}</span>:null}<small>{[c.city,c.country].filter(Boolean).join(', ')||t('No location','لا يوجد موقع')}</small><small>{[c.email,c.phone].filter(Boolean).join(' · ')}</small></div><div className="customer-actions"><IconButton icon="edit" label={t('Edit','تعديل')} onClick={()=>this.setState({editing:structuredClone(c),error:''})}/><IconButton icon="trash" label={t('Delete','حذف')} variant="danger" disabled={this.state.busy} onClick={()=>this.setState({deleting:c,error:''})}/></div></article>;})}</div>:<div className="empty-state"><span className="empty-mark"><Icon name="users" size={28}/></span><h2>{t('No customers yet','لا يوجد عملاء بعد')}</h2><p>{t('Add your first customer.','أضف أول عميل.')}</p><Button icon="plus" variant="primary" onClick={()=>this.setState({editing:blankCustomer(),error:''})}>{t('Add Customer','إضافة عميل')}</Button></div>}
    <Modal open={Boolean(this.state.editing)} title={this.state.editing&&this.props.customers.some(c=>c.id===this.state.editing?.id)?t('Edit Customer','تعديل العميل'):t('Add Customer','إضافة عميل')} size="lg" onClose={()=>this.setState({editing:null,error:''})} footer={<div className="modal-footer-actions"><Button disabled={this.state.busy} onClick={()=>this.setState({editing:null,error:''})}>{t('Cancel','إلغاء')}</Button><Button variant="primary" disabled={this.state.busy} onClick={this.save}>{this.state.busy?t('Saving…','جارٍ الحفظ…'):t('Save Customer','حفظ العميل')}</Button></div>}>{this.state.editing?<CustomerForm customer={this.state.editing} onChange={(editing)=>this.setState({editing})}/>:null}{this.state.error?<div className="inline-error">{this.state.error}</div>:null}</Modal>
    <ConfirmDialog open={Boolean(this.state.deleting)} title={t(`Delete ${this.state.deleting?.companyNameEn||'customer'}?`,`حذف ${this.state.deleting?.companyNameAr||this.state.deleting?.companyNameEn||'العميل'}؟`)} message={t('This removes the customer from your address book. Existing documents keep their saved customer snapshot.','سيتم حذف العميل من دليل العملاء، بينما تحتفظ المستندات الحالية بنسخة بيانات العميل المحفوظة فيها.')} onCancel={()=>{if(!this.state.busy)this.setState({deleting:null,error:''});}} onConfirm={()=>void this.remove()}/></section>;}
}
