import type { Customer } from '../types.js';
import { makeId } from '../lib/id.js';
import { Button, ConfirmDialog, Field, Icon, IconButton, Input, Modal, Textarea } from './UI.js';

export function blankCustomer(): Customer { const now=new Date().toISOString(); return { id:makeId('customer'),createdAt:now,updatedAt:now,companyNameEn:'',companyNameAr:'',contactPerson:'',addressEn:'',addressAr:'',city:'',country:'',phone:'',email:'',vatTaxNumber:'',commercialRegistration:'',notes:''}; }

interface FormProps { customer: Customer; onChange: (c:Customer)=>void; }
export function CustomerForm({customer,onChange}:FormProps): any {
  const set=(key:keyof Customer,value:string)=>onChange({...customer,[key]:value,updatedAt:new Date().toISOString()});
  return <div className="form-grid two"><Field label="Company Name English"><Input autoFocus value={customer.companyNameEn} onChange={(e:any)=>set('companyNameEn',e.target.value)}/></Field><Field label="Company Name Arabic"><Input dir="rtl" value={customer.companyNameAr} onChange={(e:any)=>set('companyNameAr',e.target.value)}/></Field><Field label="Contact Person"><Input value={customer.contactPerson} onChange={(e:any)=>set('contactPerson',e.target.value)}/></Field><Field label="Email"><Input type="email" value={customer.email} onChange={(e:any)=>set('email',e.target.value)}/></Field><Field label="Address English"><Input value={customer.addressEn} onChange={(e:any)=>set('addressEn',e.target.value)}/></Field><Field label="Address Arabic"><Input dir="rtl" value={customer.addressAr} onChange={(e:any)=>set('addressAr',e.target.value)}/></Field><Field label="City"><Input value={customer.city} onChange={(e:any)=>set('city',e.target.value)}/></Field><Field label="Country"><Input value={customer.country} onChange={(e:any)=>set('country',e.target.value)}/></Field><Field label="Phone"><Input value={customer.phone} onChange={(e:any)=>set('phone',e.target.value)}/></Field><Field label="VAT / Tax Number"><Input value={customer.vatTaxNumber} onChange={(e:any)=>set('vatTaxNumber',e.target.value)}/></Field><Field label="Commercial Registration"><Input value={customer.commercialRegistration} onChange={(e:any)=>set('commercialRegistration',e.target.value)}/></Field><Field label="Notes" className="span-2"><Textarea rows="3" value={customer.notes} onChange={(e:any)=>set('notes',e.target.value)}/></Field></div>;
}

interface Props { customers: Customer[]; onSave: (customer:Customer)=>Promise<void>; onDelete:(customer:Customer)=>Promise<void>; }
interface State { query:string; editing:Customer|null; deleting:Customer|null; error:string; busy:boolean; }
export class CustomersPage extends React.Component<Props,State> {
  state:State={query:'',editing:null,deleting:null,error:'',busy:false};
  private filtered():Customer[]{const q=this.state.query.trim().toLowerCase();return this.props.customers.filter(c=>!q||c.companyNameEn.toLowerCase().includes(q)||c.companyNameAr.includes(this.state.query.trim())||c.contactPerson.toLowerCase().includes(q)).sort((a,b)=>a.companyNameEn.localeCompare(b.companyNameEn));}
  private save=async()=>{const c=this.state.editing;if(!c)return;if(!c.companyNameEn.trim()&&!c.companyNameAr.trim()){this.setState({error:'Company name is required.'});return;}this.setState({busy:true,error:''});try{await this.props.onSave(c);this.setState({editing:null,busy:false});}catch(e){this.setState({error:e instanceof Error?e.message:'Unable to save customer.',busy:false});}};
  render():any{const customers=this.filtered();return <section className="page customers-page"><div className="page-heading"><div><p className="eyebrow">Address book</p><h1>Customers</h1></div><Button icon="plus" variant="primary" onClick={()=>this.setState({editing:blankCustomer()})}>Add Customer</Button></div><div className="list-toolbar customers-toolbar"><div className="search-box"><Icon name="search"/><Input placeholder="Search customers" value={this.state.query} onChange={(e:any)=>this.setState({query:e.target.value})}/></div></div>{customers.length?<div className="customer-list">{customers.map(c=><article className="customer-card" key={c.id}><div className="customer-avatar">{(c.companyNameEn||c.companyNameAr||'C').trim().charAt(0).toUpperCase()}</div><div className="customer-info"><strong>{c.companyNameEn||c.companyNameAr}</strong>{c.companyNameAr&&c.companyNameEn?<span dir="rtl">{c.companyNameAr}</span>:null}<small>{[c.city,c.country].filter(Boolean).join(', ')||'No location'}</small><small>{[c.email,c.phone].filter(Boolean).join(' · ')}</small></div><div className="customer-actions"><IconButton icon="edit" label="Edit" onClick={()=>this.setState({editing:structuredClone(c)})}/><IconButton icon="trash" label="Delete" variant="danger" onClick={()=>this.setState({deleting:c})}/></div></article>)}</div>:<div className="empty-state"><span className="empty-mark"><Icon name="users" size={28}/></span><h2>No customers yet</h2><p>Add your first customer.</p><Button icon="plus" variant="primary" onClick={()=>this.setState({editing:blankCustomer()})}>Add Customer</Button></div>}
    <Modal open={Boolean(this.state.editing)} title={this.state.editing&&this.props.customers.some(c=>c.id===this.state.editing?.id)?'Edit Customer':'Add Customer'} size="lg" onClose={()=>this.setState({editing:null,error:''})} footer={<div className="modal-footer-actions"><Button onClick={()=>this.setState({editing:null,error:''})}>Cancel</Button><Button variant="primary" disabled={this.state.busy} onClick={this.save}>{this.state.busy?'Saving…':'Save Customer'}</Button></div>}>{this.state.editing?<CustomerForm customer={this.state.editing} onChange={(editing)=>this.setState({editing})}/>:null}{this.state.error?<div className="inline-error">{this.state.error}</div>:null}</Modal>
    <ConfirmDialog open={Boolean(this.state.deleting)} title={`Delete ${this.state.deleting?.companyNameEn||'customer'}?`} message="This removes the customer from your address book. Existing documents keep their saved customer snapshot." onCancel={()=>this.setState({deleting:null})} onConfirm={async()=>{const c=this.state.deleting;if(c){await this.props.onDelete(c);this.setState({deleting:null});}}}/></section>;}
}
