import type { DocumentEventRecord, DocumentRevisionRecord, LourexDocument, PaymentRecord } from '../types.js';
import { displayDate } from '../lib/id.js';
import { getUiLanguage, isArabic, t } from '../lib/i18n.js';
import { formatMoney } from '../lib/money.js';
import { documentRevision, invoiceCreditCapacity, isCreditNote, lifecycleEventLabel } from '../lib/document-lifecycle.js';
import { Button, Modal, Textarea } from './UI.js';

interface Props{document:LourexDocument;documents:LourexDocument[];payments:PaymentRecord[];events:DocumentEventRecord[];revisions:DocumentRevisionRecord[];onDiscardRevision:(doc:LourexDocument)=>Promise<void>;onVoid:(doc:LourexDocument,reason:string)=>Promise<void>;onCreateCreditNote:(doc:LourexDocument)=>Promise<void>;}
interface State{voidOpen:boolean;reason:string;working:boolean;error:string;}
export class DocumentLifecyclePanel extends React.Component<Props,State>{
  state:State={voidOpen:false,reason:'',working:false,error:''};
  private voidNow=async()=>{if(!this.state.reason.trim()){this.setState({error:t('Enter a reason first.','أدخل سبب الإلغاء أولًا.')});return;}this.setState({working:true,error:''});try{await this.props.onVoid(this.props.document,this.state.reason);this.setState({voidOpen:false,reason:'',working:false});}catch(e){this.setState({working:false,error:e instanceof Error?e.message:t('Unable to void document.','تعذر إلغاء المستند.')});}};
  private credit=async()=>{this.setState({working:true,error:''});try{await this.props.onCreateCreditNote(this.props.document);this.setState({working:false});}catch(e){this.setState({working:false,error:e instanceof Error?e.message:t('Unable to create credit note.','تعذر إنشاء إشعار دائن.')});}};
  private discard=async()=>{if(!window.confirm(t('Discard this revision and restore the previous Final version?','إلغاء هذه المراجعة واستعادة النسخة النهائية السابقة؟')))return;this.setState({working:true,error:''});try{await this.props.onDiscardRevision(this.props.document);this.setState({working:false});}catch(e){this.setState({working:false,error:e instanceof Error?e.message:t('Unable to discard revision.','تعذر إلغاء المراجعة.')});}};
  render():any{const doc=this.props.document;const revision=documentRevision(doc);const voided=doc.lifecycleStatus==='voided';const revisionDraft=doc.status==='draft'&&revision>1;const finalActive=doc.status==='final'&&!voided;const standardInvoice=doc.kind==='invoice'&&!isCreditNote(doc);const canCredit=finalActive&&standardInvoice;const capacity=standardInvoice?invoiceCreditCapacity(doc,this.props.documents,this.props.payments):null;const events=[...this.props.events].filter(event=>event.documentId===doc.id).sort((a,b)=>b.at.localeCompare(a.at)).slice(0,16);const revisions=this.props.revisions.filter(item=>item.documentId===doc.id).length;const arabic=isArabic();const status=voided?(doc.kind==='proforma'?t('Cancelled','ملغى'):t('Voided','ملغى')):revisionDraft?t('Revision '+revision+' Draft','مسودة مراجعة '+revision):doc.status==='final'?t('Final','نهائي'):t('Draft','مسودة');return <section className="document-lifecycle-panel">
    <div className="lifecycle-heading"><div><p className="eyebrow">{t('Document control','ضبط المستند')}</p><h2>{t('History & Lifecycle','السجل ودورة الحياة')}</h2><p>{t('Issued versions are preserved. Revisions, voids, credits and payments stay traceable.','النسخ الصادرة محفوظة، وتبقى المراجعات والإلغاءات والإشعارات الدائنة والمدفوعات قابلة للتتبع.')}</p></div><span className={`lifecycle-status ${voided?'is-voided':revisionDraft?'is-revision':doc.status==='final'?'is-final':'is-draft'}`}>{status}</span></div>
    <div className="lifecycle-facts"><div><span>{t('Revision','المراجعة')}</span><strong>R{revision}</strong></div><div><span>{t('Saved finals','النسخ النهائية المحفوظة')}</span><strong>{revisions}</strong></div>{isCreditNote(doc)?<div><span>{t('Source invoice','الفاتورة الأصلية')}</span><strong>{doc.creditForNumber||'—'}</strong></div>:null}{capacity&&finalActive?<div><span>{t('Available to credit','متاح كإشعار دائن')}</span><strong>{formatMoney(capacity.available,doc.currency)}</strong></div>:null}</div>
    {voided?<div className="void-reason"><strong>{t('Reason','السبب')}</strong><span>{doc.voidReason||'—'}</span></div>:null}
    <div className="lifecycle-actions">{revisionDraft?<Button onClick={()=>void this.discard()} disabled={this.state.working}>{t('Discard Revision','إلغاء المراجعة')}</Button>:null}{canCredit&&capacity&&capacity.available!=='0.00'?<Button icon="invoice" onClick={()=>void this.credit()} disabled={this.state.working}>{t('Create Credit Note','إنشاء إشعار دائن')}</Button>:null}{finalActive?<Button variant="danger" onClick={()=>this.setState({voidOpen:true,error:''})} disabled={this.state.working}>{doc.kind==='proforma'?t('Cancel Quote','إلغاء عرض السعر'):t('Void Document','إلغاء المستند')}</Button>:null}</div>
    {this.state.error?<p className="lifecycle-error" role="alert">{this.state.error}</p>:null}
    <div className="document-timeline"><h3>{t('Timeline','السجل الزمني')}</h3>{events.length?events.map(event=><article key={event.id}><span className="timeline-dot" aria-hidden="true"/><div><strong>{lifecycleEventLabel(event.type,arabic)}</strong><small>{displayDate(event.at.slice(0,10),getUiLanguage())}{event.relatedDocumentNumber?' · '+event.relatedDocumentNumber:''}{event.amount?' · '+formatMoney(event.amount,event.currency||doc.currency):''}</small>{event.note?<p>{event.note}</p>:null}</div></article>):<p className="timeline-empty">{t('History begins when this document is saved or issued.','يبدأ السجل عند حفظ المستند أو إصداره.')}</p>}</div>
    <Modal open={this.state.voidOpen} title={doc.kind==='proforma'?t('Cancel final quote','إلغاء عرض السعر النهائي'):t('Void final document','إلغاء المستند النهائي')} size="sm" onClose={()=>this.setState({voidOpen:false,error:''})} footer={<div className="modal-footer-actions"><Button onClick={()=>this.setState({voidOpen:false,error:''})}>{t('Back','رجوع')}</Button><Button variant="danger" disabled={this.state.working||!this.state.reason.trim()} onClick={()=>void this.voidNow()}>{t('Confirm Void','تأكيد الإلغاء')}</Button></div>}><p className="modal-message">{t('This preserves the document and its number permanently instead of deleting history.','سيبقى المستند ورقمه محفوظين بشكل دائم بدل حذف التاريخ.')}</p><label className="lifecycle-reason-field"><span>{t('Reason','السبب')}</span><Textarea rows={3} value={this.state.reason} onChange={(e:any)=>this.setState({reason:e.target.value,error:''})} placeholder={t('Why is this document being voided?','ما سبب إلغاء هذا المستند؟')}/></label>{this.state.error?<p className="lifecycle-error">{this.state.error}</p>:null}</Modal>
  </section>;}
}
