import type { CompanySettings, Customer, DocumentItem, LourexDocument, TemplateId } from '../types.js';
import { calculateTotals, formatMoney, lineTotal } from '../lib/money.js';
import { customerSnapshotFrom } from '../lib/defaults.js';
import { emptyItem, refreshCompanySnapshot, validateDocument } from '../lib/documents.js';
import { blankCustomer, CustomerForm } from './CustomersPage.js';
import { TemplateRenderer } from '../templates/TemplateRenderer.js';
import { TemplateThumbnails } from '../templates/TemplateThumbnails.js';
import { Button, ConfirmDialog, Field, Icon, IconButton, Input, Modal, Select, Textarea, Toggle } from './UI.js';

const currencyPresets=['USD','EUR','SAR','TRY','AED','GBP'];
const unitPresets=['PCS','Carton','Box','Pallet','KG','Unit','Set'];
const incoterms=['EXW','FCA','FOB','CFR','CIF','CPT','CIP','DAP','DPU','DDP'];

interface Props { document:LourexDocument; customers:Customer[]; company:CompanySettings; onClose:()=>void; onSave:(doc:LourexDocument,auto?:boolean)=>Promise<void>; onSaveCustomer:(customer:Customer)=>Promise<void>; onConvert:(doc:LourexDocument)=>Promise<void>; onPrint:(doc:LourexDocument,mode:'print'|'pdf'|'share')=>void; }
interface State { doc:LourexDocument; errors:Record<string,string>; saving:boolean; saveState:'saved'|'saving'|'unsaved'; customerQuery:string; customerOpen:boolean; addCustomer:Customer|null; addCustomerError:string; mobilePreview:boolean; confirmClose:boolean; }

export class EditorPage extends React.Component<Props,State>{
  private autosaveTimer:number|undefined;
  constructor(props:Props){super(props);this.state={doc:structuredClone(props.document),errors:{},saving:false,saveState:'saved',customerQuery:props.document.customerSnapshot?.companyNameEn||'',customerOpen:false,addCustomer:null,addCustomerError:'',mobilePreview:false,confirmClose:false};}
  componentWillUnmount():void{if(this.autosaveTimer)clearTimeout(this.autosaveTimer);}
  private mutate=(fn:(d:LourexDocument)=>LourexDocument)=>{const doc={...fn(this.state.doc),updatedAt:new Date().toISOString()};this.setState({doc,saveState:'unsaved'},()=>this.schedule());};
  private schedule=()=>{if(this.autosaveTimer)clearTimeout(this.autosaveTimer);if(Object.keys(validateDocument(this.state.doc)).length)return;this.autosaveTimer=window.setTimeout(()=>void this.save(true),2500);};
  private save=async(auto=false)=>{if(this.state.saving)return;const errors=validateDocument(this.state.doc);if(Object.keys(errors).length){if(!auto)this.setState({errors});return;}this.setState({saving:true,saveState:'saving',errors:{}});try{await this.props.onSave(this.state.doc,auto);this.setState({saving:false,saveState:'saved'});}catch(e){this.setState({saving:false,saveState:'unsaved',errors:{global:e instanceof Error?e.message:'Save failed.'}});}};
  private field=(key:keyof LourexDocument,value:any)=>this.mutate(d=>({...d,[key]:value}));
  private term=(key:keyof LourexDocument['terms'],value:string)=>this.mutate(d=>({...d,terms:{...d.terms,[key]:value}}));
  private adj=(key:keyof LourexDocument['adjustments'],value:any)=>this.mutate(d=>({...d,adjustments:{...d.adjustments,[key]:value}}));
  private appearance=(key:keyof LourexDocument['appearance'],value:any)=>this.mutate(d=>({...d,appearance:{...d.appearance,[key]:value}}));
  private item=(id:string,key:keyof DocumentItem,value:string)=>this.mutate(d=>({...d,items:d.items.map(i=>i.id===id?{...i,[key]:value}:i)}));
  private selectCustomer=(c:Customer)=>{this.mutate(d=>({...d,customerSnapshot:customerSnapshotFrom(c)}));this.setState({customerQuery:c.companyNameEn||c.companyNameAr,customerOpen:false});};
  private addCustomer=async()=>{const c=this.state.addCustomer;if(!c)return;if(!c.companyNameEn.trim()&&!c.companyNameAr.trim()){this.setState({addCustomerError:'Company name is required.'});return;}try{await this.props.onSaveCustomer(c);this.selectCustomer(c);this.setState({addCustomer:null,addCustomerError:''});}catch(e){this.setState({addCustomerError:e instanceof Error?e.message:'Unable to save customer.'});}};
  render():any{const d=this.state.doc,errors=this.state.errors,totals=calculateTotals(d.items,d.adjustments);const customers=this.props.customers.filter(c=>!this.state.customerQuery||c.companyNameEn.toLowerCase().includes(this.state.customerQuery.toLowerCase())||c.companyNameAr.includes(this.state.customerQuery)).slice(0,8);return <div className={`editor-screen ${this.state.mobilePreview?'mobile-preview-open':''}`}>
    <header className="editor-topbar"><div className="editor-top-left"><IconButton icon="arrowLeft" label="Back" onClick={()=>this.state.saveState==='unsaved'?this.setState({confirmClose:true}):this.props.onClose()}/><div><strong>{d.number}</strong><span>{d.kind==='proforma'?'Proforma Invoice':'Invoice'}</span></div></div><div className={`save-indicator state-${this.state.saveState}`}>{this.state.saveState==='saving'?'Saving…':this.state.saveState==='saved'?'Saved':'Unsaved'}</div><div className="editor-actions"><Button icon="eye" className="mobile-preview-button" onClick={()=>this.setState({mobilePreview:true})}>Preview</Button><Button icon="printer" variant="ghost" onClick={()=>this.props.onPrint(d,'print')}>Print</Button><Button icon="download" onClick={()=>this.props.onPrint(d,'pdf')}>PDF</Button><Button icon="share" onClick={()=>this.props.onPrint(d,'share')}>Share</Button><Button icon="save" variant="primary" disabled={this.state.saving} onClick={()=>void this.save(false)}>Save</Button></div></header>
    {errors.global?<div className="editor-global-error">{errors.global}</div>:null}
    <div className="editor-layout"><aside className="editor-pane"><div className="editor-scroll">
      <section className="editor-section"><div className="section-heading"><span>01</span><h2>Document</h2></div><div className="form-grid two compact-grid"><Field label="Number" error={errors.number}><Input value={d.number} onChange={(e:any)=>this.field('number',e.target.value)}/></Field><Field label="Issue Date"><Input type="date" value={d.issueDate} onChange={(e:any)=>this.field('issueDate',e.target.value)}/></Field><Field label={d.kind==='proforma'?'Valid Until':'Due Date'}><Input type="date" value={d.dueDate} onChange={(e:any)=>this.field('dueDate',e.target.value)}/></Field><Field label="Currency"><Input list="currencies" value={d.currency} onChange={(e:any)=>this.field('currency',e.target.value.toUpperCase())}/><datalist id="currencies">{currencyPresets.map(x=><option key={x} value={x}/>)}</datalist></Field><Field label="Language"><Select value={d.language} onChange={(e:any)=>this.field('language',e.target.value)}><option value="en">English</option><option value="ar">العربية</option><option value="bilingual">Arabic + English</option></Select></Field></div></section>
      <section className="editor-section"><div className="section-heading"><span>02</span><h2>Customer</h2></div><div className="customer-select-wrap"><Field label="Saved Customer" error={errors.customer}><div className="search-select"><Icon name="search"/><Input value={this.state.customerQuery} placeholder="Search customer" onFocus={()=>this.setState({customerOpen:true})} onChange={(e:any)=>this.setState({customerQuery:e.target.value,customerOpen:true})}/></div></Field>{this.state.customerOpen?<div className="customer-dropdown">{customers.map(c=><button key={c.id} onClick={()=>this.selectCustomer(c)}><strong>{c.companyNameEn||c.companyNameAr}</strong><span>{[c.city,c.country].filter(Boolean).join(', ')}</span></button>)}<button className="new-customer-option" onClick={()=>this.setState({addCustomer:blankCustomer(),customerOpen:false})}><Icon name="plus"/>New Customer</button></div>:null}</div>{d.customerSnapshot?<div className="selected-customer"><div><strong>{d.customerSnapshot.companyNameEn||d.customerSnapshot.companyNameAr}</strong><span>{[d.customerSnapshot.city,d.customerSnapshot.country].filter(Boolean).join(', ')}</span></div></div>:null}</section>
      <section className="editor-section"><div className="section-heading with-action"><div><span>03</span><h2>Items</h2></div><Button icon="plus" onClick={()=>this.mutate(doc=>({...doc,items:[...doc.items,emptyItem()]}))}>Add Item</Button></div><div className="item-cards">{d.items.map((i,index)=><article className="item-card" key={i.id}><header><strong>Item {index+1}</strong><IconButton icon="trash" label="Delete" disabled={d.items.length===1} onClick={()=>this.mutate(doc=>({...doc,items:doc.items.filter(x=>x.id!==i.id)}))}/></header><div className="form-grid two compact-grid">{d.language!=='ar'?<Field label="Description English" className="span-2" error={errors[`item-${index}-description`]}><Textarea rows="2" value={i.descriptionEn} onChange={(e:any)=>this.item(i.id,'descriptionEn',e.target.value)}/></Field>:null}{d.language!=='en'?<Field label="الوصف العربي" className="span-2"><Textarea dir="rtl" rows="2" value={i.descriptionAr} onChange={(e:any)=>this.item(i.id,'descriptionAr',e.target.value)}/></Field>:null}<Field label="HS Code"><Input value={i.hsCode} onChange={(e:any)=>this.item(i.id,'hsCode',e.target.value)}/></Field><Field label="Origin"><Input value={i.origin} onChange={(e:any)=>this.item(i.id,'origin',e.target.value)}/></Field><Field label="Packing"><Input value={i.packing} onChange={(e:any)=>this.item(i.id,'packing',e.target.value)}/></Field><Field label="Quantity" error={errors[`item-${index}-quantity`]}><Input value={i.quantity} onChange={(e:any)=>this.item(i.id,'quantity',e.target.value)}/></Field><Field label="Unit"><Input list="units" value={i.unit} onChange={(e:any)=>this.item(i.id,'unit',e.target.value)}/><datalist id="units">{unitPresets.map(x=><option key={x} value={x}/>)}</datalist></Field><Field label={`Unit Price (${d.currency})`} error={errors[`item-${index}-price`]}><Input value={i.unitPrice} onChange={(e:any)=>this.item(i.id,'unitPrice',e.target.value)}/></Field></div><footer><span>Line Total</span><strong>{formatMoney(lineTotal(i.quantity,i.unitPrice),d.currency)}</strong></footer></article>)}</div></section>
      <section className="editor-section"><div className="section-heading"><span>04</span><h2>Totals</h2></div><div className="adjustments-list"><div className="adjustment-row"><Toggle checked={d.adjustments.discountEnabled} onChange={v=>this.adj('discountEnabled',v)} label="Discount"/>{d.adjustments.discountEnabled?<Input value={d.adjustments.discountValue} onChange={(e:any)=>this.adj('discountValue',e.target.value)}/>:null}</div><div className="adjustment-row"><Toggle checked={d.adjustments.shippingEnabled} onChange={v=>this.adj('shippingEnabled',v)} label="Shipping"/>{d.adjustments.shippingEnabled?<Input value={d.adjustments.shipping} onChange={(e:any)=>this.adj('shipping',e.target.value)}/>:null}</div><div className="adjustment-row"><Toggle checked={d.adjustments.taxEnabled} onChange={v=>this.adj('taxEnabled',v)} label="Tax / VAT"/>{d.adjustments.taxEnabled?<Input value={d.adjustments.taxPercent} onChange={(e:any)=>this.adj('taxPercent',e.target.value)}/>:null}</div></div><div className="editor-totals"><div><span>Subtotal</span><strong>{formatMoney(totals.subtotal,d.currency)}</strong></div><div className="grand"><span>Grand Total</span><strong>{formatMoney(totals.grandTotal,d.currency)}</strong></div></div></section>
      <section className="editor-section"><div className="section-heading"><span>05</span><h2>Commercial Terms</h2></div><div className="form-grid two compact-grid"><Field label="Incoterm"><Input list="incoterms" value={d.terms.incoterm} onChange={(e:any)=>this.term('incoterm',e.target.value)}/><datalist id="incoterms">{incoterms.map(x=><option key={x} value={x}/>)}</datalist></Field><Field label="Payment Terms"><Input value={d.terms.paymentTerms} onChange={(e:any)=>this.term('paymentTerms',e.target.value)}/></Field><Field label="Delivery Time"><Input value={d.terms.deliveryTime} onChange={(e:any)=>this.term('deliveryTime',e.target.value)}/></Field><Field label="Final Destination"><Input value={d.terms.finalDestination} onChange={(e:any)=>this.term('finalDestination',e.target.value)}/></Field><Field label="Remarks" className="span-2"><Textarea value={d.terms.remarks} onChange={(e:any)=>this.term('remarks',e.target.value)}/></Field><Field label="Notes" className="span-2"><Textarea value={d.notes} onChange={(e:any)=>this.field('notes',e.target.value)}/></Field></div></section>
      <section className="editor-section"><div className="section-heading"><span>06</span><h2>Design</h2></div><TemplateThumbnails document={d} onSelect={(id:TemplateId)=>this.appearance('templateId',id)}/><div className="appearance-controls"><Field label="Accent"><Input type="color" value={d.appearance.accentColor} onChange={(e:any)=>this.appearance('accentColor',e.target.value)}/></Field><Toggle checked={d.appearance.showBank} onChange={v=>this.appearance('showBank',v)} label="Bank Details"/><Toggle checked={d.appearance.showSignature} onChange={v=>this.appearance('showSignature',v)} label="Signature"/><Toggle checked={d.appearance.showStamp} onChange={v=>this.appearance('showStamp',v)} label="Stamp"/></div><Button icon="refresh" onClick={()=>this.mutate(doc=>refreshCompanySnapshot(doc,this.props.company))}>Refresh Company Details</Button>{d.kind==='proforma'?<Button icon="invoice" variant="primary" onClick={()=>void this.props.onConvert(d)}>Convert to Invoice</Button>:null}</section>
    </div></aside><section className="preview-pane"><div className="preview-toolbar"><span>Live A4 Preview</span></div><div className="preview-stage"><TemplateRenderer document={d} scale={0.82}/></div></section></div>
    <div className="mobile-preview-overlay"><header><strong>Preview</strong><div><Button icon="download" onClick={()=>this.props.onPrint(d,'pdf')}>PDF</Button><IconButton icon="x" label="Close" onClick={()=>this.setState({mobilePreview:false})}/></div></header><div className="mobile-preview-stage"><TemplateRenderer document={d} scale={0.48}/></div></div>
    <ConfirmDialog open={this.state.confirmClose} title="Discard unsaved changes?" message="Your latest changes have not been saved." confirmLabel="Discard" destructive onCancel={()=>this.setState({confirmClose:false})} onConfirm={()=>this.props.onClose()}/>
    <Modal open={Boolean(this.state.addCustomer)} title="New Customer" size="lg" onClose={()=>this.setState({addCustomer:null,addCustomerError:''})} footer={<div className="modal-footer-actions"><Button onClick={()=>this.setState({addCustomer:null})}>Cancel</Button><Button variant="primary" onClick={()=>void this.addCustomer()}>Save & Select</Button></div>}>{this.state.addCustomer?<CustomerForm customer={this.state.addCustomer} onChange={addCustomer=>this.setState({addCustomer})}/>:null}{this.state.addCustomerError?<div className="inline-error">{this.state.addCustomerError}</div>:null}</Modal>
  </div>;}
}
