import type { FxRateRecord, LourexDocument, PaymentRecord, PurchaseRecord, SupplierPaymentRecord } from '../types.js';
import { convertWithFxRate, createFxRate, fxRateForDate } from '../lib/fx-rates.js';
import { formatMoney } from '../lib/money.js';
import { displayDate, todayIso } from '../lib/id.js';
import { getUiLanguage, t } from '../lib/i18n.js';
import { mutateVaultSafely } from '../storage/vault-mutation-bridge.js';
import { Button, Input, Select, Textarea } from './UI.js';

interface Props {rates:FxRateRecord[];documents:LourexDocument[];payments:PaymentRecord[];purchases:PurchaseRecord[];supplierPayments:SupplierPaymentRecord[];defaultCurrency:string;}
function currencySet(props:Props):string[]{return Array.from(new Set([props.defaultCurrency,...props.rates.flatMap(r=>[r.fromCurrency,r.toCurrency]),...props.documents.map(d=>d.currency),...props.payments.map(p=>p.currency),...props.purchases.map(p=>p.currency),...props.supplierPayments.map(p=>p.currency)].filter(Boolean).map(v=>v.trim().toUpperCase()))).sort();}
export function FxRatesPage(props:Props):any{
  const currencies=currencySet(props),fallbackFrom=props.defaultCurrency||currencies[0]||'USD',fallbackTo=currencies.find(c=>c!==fallbackFrom)||'EUR';
  const [date,setDate]=React.useState(todayIso()),[from,setFrom]=React.useState(fallbackFrom),[to,setTo]=React.useState(fallbackTo),[rate,setRate]=React.useState(''),[source,setSource]=React.useState('Manual'),[notes,setNotes]=React.useState(''),[amount,setAmount]=React.useState('1000'),[busy,setBusy]=React.useState(false),[error,setError]=React.useState('');
  const selected=fxRateForDate(props.rates,from,to,date);const converted=selected&&amount.trim()?convertWithFxRate(amount,selected):'';
  const save=async()=>{if(busy)return;setBusy(true);setError('');try{const item={...createFxRate(from,to),date,fromCurrency:from.trim().toUpperCase(),toCurrency:to.trim().toUpperCase(),rate:rate.trim(),sourceLabel:source.trim(),notes:notes.trim()};await mutateVaultSafely(vault=>({...vault,fxRates:[...vault.fxRates,item]}));setRate('');setNotes('');}catch(e){setError(e instanceof Error?e.message:t('Unable to save exchange rate.','تعذر حفظ سعر الصرف.'));}finally{setBusy(false);}};
  const remove=async(id:string)=>{if(busy)return;setBusy(true);try{await mutateVaultSafely(vault=>({...vault,fxRates:vault.fxRates.filter(item=>item.id!==id)}));}catch(e){setError(e instanceof Error?e.message:t('Unable to delete exchange rate.','تعذر حذف سعر الصرف.'));}finally{setBusy(false);}};
  const rows=[...props.rates].sort((a,b)=>b.date.localeCompare(a.date)||b.updatedAt.localeCompare(a.updatedAt));
  return <section className="ta-finance-page lx-fx-rates"><header className="ta-page-header"><div><span className="ta-page-kicker">{t('Exchange rates','أسعار الصرف')}</span><h2>{t('Dated FX Rates','أسعار صرف مؤرخة')}</h2><p>{t('Store explicit, source-labelled rates. Original document amounts and currencies never change.','احفظ أسعارًا صريحة مع مصدرها. مبالغ وعملات المستندات الأصلية لا تتغير أبدًا.')}</p></div></header>
    <section className="ta-data-alert"><span>FX</span><div><strong>{t('No hidden conversion','لا تحويل مخفي')}</strong><p>{t('Reports remain currency-separated by default. Any consolidated conversion must explicitly choose a dated rate.','تبقى التقارير مفصولة حسب العملة افتراضيًا. أي توحيد للعملات يجب أن يختار سعرًا مؤرخًا بشكل صريح.')}</p></div></section>
    <section className="ta-panel"><header className="ta-panel-header"><div><span>{t('Rate management','إدارة الأسعار')}</span><h3>{t('Add exchange rate','إضافة سعر صرف')}</h3></div></header><div className="lx-form-grid"><label><span>{t('Date','التاريخ')}</span><Input type="date" value={date} onChange={(e:any)=>setDate(e.target.value)}/></label><label><span>{t('From','من')}</span><Input value={from} maxLength={8} onChange={(e:any)=>setFrom(String(e.target.value).toUpperCase())}/></label><label><span>{t('To','إلى')}</span><Input value={to} maxLength={8} onChange={(e:any)=>setTo(String(e.target.value).toUpperCase())}/></label><label><span>{t('Rate','السعر')}</span><Input inputMode="decimal" value={rate} placeholder="1.00000000" onChange={(e:any)=>setRate(e.target.value)}/></label><label><span>{t('Source label','مصدر السعر')}</span><Input value={source} placeholder={t('Manual / Bank / ECB…','يدوي / بنك / ECB…')} onChange={(e:any)=>setSource(e.target.value)}/></label><label className="lx-form-wide"><span>{t('Notes','ملاحظات')}</span><Textarea rows={2} value={notes} onChange={(e:any)=>setNotes(e.target.value)}/></label></div>{error?<p className="lifecycle-error" role="alert">{error}</p>:null}<Button variant="primary" icon="plus" disabled={busy} onClick={()=>void save()}>{t('Save rate','حفظ السعر')}</Button></section>
    <section className="ta-panel"><header className="ta-panel-header"><div><span>{t('Explicit converter','محول صريح')}</span><h3>{t('Convert using saved rate','تحويل باستخدام سعر محفوظ')}</h3></div></header><div className="lx-form-grid"><label><span>{t('Amount','المبلغ')}</span><Input inputMode="decimal" value={amount} onChange={(e:any)=>setAmount(e.target.value)}/></label><label><span>{t('From','من')}</span><Select value={from} onChange={(e:any)=>setFrom(e.target.value)}>{currencies.map(c=><option key={c}>{c}</option>)}</Select></label><label><span>{t('To','إلى')}</span><Select value={to} onChange={(e:any)=>setTo(e.target.value)}>{currencies.filter(c=>c!==from).map(c=><option key={c}>{c}</option>)}</Select></label><label><span>{t('As of','كما في')}</span><Input type="date" value={date} onChange={(e:any)=>setDate(e.target.value)}/></label></div><div className="lx-fx-conversion-result"><span>{selected?`${selected.fromCurrency}/${selected.toCurrency} · ${selected.rate} · ${selected.sourceLabel}`:t('No saved rate available on or before this date.','لا يوجد سعر محفوظ متاح في هذا التاريخ أو قبله.')}</span><strong>{selected&&converted?`${formatMoney(amount||'0',from)} → ${formatMoney(converted,to)}`:'—'}</strong></div></section>
    <section className="ta-panel"><header className="ta-panel-header"><div><span>{t('Rate history','سجل الأسعار')}</span><h3>{t('Saved FX rates','أسعار الصرف المحفوظة')}</h3></div><div className="ta-panel-status">{rows.length}</div></header><div className="ta-table-wrap"><table className="ta-table"><thead><tr><th>{t('Date','التاريخ')}</th><th>{t('Pair','الزوج')}</th><th>{t('Rate','السعر')}</th><th>{t('Source','المصدر')}</th><th>{t('Notes','ملاحظات')}</th><th>{t('Actions','الإجراءات')}</th></tr></thead><tbody>{rows.map(item=><tr key={item.id}><td>{displayDate(item.date,getUiLanguage())}</td><td><strong>{item.fromCurrency}/{item.toCurrency}</strong></td><td><bdi>{item.rate}</bdi></td><td>{item.sourceLabel}</td><td>{item.notes||'—'}</td><td><Button variant="danger" disabled={busy} onClick={()=>void remove(item.id)}>{t('Delete','حذف')}</Button></td></tr>)}</tbody></table></div></section>
  </section>;
}
