import type { LourexDocument, PaymentMethod, PaymentRecord } from '../types.js';
import { formatMoney } from '../lib/money.js';
import { displayDate, makeId, todayIso } from '../lib/id.js';
import { getUiLanguage, isArabic, t } from '../lib/i18n.js';
import { invoicePaymentSummary, invoicePayments, paymentMethodLabel } from '../lib/payments.js';
import { Button, Input, Select, Textarea } from './UI.js';

interface Props{document:LourexDocument;payments:PaymentRecord[];onSave:(payment:PaymentRecord)=>Promise<void>;onDelete:(payment:PaymentRecord)=>Promise<void>;}
interface State{open:boolean;amount:string;date:string;method:PaymentMethod;reference:string;notes:string;saving:boolean;error:string;}
export class InvoicePaymentsPanel extends React.Component<Props,State>{
  state:State={open:false,amount:'',date:todayIso(),method:'bank-transfer',reference:'',notes:'',saving:false,error:''};
  private openForm=()=>{const summary=invoicePaymentSummary(this.props.document,this.props.payments);this.setState({open:true,amount:summary.remaining,date:todayIso(),method:'bank-transfer',reference:'',notes:'',error:''});};
  private closeForm=()=>this.setState({open:false,error:''});
  private save=async()=>{const doc=this.props.document;const now=new Date().toISOString();const payment:PaymentRecord={id:makeId('pay'),invoiceId:doc.id,invoiceNumber:doc.number,customerId:doc.customerSnapshot?.sourceCustomerId||'',customerNameEn:doc.customerSnapshot?.companyNameEn||'',customerNameAr:doc.customerSnapshot?.companyNameAr||'',currency:doc.currency,amount:this.state.amount,date:this.state.date,method:this.state.method,reference:this.state.reference,notes:this.state.notes,createdAt:now,updatedAt:now};this.setState({saving:true,error:''});try{await this.props.onSave(payment);this.setState({open:false,amount:'',reference:'',notes:'',saving:false});}catch(e){this.setState({saving:false,error:e instanceof Error?e.message:t('Unable to save payment.','تعذر حفظ الدفعة.')});}};
  private remove=async(payment:PaymentRecord)=>{if(!window.confirm(t('Delete this payment record? This changes the invoice balance.','حذف سجل الدفعة؟ سيؤثر ذلك على رصيد الفاتورة.')))return;try{await this.props.onDelete(payment);}catch(e){this.setState({error:e instanceof Error?e.message:t('Unable to delete payment.','تعذر حذف الدفعة.')});}};
  render():any{const doc=this.props.document;if(doc.kind!=='invoice'||doc.role==='credit-note'||doc.status!=='final'||doc.lifecycleStatus==='voided')return null;const summary=invoicePaymentSummary(doc,this.props.payments);const payments=invoicePayments(doc.id,this.props.payments).sort((a,b)=>b.date.localeCompare(a.date)||b.createdAt.localeCompare(a.createdAt));const arabic=isArabic();const statusLabel=summary.status==='paid'?t('Paid','مدفوعة'):summary.status==='partially-paid'?t('Partially Paid','مدفوعة جزئيًا'):summary.status==='overdue'?t('Overdue','متأخرة'):t('Unpaid','غير مدفوعة');return <section className="invoice-payments-panel" aria-label={t('Payments and collection','المدفوعات والتحصيل')}>
    <div className="payments-heading"><div><p className="eyebrow">{t('Collection','التحصيل')}</p><h2>{t('Payments','المدفوعات')}</h2><p>{t('Record full or partial receipts without changing the invoice itself.','سجّل الدفعات الكاملة أو الجزئية دون تغيير الفاتورة نفسها.')}</p></div><span className={`payment-status status-${summary.status}`}>{statusLabel}</span></div>
    <div className="payment-summary-grid"><div><span>{t('Invoice total','إجمالي الفاتورة')}</span><strong>{formatMoney(summary.total,doc.currency)}</strong></div><div><span>{t('Paid','المدفوع')}</span><strong>{formatMoney(summary.paid,doc.currency)}</strong></div><div className="payment-balance-card"><span>{t('Remaining','المتبقي')}</span><strong>{formatMoney(summary.remaining,doc.currency)}</strong></div></div>
    {summary.status!=='paid'&&!this.state.open?<Button icon="plus" variant="primary" onClick={this.openForm}>{t('Record Payment','تسجيل دفعة')}</Button>:null}
    {this.state.open?<div className="payment-entry-form"><div className="payment-form-grid"><label><span>{t('Amount','المبلغ')}</span><Input inputMode="decimal" value={this.state.amount} onChange={(e:any)=>this.setState({amount:e.target.value,error:''})}/></label><label><span>{t('Date','التاريخ')}</span><Input type="date" value={this.state.date} onChange={(e:any)=>this.setState({date:e.target.value,error:''})}/></label><label><span>{t('Method','الوسيلة')}</span><Select value={this.state.method} onChange={(e:any)=>this.setState({method:e.target.value as PaymentMethod})}>{(['cash','bank-transfer','card','cheque','other'] as PaymentMethod[]).map(method=><option key={method} value={method}>{paymentMethodLabel(method,arabic)}</option>)}</Select></label><label><span>{t('Reference','المرجع')}</span><Input value={this.state.reference} placeholder={t('Transfer / receipt reference','مرجع التحويل / الإيصال')} onChange={(e:any)=>this.setState({reference:e.target.value})}/></label></div><label className="payment-notes-field"><span>{t('Notes','ملاحظات')}</span><Textarea rows={2} value={this.state.notes} onChange={(e:any)=>this.setState({notes:e.target.value})}/></label>{this.state.error?<p className="payment-error" role="alert">{this.state.error}</p>:null}<div className="payment-form-actions"><Button onClick={this.closeForm} disabled={this.state.saving}>{t('Cancel','إلغاء')}</Button><Button variant="primary" icon="save" onClick={()=>void this.save()} disabled={this.state.saving}>{this.state.saving?t('Saving…','جارٍ الحفظ…'):t('Save Payment','حفظ الدفعة')}</Button></div></div>:null}
    {payments.length?<div className="payment-history"><h3>{t('Payment history','سجل المدفوعات')}</h3>{payments.map(payment=><article className="payment-row" key={payment.id}><div><strong>{formatMoney(payment.amount,payment.currency)}</strong><span>{displayDate(payment.date,getUiLanguage())} · {paymentMethodLabel(payment.method,arabic)}</span></div><div className="payment-row-details">{payment.reference?<span>{t('Ref.','مرجع')}: {payment.reference}</span>:null}{payment.notes?<small>{payment.notes}</small>:null}</div><Button variant="ghost" onClick={()=>void this.remove(payment)}>{t('Delete','حذف')}</Button></article>)}</div>:<p className="payment-empty">{t('No payments recorded yet.','لا توجد دفعات مسجلة بعد.')}</p>}
  </section>;}
}
