import { t } from '../lib/i18n.js';
import { Button } from './UI.js';

interface Props{src:string;onApply:(dataUrl:string)=>void;}
interface State{open:boolean;ready:boolean;tool:'tap'|'erase';tolerance:number;brush:number;canUndo:boolean;error:string;}

function loadImage(src:string):Promise<HTMLImageElement>{return new Promise((resolve,reject)=>{const image=new Image();image.onload=()=>resolve(image);image.onerror=()=>reject(new Error(t('Unable to open logo image.','تعذر فتح صورة الشعار.')));image.src=src;});}
function cloneImageData(data:ImageData):ImageData{return new ImageData(new Uint8ClampedArray(data.data),data.width,data.height);}

export class LogoBackgroundEditor extends React.Component<Props,State>{
  private canvasRef=React.createRef<HTMLCanvasElement>();
  private original:ImageData|null=null;
  private history:ImageData[]=[];
  private drawing=false;
  constructor(props:Props){super(props);this.state={open:false,ready:false,tool:'tap',tolerance:42,brush:28,canUndo:false,error:''};}

  private open=()=>this.setState({open:true,ready:false,error:'',canUndo:false},()=>void this.prepare());
  private close=()=>{this.drawing=false;this.setState({open:false,error:''});};
  private prepare=async()=>{
    try{
      const image=await loadImage(this.props.src);const naturalWidth=image.naturalWidth||image.width,naturalHeight=image.naturalHeight||image.height;
      if(!naturalWidth||!naturalHeight)throw new Error(t('Logo image is empty.','صورة الشعار فارغة.'));
      const maxDimension=1600,scale=Math.min(1,maxDimension/Math.max(naturalWidth,naturalHeight)),width=Math.max(1,Math.round(naturalWidth*scale)),height=Math.max(1,Math.round(naturalHeight*scale));
      const canvas=this.canvasRef.current;if(!canvas)return;canvas.width=width;canvas.height=height;const context=canvas.getContext('2d',{willReadFrequently:true});if(!context)throw new Error(t('Image editor is unavailable.','محرر الصورة غير متاح.'));
      context.clearRect(0,0,width,height);context.drawImage(image,0,0,width,height);this.original=context.getImageData(0,0,width,height);this.history=[];this.setState({ready:true,canUndo:false,error:''});
    }catch(error){this.setState({ready:false,error:error instanceof Error?error.message:t('Unable to prepare logo editor.','تعذر تجهيز محرر الشعار.')});}
  };
  private snapshot=()=>{const canvas=this.canvasRef.current,context=canvas?.getContext('2d',{willReadFrequently:true});if(!canvas||!context)return;this.history.push(context.getImageData(0,0,canvas.width,canvas.height));if(this.history.length>12)this.history.shift();this.setState({canUndo:true});};
  private undo=()=>{const canvas=this.canvasRef.current,context=canvas?.getContext('2d',{willReadFrequently:true}),previous=this.history.pop();if(!canvas||!context||!previous)return;context.putImageData(previous,0,0);this.setState({canUndo:this.history.length>0});};
  private reset=()=>{const canvas=this.canvasRef.current,context=canvas?.getContext('2d',{willReadFrequently:true});if(!canvas||!context||!this.original)return;context.putImageData(cloneImageData(this.original),0,0);this.history=[];this.setState({canUndo:false,error:''});};
  private point=(event:React.PointerEvent<HTMLCanvasElement>)=>{const canvas=event.currentTarget,rect=canvas.getBoundingClientRect(),x=Math.max(0,Math.min(canvas.width-1,Math.floor((event.clientX-rect.left)*canvas.width/Math.max(1,rect.width)))),y=Math.max(0,Math.min(canvas.height-1,Math.floor((event.clientY-rect.top)*canvas.height/Math.max(1,rect.height))));return{x,y};};
  private flood=(x:number,y:number)=>{
    const canvas=this.canvasRef.current,context=canvas?.getContext('2d',{willReadFrequently:true});if(!canvas||!context)return;const image=context.getImageData(0,0,canvas.width,canvas.height),data=image.data,width=canvas.width,height=canvas.height,total=width*height,seed=(y*width+x)*4,seedAlpha=data[seed+3]??0;if(seedAlpha<=10)return;
    const sr=data[seed]??0,sg=data[seed+1]??0,sb=data[seed+2]??0,threshold=this.state.tolerance*this.state.tolerance*3,visited=new Uint8Array(total),queue=new Int32Array(total);let start=0,end=0;queue[end++]=y*width+x;visited[y*width+x]=1;let changed=0;
    while(start<end){const pixel=queue[start++]??0,index=pixel*4,alpha=data[index+3]??0;if(alpha<=10)continue;const dr=(data[index]??0)-sr,dg=(data[index+1]??0)-sg,db=(data[index+2]??0)-sb;if(dr*dr+dg*dg+db*db>threshold)continue;data[index+3]=0;changed+=1;const px=pixel%width,py=Math.floor(pixel/width);const visit=(next:number)=>{if(next<0||next>=total||visited[next])return;visited[next]=1;queue[end++]=next;};if(px>0)visit(pixel-1);if(px+1<width)visit(pixel+1);if(py>0)visit(pixel-width);if(py+1<height)visit(pixel+width);}
    if(changed>0)context.putImageData(image,0,0);
  };
  private erase=(x:number,y:number)=>{const canvas=this.canvasRef.current,context=canvas?.getContext('2d',{willReadFrequently:true});if(!canvas||!context)return;const image=context.getImageData(0,0,canvas.width,canvas.height),data=image.data,radius=Math.max(2,Math.round(this.state.brush*canvas.width/Math.max(320,canvas.clientWidth||320))),r2=radius*radius,left=Math.max(0,x-radius),right=Math.min(canvas.width-1,x+radius),top=Math.max(0,y-radius),bottom=Math.min(canvas.height-1,y+radius);for(let py=top;py<=bottom;py+=1)for(let px=left;px<=right;px+=1){const dx=px-x,dy=py-y;if(dx*dx+dy*dy<=r2)data[(py*canvas.width+px)*4+3]=0;}context.putImageData(image,0,0);};
  private pointerDown=(event:React.PointerEvent<HTMLCanvasElement>)=>{if(!this.state.ready)return;event.preventDefault();event.currentTarget.setPointerCapture?.(event.pointerId);const{x,y}=this.point(event);this.snapshot();if(this.state.tool==='tap'){this.flood(x,y);return;}this.drawing=true;this.erase(x,y);};
  private pointerMove=(event:React.PointerEvent<HTMLCanvasElement>)=>{if(!this.drawing||this.state.tool!=='erase')return;event.preventDefault();const{x,y}=this.point(event);this.erase(x,y);};
  private pointerUp=()=>{this.drawing=false;};
  private crop=():string=>{const canvas=this.canvasRef.current,context=canvas?.getContext('2d',{willReadFrequently:true});if(!canvas||!context)return this.props.src;const pixels=context.getImageData(0,0,canvas.width,canvas.height),data=pixels.data;let left=canvas.width,top=canvas.height,right=-1,bottom=-1;for(let index=0;index<data.length;index+=4){if((data[index+3]??0)<=10)continue;const pixel=Math.floor(index/4),x=pixel%canvas.width,y=Math.floor(pixel/canvas.width);left=Math.min(left,x);right=Math.max(right,x);top=Math.min(top,y);bottom=Math.max(bottom,y);}if(right<left||bottom<top)return this.props.src;const padding=Math.max(4,Math.round(Math.min(canvas.width,canvas.height)*.015)),cropLeft=Math.max(0,left-padding),cropTop=Math.max(0,top-padding),cropRight=Math.min(canvas.width-1,right+padding),cropBottom=Math.min(canvas.height-1,bottom+padding),cropWidth=cropRight-cropLeft+1,cropHeight=cropBottom-cropTop+1,output=document.createElement('canvas');output.width=cropWidth;output.height=cropHeight;const out=output.getContext('2d');if(!out)return canvas.toDataURL('image/png');out.clearRect(0,0,cropWidth,cropHeight);out.drawImage(canvas,cropLeft,cropTop,cropWidth,cropHeight,0,0,cropWidth,cropHeight);return output.toDataURL('image/png');};
  private apply=()=>{if(!this.state.ready)return;const result=this.crop();this.props.onApply(result);this.close();};

  render():any{return <><button type="button" className="logo-manual-edit-action" onClick={this.open}>{t('Remove background manually','إزالة الخلفية يدويًا')}</button>{this.state.open?<div className="logo-editor-overlay" role="dialog" aria-modal="true" aria-label={t('Logo background editor','محرر خلفية الشعار')}><div className="logo-editor-sheet"><header><div><strong>{t('Remove logo background','إزالة خلفية الشعار')}</strong><span>{t('Tap an unwanted area to remove it, or use the eraser for precise cleanup.','اضغط على الجزء غير المرغوب لحذفه، أو استخدم الممحاة للتنظيف الدقيق.')}</span></div><button type="button" className="logo-editor-close" onClick={this.close} aria-label={t('Close','إغلاق')}>×</button></header><div className="logo-editor-canvas-wrap"><canvas ref={this.canvasRef} onPointerDown={this.pointerDown} onPointerMove={this.pointerMove} onPointerUp={this.pointerUp} onPointerCancel={this.pointerUp}/>{!this.state.ready&&!this.state.error?<div className="logo-editor-loading">{t('Preparing logo…','جارٍ تجهيز الشعار…')}</div>:null}</div>{this.state.error?<p className="logo-editor-error">{this.state.error}</p>:null}<div className="logo-editor-tools"><div className="logo-editor-tool-switch"><button type="button" className={this.state.tool==='tap'?'active':''} onClick={()=>this.setState({tool:'tap'})}>{t('Tap area','لمس المنطقة')}</button><button type="button" className={this.state.tool==='erase'?'active':''} onClick={()=>this.setState({tool:'erase'})}>{t('Eraser','ممحاة')}</button></div>{this.state.tool==='tap'?<label><span>{t('Tolerance','حساسية اللون')} {this.state.tolerance}</span><input type="range" min="8" max="90" step="1" value={this.state.tolerance} onChange={(e:any)=>this.setState({tolerance:Number(e.target.value)})}/></label>:<label><span>{t('Eraser size','حجم الممحاة')} {this.state.brush}</span><input type="range" min="8" max="72" step="1" value={this.state.brush} onChange={(e:any)=>this.setState({brush:Number(e.target.value)})}/></label>}<div className="logo-editor-secondary"><button type="button" disabled={!this.state.canUndo} onClick={this.undo}>{t('Undo','تراجع')}</button><button type="button" onClick={this.reset}>{t('Reset','إعادة ضبط')}</button></div></div><footer><Button onClick={this.close}>{t('Cancel','إلغاء')}</Button><Button variant="primary" disabled={!this.state.ready} onClick={this.apply}>{t('Use this logo','اعتماد هذا الشعار')}</Button></footer></div></div>:null}</>;}
}
