import type { ExpenseRecord, InventoryMovementRecord, InventoryMovementType, PurchaseRecord, SavedItem, Supplier } from '../types.js';
import { t } from '../lib/i18n.js';
import { formatMoney } from '../lib/money.js';
import { todayIso } from '../lib/id.js';
import { allocateLandedCost, createExpense, createManualInventoryMovement, createPurchase, createPurchaseItem, createSupplier, inventoryBalances, inventoryMovementIsManual, purchaseTotals, spendByCurrency, supplierSnapshotFrom, validateExpense, validatePurchase, validateSupplier } from '../lib/operations.js';
import { Button, Icon, Input, Select, Textarea } from './UI.js';

type Tab='suppliers'|'purchases'|'expenses'|'inventory';
type ManualMovementType=Extract<InventoryMovementType,'opening'|'issue'|'adjustment'>;

interface Props{
  suppliers:Supplier[];purchases:PurchaseRecord[];expenses:ExpenseRecord[];inventoryMovements:InventoryMovementRecord[];items:SavedItem[];defaultCurrency:string;
  onSaveSupplier:(supplier:Supplier)=>Promise<void>;onDeleteSupplier:(supplier:Supplier)=>Promise<void>;
  onSavePurchase:(purchase:PurchaseRecord)=>Promise<void>;onDeletePurchase:(purchase:PurchaseRecord)=>Promise<void>;onPostPurchase:(purchase:PurchaseRecord)=>Promise<void>;onReversePurchase:(purchase:PurchaseRecord,reason:string)=>Promise<void>;
  onSaveExpense:(expense:ExpenseRecord)=>Promise<void>;onDeleteExpense:(expense:ExpenseRecord)=>Promise<void>;
  onSaveInventoryMovement:(movement:InventoryMovementRecord)=>Promise<void>;onDeleteInventoryMovement:(movement:InventoryMovementRecord)=>Promise<void>;
}
interface State{
  tab:Tab;search:string;error:string;supplierEdit:Supplier|null;purchaseEdit:PurchaseRecord|null;expenseEdit:ExpenseRecord|null;
  movementItemId:string;movementType:ManualMovementType;movementQuantity:string;movementDate:string;movementNote:string;movementCost:string;movementCurrency:string;
}

const currencies=['USD','EUR','SAR','TRY','AED','GBP'];
const expenseCategories=['General','Freight','Customs','Storage','Transport','Marketing','Office','Professional','Bank Fees','Other'];
function supplierLabel(supplier:Supplier):string{return supplier.nameEn||supplier.nameAr||t('Unnamed supplier','مورد بدون اسم');}
function purchaseSupplierLabel(purchase:PurchaseRecord):string{return purchase.supplierSnapshot?.nameEn||purchase.supplierSnapshot?.nameAr||t('No supplier','بدون مورد');}
function itemLabel(item:SavedItem):string{return [item.sku,item.descriptionEn||item.descriptionAr].filter(Boolean).join(' · ');}
function movementTypeLabel(type:InventoryMovementType):string{
  if(type==='purchase')return t('Purchase receipt','استلام شراء');if(type==='purchase-reversal')return t('Purchase reversal','عكس شراء');if(type==='opening')return t('Opening stock','رصيد افتتاحي');if(type==='issue')return t('Stock issue','إخراج مخزون');return t('Adjustment','تسوية');
}

export class OperationsPage extends React.Component<Props,State>{
  state:State={tab:'suppliers',search:'',error:'',supplierEdit:null,purchaseEdit:null,expenseEdit:null,movementItemId:'',movementType:'opening',movementQuantity:'',movementDate:todayIso(),movementNote:'',movementCost:'',movementCurrency:this.props.defaultCurrency||'USD'};

  private fail=(error:unknown)=>this.setState({error:error instanceof Error?error.message:String(error)});
  private clearError=()=>this.setState({error:''});
  private visible=(...values:string[])=>{const q=this.state.search.trim().toLowerCase();return !q||values.join(' ').toLowerCase().includes(q);};

  private saveSupplier=async()=>{
    const supplier=this.state.supplierEdit;if(!supplier)return;const errors=validateSupplier(supplier);if(errors.length){this.setState({error:errors[0]??t('Validation failed.','فشل التحقق.')});return;}
    try{await this.props.onSaveSupplier({...supplier,defaultCurrency:supplier.defaultCurrency.trim().toUpperCase(),updatedAt:new Date().toISOString()});this.setState({supplierEdit:null,error:''});}catch(e){this.fail(e);}
  };
  private deleteSupplier=async(supplier:Supplier)=>{if(!window.confirm(t(`Delete ${supplierLabel(supplier)}?`,`حذف ${supplierLabel(supplier)}؟`)))return;try{await this.props.onDeleteSupplier(supplier);if(this.state.supplierEdit?.id===supplier.id)this.setState({supplierEdit:null});}catch(e){this.fail(e);}};

  private newPurchase=()=>{const purchase=createPurchase(this.props.purchases,this.props.suppliers,this.props.defaultCurrency);purchase.items=[createPurchaseItem()];this.setState({purchaseEdit:purchase,error:''});};
  private choosePurchaseSupplier=(supplierId:string)=>this.setState(state=>{
    if(!state.purchaseEdit)return null as any;const supplier=this.props.suppliers.find(item=>item.id===supplierId);return {purchaseEdit:{...state.purchaseEdit,supplierSnapshot:supplier?supplierSnapshotFrom(supplier):null,currency:supplier?.defaultCurrency||state.purchaseEdit.currency}} as any;
  });
  private updatePurchaseItem=(id:string,patch:Partial<PurchaseRecord['items'][number]>)=>this.setState(state=>state.purchaseEdit?({purchaseEdit:{...state.purchaseEdit,items:state.purchaseEdit.items.map(item=>item.id===id?{...item,...patch}:item)}} as any):null as any);
  private chooseSavedItem=(lineId:string,itemId:string)=>{
    const saved=this.props.items.find(item=>item.id===itemId);if(!saved){this.updatePurchaseItem(lineId,{savedItemId:'',sku:''});return;}
    this.updatePurchaseItem(lineId,{savedItemId:saved.id,sku:saved.sku??'',descriptionEn:saved.descriptionEn,descriptionAr:saved.descriptionAr,unit:saved.unit||'PCS',unitCost:saved.lastUnitCost??''});
  };
  private addPurchaseItem=()=>this.setState(state=>state.purchaseEdit?({purchaseEdit:{...state.purchaseEdit,items:[...state.purchaseEdit.items,createPurchaseItem()]}} as any):null as any);
  private removePurchaseItem=(id:string)=>this.setState(state=>state.purchaseEdit?({purchaseEdit:{...state.purchaseEdit,items:state.purchaseEdit.items.filter(item=>item.id!==id)}} as any):null as any);
  private savePurchase=async()=>{const purchase=this.state.purchaseEdit;if(!purchase)return;const errors=validatePurchase(purchase,this.props.items);if(errors.length){this.setState({error:errors[0]??t('Validation failed.','فشل التحقق.')});return;}try{await this.props.onSavePurchase({...purchase,currency:purchase.currency.trim().toUpperCase(),updatedAt:new Date().toISOString()});this.setState({purchaseEdit:null,error:''});}catch(e){this.fail(e);}};
  private postPurchase=async()=>{const purchase=this.state.purchaseEdit;if(!purchase)return;const errors=validatePurchase(purchase,this.props.items);if(errors.length){this.setState({error:errors[0]??t('Validation failed.','فشل التحقق.')});return;}if(!window.confirm(t('Post this purchase? Stock receipts and landed costs will be recorded and the purchase becomes read-only.','ترحيل هذا الشراء؟ سيتم تسجيل استلام المخزون وتكلفة الوصول وسيصبح الشراء للقراءة فقط.')))return;try{await this.props.onPostPurchase({...purchase,currency:purchase.currency.trim().toUpperCase()});this.setState({purchaseEdit:null,error:''});}catch(e){this.fail(e);}};
  private deletePurchase=async(purchase:PurchaseRecord)=>{if(purchase.status!=='draft'){this.setState({error:t('Only draft purchases can be deleted.','يمكن حذف مسودات الشراء فقط.')});return;}if(!window.confirm(t(`Delete ${purchase.number}?`,`حذف ${purchase.number}؟`)))return;try{await this.props.onDeletePurchase(purchase);if(this.state.purchaseEdit?.id===purchase.id)this.setState({purchaseEdit:null});}catch(e){this.fail(e);}};
  private reversePurchase=async(purchase:PurchaseRecord)=>{const reason=window.prompt(t('Reason for reversing this posted purchase:','سبب عكس عملية الشراء المرحلة:'))?.trim()??'';if(!reason)return;try{await this.props.onReversePurchase(purchase,reason);}catch(e){this.fail(e);}};

  private saveExpense=async()=>{const expense=this.state.expenseEdit;if(!expense)return;const errors=validateExpense(expense);if(errors.length){this.setState({error:errors[0]??t('Validation failed.','فشل التحقق.')});return;}try{await this.props.onSaveExpense({...expense,currency:expense.currency.trim().toUpperCase(),updatedAt:new Date().toISOString()});this.setState({expenseEdit:null,error:''});}catch(e){this.fail(e);}};
  private deleteExpense=async(expense:ExpenseRecord)=>{if(!window.confirm(t('Delete this expense?','حذف هذا المصروف؟')))return;try{await this.props.onDeleteExpense(expense);if(this.state.expenseEdit?.id===expense.id)this.setState({expenseEdit:null});}catch(e){this.fail(e);}};

  private saveMovement=async()=>{
    const item=this.props.items.find(entry=>entry.id===this.state.movementItemId);if(!item){this.setState({error:t('Choose a saved item first.','اختر صنفًا محفوظًا أولًا.')});return;}
    try{const movement=createManualInventoryMovement(item,this.state.movementType,this.state.movementQuantity,this.state.movementDate,this.state.movementNote,this.state.movementCost,this.state.movementCurrency);await this.props.onSaveInventoryMovement(movement);this.setState({movementQuantity:'',movementNote:'',movementCost:'',error:''});}catch(e){this.fail(e);}
  };
  private deleteMovement=async(movement:InventoryMovementRecord)=>{if(!inventoryMovementIsManual(movement)){this.setState({error:t('Purchase-generated inventory movements cannot be deleted. Reverse the purchase instead.','لا يمكن حذف حركات المخزون الناتجة عن شراء. اعكس الشراء بدلًا من ذلك.')});return;}if(!window.confirm(t('Reverse this manual inventory movement? The original record will stay in history.','عكس حركة المخزون اليدوية؟ سيبقى السجل الأصلي محفوظًا في التاريخ.')))return;try{await this.props.onDeleteInventoryMovement(movement);}catch(e){this.fail(e);}};

  private renderSummary():any{
    const spend=spendByCurrency(this.props.purchases,this.props.expenses);
    return <div className="operations-summary">
      <div><strong>{this.props.suppliers.length}</strong><span>{t('Suppliers','الموردون')}</span></div>
      <div><strong>{this.props.purchases.filter(p=>p.status==='posted').length}</strong><span>{t('Posted purchases','مشتريات مرحلة')}</span></div>
      <div><strong>{this.props.expenses.length}</strong><span>{t('Expenses','المصروفات')}</span></div>
      <div className="operations-spend-card"><span>{t('Spend by currency','الإنفاق حسب العملة')}</span>{spend.length?spend.slice(0,3).map(row=><strong key={row.currency}>{formatMoney(row.total,row.currency)}</strong>):<strong>—</strong>}</div>
    </div>;
  }

  private renderSuppliers():any{
    const list=this.props.suppliers.filter(s=>this.visible(s.nameEn,s.nameAr,s.contactPerson,s.country,s.phone,s.email));
    const edit=this.state.supplierEdit;
    return <div className="operations-split"><section className="operations-list-panel"><div className="operations-panel-head"><div><h2>{t('Suppliers','الموردون')}</h2><p>{t('Reusable purchasing counterparties. Historical purchases keep their own supplier snapshot.','جهات شراء محفوظة، مع بقاء بيانات المورد التاريخية داخل كل عملية شراء.')}</p></div><Button icon="plus" variant="primary" onClick={()=>this.setState({supplierEdit:createSupplier(),error:''})}>{t('New Supplier','مورد جديد')}</Button></div>
      <div className="operations-list">{list.length?list.map(s=><article key={s.id} className="operation-row"><div><strong>{supplierLabel(s)}</strong><span>{[s.contactPerson,s.country,s.defaultCurrency].filter(Boolean).join(' · ')}</span></div><div className="row-actions"><button onClick={()=>this.setState({supplierEdit:{...s},error:''})}>{t('Edit','تعديل')}</button><button className="danger-link" onClick={()=>void this.deleteSupplier(s)}>{t('Delete','حذف')}</button></div></article>):<div className="operations-empty">{t('No suppliers yet.','لا يوجد موردون بعد.')}</div>}</div></section>
      {edit?<section className="operations-editor"><div className="operations-panel-head"><h2>{edit.createdAt===edit.updatedAt?t('Supplier','المورد'):t('Edit Supplier','تعديل المورد')}</h2><button type="button" className="plain-close" aria-label={t('Close editor','إغلاق المحرر')} onClick={()=>this.setState({supplierEdit:null,error:''})}>×</button></div><div className="operations-form-grid">
        <label>{t('Name EN','الاسم EN')}<Input value={edit.nameEn} onChange={(e:any)=>this.setState({supplierEdit:{...edit,nameEn:e.target.value}})}/></label><label>{t('Name AR','الاسم AR')}<Input dir="rtl" value={edit.nameAr} onChange={(e:any)=>this.setState({supplierEdit:{...edit,nameAr:e.target.value}})}/></label>
        <label>{t('Contact person','جهة الاتصال')}<Input value={edit.contactPerson} onChange={(e:any)=>this.setState({supplierEdit:{...edit,contactPerson:e.target.value}})}/></label><label>{t('Country','الدولة')}<Input value={edit.country} onChange={(e:any)=>this.setState({supplierEdit:{...edit,country:e.target.value}})}/></label>
        <label>{t('City','المدينة')}<Input value={edit.city} onChange={(e:any)=>this.setState({supplierEdit:{...edit,city:e.target.value}})}/></label><label>{t('Phone','الهاتف')}<Input value={edit.phone} onChange={(e:any)=>this.setState({supplierEdit:{...edit,phone:e.target.value}})}/></label>
        <label>{t('Email','البريد')}<Input type="email" value={edit.email} onChange={(e:any)=>this.setState({supplierEdit:{...edit,email:e.target.value}})}/></label><label>{t('Default currency','العملة الافتراضية')}<Input list="operations-currencies" value={edit.defaultCurrency} onChange={(e:any)=>this.setState({supplierEdit:{...edit,defaultCurrency:e.target.value.toUpperCase()}})}/></label>
        <label className="span-2">{t('Address','العنوان')}<Input value={edit.address} onChange={(e:any)=>this.setState({supplierEdit:{...edit,address:e.target.value}})}/></label>
        <label>{t('VAT / Tax No.','رقم الضريبة')}<Input value={edit.vatTaxNumber} onChange={(e:any)=>this.setState({supplierEdit:{...edit,vatTaxNumber:e.target.value}})}/></label><label>{t('Commercial Registration','السجل التجاري')}<Input value={edit.commercialRegistration} onChange={(e:any)=>this.setState({supplierEdit:{...edit,commercialRegistration:e.target.value}})}/></label>
        <label className="span-2">{t('Payment terms','شروط الدفع')}<Input value={edit.paymentTerms} onChange={(e:any)=>this.setState({supplierEdit:{...edit,paymentTerms:e.target.value}})}/></label><label className="span-2">{t('Notes','ملاحظات')}<Textarea value={edit.notes} onChange={(e:any)=>this.setState({supplierEdit:{...edit,notes:e.target.value}})}/></label>
      </div><div className="operations-editor-actions"><Button onClick={()=>this.setState({supplierEdit:null,error:''})}>{t('Cancel','إلغاء')}</Button><Button icon="save" variant="primary" onClick={()=>void this.saveSupplier()}>{t('Save Supplier','حفظ المورد')}</Button></div></section>:null}</div>;
  }

  private renderPurchases():any{
    const list=[...this.props.purchases].sort((a,b)=>b.date.localeCompare(a.date)||b.updatedAt.localeCompare(a.updatedAt)).filter(p=>this.visible(p.number,purchaseSupplierLabel(p),p.currency,p.status));
    const edit=this.state.purchaseEdit;const totals=edit?purchaseTotals(edit):null;const allocated=edit?allocateLandedCost(edit):null;
    return <div className="operations-split purchase-layout"><section className="operations-list-panel"><div className="operations-panel-head"><div><h2>{t('Purchases','المشتريات')}</h2><p>{t('Post a purchase only when received. Posting creates stock receipt movements and freezes the record.','رحّل الشراء عند الاستلام فقط؛ الترحيل ينشئ حركات استلام للمخزون ويقفل السجل.')}</p></div><Button icon="plus" variant="primary" disabled={!this.props.suppliers.length} onClick={this.newPurchase}>{t('New Purchase','شراء جديد')}</Button></div>{!this.props.suppliers.length?<div className="operations-callout">{t('Add a supplier before creating a purchase.','أضف موردًا قبل إنشاء عملية شراء.')}</div>:null}
      <div className="operations-list">{list.length?list.map(p=>{const rowTotals=purchaseTotals(p);return <article key={p.id} className="operation-row purchase-row"><div><strong>{p.number}</strong><span>{purchaseSupplierLabel(p)} · {p.date} · {formatMoney(rowTotals.landedTotal,p.currency)}</span></div><span className={`operation-status status-${p.status}`}>{p.status==='posted'?t('Posted','مرحل'):p.status==='reversed'?t('Reversed','معكوس'):t('Draft','مسودة')}</span><div className="row-actions"><button onClick={()=>this.setState({purchaseEdit:JSON.parse(JSON.stringify(p)),error:''})}>{t('View','عرض')}</button>{p.status==='draft'?<button className="danger-link" onClick={()=>void this.deletePurchase(p)}>{t('Delete','حذف')}</button>:p.status==='posted'?<button className="danger-link" onClick={()=>void this.reversePurchase(p)}>{t('Reverse','عكس')}</button>:null}</div></article>}):<div className="operations-empty">{t('No purchases yet.','لا توجد مشتريات بعد.')}</div>}</div></section>
      {edit?<section className="operations-editor purchase-editor"><div className="operations-panel-head"><div><h2>{edit.number}</h2><span className={`operation-status status-${edit.status}`}>{edit.status}</span></div><button type="button" className="plain-close" aria-label={t('Close editor','إغلاق المحرر')} onClick={()=>this.setState({purchaseEdit:null,error:''})}>×</button></div>{edit.status==='reversed'?<div className="operations-callout danger">{t('Reversed: ','معكوس: ')}{edit.reverseReason}</div>:null}<fieldset disabled={edit.status!=='draft'}><div className="operations-form-grid compact">
        <label>{t('Purchase No.','رقم الشراء')}<Input value={edit.number} onChange={(e:any)=>this.setState({purchaseEdit:{...edit,number:e.target.value}})}/></label><label>{t('Date','التاريخ')}<Input type="date" value={edit.date} onChange={(e:any)=>this.setState({purchaseEdit:{...edit,date:e.target.value}})}/></label>
        <label>{t('Supplier','المورد')}<Select value={edit.supplierSnapshot?.sourceSupplierId??''} onChange={(e:any)=>this.choosePurchaseSupplier(e.target.value)}><option value="">{t('Choose supplier','اختر المورد')}</option>{this.props.suppliers.map(s=><option key={s.id} value={s.id}>{supplierLabel(s)}</option>)}</Select></label><label>{t('Currency','العملة')}<Input list="operations-currencies" value={edit.currency} onChange={(e:any)=>this.setState({purchaseEdit:{...edit,currency:e.target.value.toUpperCase()}})}/></label>
      </div><div className="purchase-items-head"><h3>{t('Items','الأصناف')}</h3><Button icon="plus" onClick={this.addPurchaseItem}>{t('Add Item','إضافة صنف')}</Button></div><div className="purchase-items">{edit.items.map((line,index)=>{const landed=allocated?.items[index]?.landedUnitCost||'';return <div className="purchase-item" key={line.id}><div className="purchase-item-title"><strong>#{index+1}</strong><button type="button" aria-label={t('Remove item','حذف الصنف')} onClick={()=>this.removePurchaseItem(line.id)}>×</button></div><div className="purchase-item-grid"><label>{t('Saved item','الصنف المحفوظ')}<Select value={line.savedItemId} onChange={(e:any)=>this.chooseSavedItem(line.id,e.target.value)}><option value="">{t('Unlinked / service','غير مرتبط / خدمة')}</option>{this.props.items.map(item=><option key={item.id} value={item.id}>{itemLabel(item)}</option>)}</Select></label><label>{t('SKU','SKU')}<Input value={line.sku} onChange={(e:any)=>this.updatePurchaseItem(line.id,{sku:e.target.value})}/></label><label className="span-2">{t('Description EN','الوصف EN')}<Input value={line.descriptionEn} onChange={(e:any)=>this.updatePurchaseItem(line.id,{descriptionEn:e.target.value})}/></label><label>{t('Quantity','الكمية')}<Input inputMode="decimal" value={line.quantity} onChange={(e:any)=>this.updatePurchaseItem(line.id,{quantity:e.target.value})}/></label><label>{t('Unit','الوحدة')}<Input value={line.unit} onChange={(e:any)=>this.updatePurchaseItem(line.id,{unit:e.target.value})}/></label><label>{t('Unit cost','تكلفة الوحدة')}<Input inputMode="decimal" value={line.unitCost} onChange={(e:any)=>this.updatePurchaseItem(line.id,{unitCost:e.target.value})}/></label><label>{t('Landed unit cost','تكلفة الوحدة بعد الوصول')}<Input readOnly value={landed}/></label></div></div>})}</div><div className="operations-form-grid compact purchase-costs"><label>{t('Freight','الشحن')}<Input inputMode="decimal" value={edit.freight} onChange={(e:any)=>this.setState({purchaseEdit:{...edit,freight:e.target.value}})}/></label><label>{t('Duty / Customs','الجمارك')}<Input inputMode="decimal" value={edit.duty} onChange={(e:any)=>this.setState({purchaseEdit:{...edit,duty:e.target.value}})}/></label><label>{t('Other landed costs','تكاليف وصول أخرى')}<Input inputMode="decimal" value={edit.otherCosts} onChange={(e:any)=>this.setState({purchaseEdit:{...edit,otherCosts:e.target.value}})}/></label></div><label className="block-field">{t('Notes','ملاحظات')}<Textarea value={edit.notes} onChange={(e:any)=>this.setState({purchaseEdit:{...edit,notes:e.target.value}})}/></label></fieldset>
      {totals?<div className="purchase-total-strip"><span>{t('Items','الأصناف')} <strong>{formatMoney(totals.subtotal,edit.currency)}</strong></span><span>{t('Landed total','إجمالي تكلفة الوصول')} <strong>{formatMoney(totals.landedTotal,edit.currency)}</strong></span></div>:null}<div className="operations-editor-actions">{edit.status==='draft'?<><Button onClick={()=>this.setState({purchaseEdit:null,error:''})}>{t('Cancel','إلغاء')}</Button><Button icon="save" onClick={()=>void this.savePurchase()}>{t('Save Draft','حفظ المسودة')}</Button><Button icon="check" variant="primary" onClick={()=>void this.postPurchase()}>{t('Post Purchase','ترحيل الشراء')}</Button></>:edit.status==='posted'?<Button variant="danger" onClick={()=>void this.reversePurchase(edit)}>{t('Reverse Purchase','عكس الشراء')}</Button>:<Button onClick={()=>this.setState({purchaseEdit:null,error:''})}>{t('Close','إغلاق')}</Button>}</div></section>:null}</div>;
  }

  private renderExpenses():any{
    const list=[...this.props.expenses].sort((a,b)=>b.date.localeCompare(a.date)||b.updatedAt.localeCompare(a.updatedAt)).filter(e=>this.visible(e.description,e.category,e.reference,e.currency));const edit=this.state.expenseEdit;
    return <div className="operations-split"><section className="operations-list-panel"><div className="operations-panel-head"><div><h2>{t('Expenses','المصروفات')}</h2><p>{t('Operating expenses stay separate from invoice revenue and purchase landed cost.','المصروفات التشغيلية تبقى منفصلة عن إيراد الفواتير وتكلفة وصول المشتريات.')}</p></div><Button icon="plus" variant="primary" onClick={()=>this.setState({expenseEdit:createExpense(this.props.defaultCurrency),error:''})}>{t('New Expense','مصروف جديد')}</Button></div><div className="operations-list">{list.length?list.map(e=><article key={e.id} className="operation-row"><div><strong>{e.description}</strong><span>{e.date} · {e.category} · {formatMoney(e.amount,e.currency)}</span></div><div className="row-actions"><button onClick={()=>this.setState({expenseEdit:{...e},error:''})}>{t('Edit','تعديل')}</button><button className="danger-link" onClick={()=>void this.deleteExpense(e)}>{t('Delete','حذف')}</button></div></article>):<div className="operations-empty">{t('No expenses yet.','لا توجد مصروفات بعد.')}</div>}</div></section>
      {edit?<section className="operations-editor"><div className="operations-panel-head"><h2>{t('Expense','المصروف')}</h2><button type="button" className="plain-close" aria-label={t('Close editor','إغلاق المحرر')} onClick={()=>this.setState({expenseEdit:null,error:''})}>×</button></div><div className="operations-form-grid"><label>{t('Date','التاريخ')}<Input type="date" value={edit.date} onChange={(e:any)=>this.setState({expenseEdit:{...edit,date:e.target.value}})}/></label><label>{t('Category','التصنيف')}<Select value={edit.category} onChange={(e:any)=>this.setState({expenseEdit:{...edit,category:e.target.value}})}>{expenseCategories.map(c=><option key={c} value={c}>{c}</option>)}</Select></label><label className="span-2">{t('Description','الوصف')}<Input value={edit.description} onChange={(e:any)=>this.setState({expenseEdit:{...edit,description:e.target.value}})}/></label><label>{t('Amount','المبلغ')}<Input inputMode="decimal" value={edit.amount} onChange={(e:any)=>this.setState({expenseEdit:{...edit,amount:e.target.value}})}/></label><label>{t('Currency','العملة')}<Input list="operations-currencies" value={edit.currency} onChange={(e:any)=>this.setState({expenseEdit:{...edit,currency:e.target.value.toUpperCase()}})}/></label><label>{t('Supplier (optional)','المورد (اختياري)')}<Select value={edit.supplierId} onChange={(e:any)=>this.setState({expenseEdit:{...edit,supplierId:e.target.value}})}><option value="">—</option>{this.props.suppliers.map(s=><option key={s.id} value={s.id}>{supplierLabel(s)}</option>)}</Select></label><label>{t('Reference','المرجع')}<Input value={edit.reference} onChange={(e:any)=>this.setState({expenseEdit:{...edit,reference:e.target.value}})}/></label><label className="span-2">{t('Notes','ملاحظات')}<Textarea value={edit.notes} onChange={(e:any)=>this.setState({expenseEdit:{...edit,notes:e.target.value}})}/></label></div><div className="operations-editor-actions"><Button onClick={()=>this.setState({expenseEdit:null,error:''})}>{t('Cancel','إلغاء')}</Button><Button icon="save" variant="primary" onClick={()=>void this.saveExpense()}>{t('Save Expense','حفظ المصروف')}</Button></div></section>:null}</div>;
  }

  private renderInventory():any{
    const balances=inventoryBalances(this.props.items,this.props.inventoryMovements).filter(row=>this.visible(row.item.sku??'',row.item.descriptionEn,row.item.descriptionAr,row.quantity));const movements=[...this.props.inventoryMovements].sort((a,b)=>b.date.localeCompare(a.date)||b.createdAt.localeCompare(a.createdAt)).slice(0,80);
    return <div className="inventory-workspace"><section className="inventory-balances"><div className="operations-panel-head"><div><h2>{t('Inventory Ledger','سجل المخزون')}</h2><p>{t('Stock changes only from posted purchases or explicit manual movements. Invoices do not silently change stock.','يتغير المخزون فقط من المشتريات المرحلة أو الحركات اليدوية الصريحة. الفواتير لا تغيّر المخزون تلقائيًا.')}</p></div></div><div className="inventory-table"><div className="inventory-table-head"><span>{t('Item','الصنف')}</span><span>{t('On hand','المتوفر')}</span><span>{t('Last landed cost','آخر تكلفة وصول')}</span></div>{balances.length?balances.map(row=><div className={`inventory-balance-row ${row.quantityScaled<0n?'is-negative':''}`} key={row.item.id}><span><strong>{itemLabel(row.item)}</strong><small>{row.item.category||''}</small></span><strong>{row.quantity} {row.item.unit}</strong><span>{row.item.lastUnitCost&&row.item.lastCostCurrency?formatMoney(row.item.lastUnitCost,row.item.lastCostCurrency):'—'}</span></div>):<div className="operations-empty">{t('No saved items yet.','لا توجد أصناف محفوظة بعد.')}</div>}</div></section>
      <section className="inventory-entry"><h2>{t('Manual Movement','حركة يدوية')}</h2><div className="operations-form-grid compact"><label className="span-2">{t('Saved item','الصنف المحفوظ')}<Select value={this.state.movementItemId} onChange={(e:any)=>this.setState({movementItemId:e.target.value})}><option value="">{t('Choose item','اختر الصنف')}</option>{this.props.items.map(item=><option key={item.id} value={item.id}>{itemLabel(item)}</option>)}</Select></label><label>{t('Type','النوع')}<Select value={this.state.movementType} onChange={(e:any)=>this.setState({movementType:e.target.value})}><option value="opening">{t('Opening stock','رصيد افتتاحي')}</option><option value="issue">{t('Stock issue','إخراج مخزون')}</option><option value="adjustment">{t('Adjustment (+/-)','تسوية (+/-)')}</option></Select></label><label>{t('Date','التاريخ')}<Input type="date" value={this.state.movementDate} onChange={(e:any)=>this.setState({movementDate:e.target.value})}/></label><label>{t('Quantity','الكمية')}<Input inputMode="decimal" value={this.state.movementQuantity} onChange={(e:any)=>this.setState({movementQuantity:e.target.value})}/></label><label>{t('Unit cost (optional)','تكلفة الوحدة (اختياري)')}<Input inputMode="decimal" value={this.state.movementCost} onChange={(e:any)=>this.setState({movementCost:e.target.value})}/></label><label>{t('Currency','العملة')}<Input list="operations-currencies" value={this.state.movementCurrency} onChange={(e:any)=>this.setState({movementCurrency:e.target.value.toUpperCase()})}/></label><label className="span-2">{t('Note','ملاحظة')}<Input value={this.state.movementNote} onChange={(e:any)=>this.setState({movementNote:e.target.value})}/></label></div><Button icon="plus" variant="primary" onClick={()=>void this.saveMovement()}>{t('Record Movement','تسجيل الحركة')}</Button></section>
      <section className="inventory-history"><h2>{t('Recent Movements','الحركات الأخيرة')}</h2><div className="operations-list">{movements.length?movements.map(m=><article key={m.id} className="operation-row"><div><strong>{m.itemNameEn||m.itemNameAr||m.sku}</strong><span>{m.date} · {movementTypeLabel(m.type)}{m.sourceNumber?` · ${m.sourceNumber}`:''}</span></div><strong className={m.quantity.startsWith('-')?'negative-number':'positive-number'}>{m.quantity}</strong>{inventoryMovementIsManual(m)?<div className="row-actions"><button className="danger-link" onClick={()=>void this.deleteMovement(m)}>{t('Delete','حذف')}</button></div>:null}</article>):<div className="operations-empty">{t('No inventory movements yet.','لا توجد حركات مخزون بعد.')}</div>}</div></section>
    </div>;
  }

  render():any{
    return <div className="operations-page"><datalist id="operations-currencies">{currencies.map(c=><option key={c} value={c}/>)}</datalist><div className="operations-hero"><div><span className="eyebrow">{t('Purchasing & Cost Control','المشتريات وضبط التكلفة')}</span><h1>{t('Operations','العمليات')}</h1><p>{t('Suppliers, purchases, operating expenses, landed cost and a simple auditable inventory ledger.','الموردون والمشتريات والمصروفات التشغيلية وتكلفة الوصول وسجل مخزون بسيط وقابل للتدقيق.')}</p></div><div className="operations-search"><Icon name="search"/><Input type="search" aria-label={t('Search current operations tab','بحث في تبويب العمليات الحالي')} value={this.state.search} placeholder={t('Search current tab…','بحث في التبويب الحالي…')} onChange={(e:any)=>this.setState({search:e.target.value})}/></div></div>{this.renderSummary()}<div className="operations-tabs" role="tablist" aria-label={t('Operations sections','أقسام العمليات')}>{(['suppliers','purchases','expenses','inventory'] as Tab[]).map(tab=><button type="button" key={tab} id={`operations-tab-${tab}`} role="tab" aria-selected={this.state.tab===tab} aria-controls={`operations-panel-${tab}`} className={this.state.tab===tab?'active':''} onClick={()=>this.setState({tab,search:'',error:''})}>{tab==='suppliers'?t('Suppliers','الموردون'):tab==='purchases'?t('Purchases','المشتريات'):tab==='expenses'?t('Expenses','المصروفات'):t('Inventory','المخزون')}</button>)}</div>{this.state.error?<div className="operations-error" role="alert"><span>{this.state.error}</span><button type="button" aria-label={t('Dismiss error','إغلاق الخطأ')} onClick={this.clearError}>×</button></div>:null}<div id={`operations-panel-${this.state.tab}`} role="tabpanel" aria-labelledby={`operations-tab-${this.state.tab}`}>{this.state.tab==='suppliers'?this.renderSuppliers():this.state.tab==='purchases'?this.renderPurchases():this.state.tab==='expenses'?this.renderExpenses():this.renderInventory()}</div></div>;
  }
}
