import { conditionalTaskSignals, visibleProactiveSignals, type ProactiveSignal } from '../lib/ai-proactive-assistant.js';
import { scopeVault } from '../lib/workspaces.js';
import { t } from '../lib/i18n.js';
import { dismissProactiveSignal, loadProactiveState, setProactiveCategoryMuted, snoozeProactiveSignal, type ProactiveState } from '../storage/assistant-proactive-store.js';
import { loadAssistantTasks, scopedAssistantTasks, type AssistantTaskRecord } from '../storage/assistant-task-store.js';
import { resumeVaultSession } from '../storage/vault.js';

interface State{signals:ProactiveSignal[];preferences:ProactiveState|null;personalDue:number;busy:boolean;error:string;}
const WEIGHT={urgent:4,attention:3,opportunity:2,info:1} as const;
function tomorrowDateTime():string{const date=new Date();date.setHours(date.getHours()+24);return date.toISOString();}
function levelLabel(level:ProactiveSignal['category']):string{return level==='urgent'?t('URGENT','عاجل'):level==='attention'?t('ATTENTION','انتباه'):level==='opportunity'?t('OPPORTUNITY','فرصة'):t('INFO','معلومة');}
function duePlainTaskSignals(tasks:AssistantTaskRecord[],at=Date.now()):ProactiveSignal[]{return tasks.filter(task=>task.status==='open'&&task.conditionType==='none'&&(!task.dueAt||Date.parse(task.snoozedUntil||task.dueAt)<=at)).slice(0,8).map(task=>({key:`task-reminder:${task.id}`,kind:'conditional-task',category:'attention',title:`Reminder — ${task.title}`,titleAr:`تذكير — ${task.title}`,detail:task.notes||'A saved business reminder is due.',detailAr:task.notes||'تذكير أعمال محفوظ مستحق الآن.',actionLabel:'Open tasks',actionLabelAr:'فتح المهام',searchQuery:'',evidence:[`assistant-task:${task.id}`]}));}
function sortSignals(rows:ProactiveSignal[]):ProactiveSignal[]{const seen=new Set<string>();return rows.filter(row=>{if(seen.has(row.key))return false;seen.add(row.key);return true;}).sort((a,b)=>(WEIGHT[b.category]??0)-(WEIGHT[a.category]??0)||a.title.localeCompare(b.title));}
function openSignal(signal:ProactiveSignal):void{if(signal.searchQuery)window.dispatchEvent(new CustomEvent('lourex-global-search-open',{detail:{query:signal.searchQuery,autoOpenUnique:true}}));else{const launcher=document.querySelector<HTMLButtonElement>('.lourex-ai-launcher');if(launcher&&!document.getElementById('lourex-ai-panel'))launcher.click();window.setTimeout(()=>document.querySelector<HTMLButtonElement>('#lourex-ai-panel .lourex-ai-manager-button')?.click(),80);}}
function openBrief():void{window.dispatchEvent(new CustomEvent('lourex-ai-open-daily'));}

export class ProactiveAssistantTool extends React.Component<Record<string,never>,State>{
  state:State={signals:[],preferences:null,personalDue:0,busy:false,error:''};
  private timer:number|undefined;
  componentDidMount():void{void this.refresh();window.addEventListener('focus',this.onWake);document.addEventListener('visibilitychange',this.onVisibility);this.timer=window.setInterval(()=>void this.refresh(),5*60*1000);}
  componentWillUnmount():void{window.removeEventListener('focus',this.onWake);document.removeEventListener('visibilitychange',this.onVisibility);if(this.timer)window.clearInterval(this.timer);}
  private onWake=()=>void this.refresh();
  private onVisibility=()=>{if(document.visibilityState==='visible')void this.refresh();};
  private refresh=async()=>{if(this.state.busy)return;this.setState({busy:true});try{const resumed=await resumeVaultSession();if(!resumed){this.setState({signals:[],preferences:null,personalDue:0,busy:false,error:''});return;}const vault=scopeVault(resumed.vault),[preferences,tasksState]=await Promise.all([loadProactiveState(resumed.key),loadAssistantTasks(resumed.key)]),workspaceId=vault.appSettings.activeWorkspaceId,branchId=vault.appSettings.activeBranchId,businessTasks=scopedAssistantTasks(tasksState,{scope:'business',workspaceId,branchId,status:'open'}),personalTasks=scopedAssistantTasks(tasksState,{scope:'personal',status:'open'}),base=visibleProactiveSignals(vault,preferences,undefined,12),conditional=conditionalTaskSignals(vault,businessTasks).filter(signal=>!preferences.mutedCategories.includes(signal.category)),plain=duePlainTaskSignals(businessTasks).filter(signal=>!preferences.mutedCategories.includes(signal.category)),now=Date.now(),personalDue=personalTasks.filter(task=>!task.dueAt||Date.parse(task.snoozedUntil||task.dueAt)<=now).length;this.setState({signals:sortSignals([...base,...conditional,...plain]).slice(0,12),preferences,personalDue,busy:false,error:''});}catch(error){this.setState({busy:false,error:error instanceof Error?error.message:String(error)});}};
  private dismiss=async(signal:ProactiveSignal)=>{try{const resumed=await resumeVaultSession();if(!resumed)return;await dismissProactiveSignal(resumed.key,signal.key);await this.refresh();}catch(error){this.setState({error:error instanceof Error?error.message:String(error)});}};
  private snooze=async(signal:ProactiveSignal)=>{try{const resumed=await resumeVaultSession();if(!resumed)return;await snoozeProactiveSignal(resumed.key,signal.key,tomorrowDateTime());await this.refresh();}catch(error){this.setState({error:error instanceof Error?error.message:String(error)});}};
  private mute=async(signal:ProactiveSignal)=>{try{const resumed=await resumeVaultSession();if(!resumed)return;await setProactiveCategoryMuted(resumed.key,signal.category,true);await this.refresh();}catch(error){this.setState({error:error instanceof Error?error.message:String(error)});}};
  render():any{const preferences=this.state.preferences;if(!preferences||preferences.morningBriefEnabled===false)return null;const top=this.state.signals[0]??null;return <div className={`lourex-proactive-dock${top?' has-signal':''}`} data-lourex-proactive-ready="true">{top?<article className={`lourex-proactive-signal is-${top.category}`}><div className="lourex-proactive-copy"><small>{levelLabel(top.category)} · {t('BUSINESS','أعمال')}</small><strong><bdi dir="auto">{document.documentElement.lang==='ar'?top.titleAr:top.title}</bdi></strong><p><bdi dir="auto">{document.documentElement.lang==='ar'?top.detailAr:top.detail}</bdi></p></div><div className="lourex-proactive-actions"><button type="button" onClick={()=>openSignal(top)}>{t('Open','فتح')}</button><button type="button" onClick={()=>void this.snooze(top)}>{t('Remind later','ذكرني لاحقًا')}</button><button type="button" onClick={()=>void this.dismiss(top)}>{t('Dismiss','إخفاء')}</button><button type="button" onClick={()=>void this.mute(top)}>{t('Mute category','كتم الفئة')}</button></div></article>:null}<button type="button" className="lourex-proactive-brief-button" onClick={openBrief}>{t('Morning Brief','الموجز الصباحي')}{this.state.personalDue?` · ${this.state.personalDue} ${t('personal','شخصي')}`:''}</button>{this.state.error?<small role="alert" className="lourex-proactive-error">{this.state.error}</small>:null}</div>;}
}
