import { t } from '../lib/i18n.js';
import { reviewDraftPurchases, type PurchaseGuardianIssue, type PurchaseGuardianReview } from '../lib/purchase-guardian.js';
import { resumeVaultSession } from '../storage/vault.js';
import { Button, Icon, Modal } from './UI.js';

interface State{open:boolean;busy:boolean;reviews:PurchaseGuardianReview[];error:string;}
function severityLabel(value:PurchaseGuardianIssue['severity']):string{return value==='critical'?t('Critical','حرج'):value==='warning'?t('Warning','تحذير'):t('Info','معلومة');}
function codeLabel(value:PurchaseGuardianIssue['code']):string{if(value==='missing-supplier')return t('Missing supplier','مورد مفقود');if(value==='unmatched-item')return t('Unmatched purchase item','صنف شراء غير مطابق');if(value==='zero-cost')return t('Zero unit cost','تكلفة وحدة صفر');if(value==='cost-currency-mismatch')return t('Cost currency mismatch','اختلاف عملة التكلفة');if(value==='abnormal-landed-cost')return t('Abnormal landed cost','تكلفة وصول غير معتادة');return t('Possible duplicate line','سطر مكرر محتمل');}
function openPurchase(number:string):void{window.dispatchEvent(new CustomEvent('lourex-global-search-open',{detail:{query:number,autoOpenUnique:true}}));}

export class PurchaseGuardianTool extends React.Component<{},State>{
  state:State={open:false,busy:false,reviews:[],error:''};
  private open=async()=>{this.setState({open:true,busy:true,error:''});try{const resumed=await resumeVaultSession();if(!resumed)throw new Error(t('Unlock LOUREX before reviewing purchase drafts.','افتح قفل LOUREX قبل مراجعة مسودات الشراء.'));this.setState({busy:false,reviews:reviewDraftPurchases(resumed.vault)});}catch(error){this.setState({busy:false,error:error instanceof Error?error.message:String(error)});}};
  private close=()=>this.setState({open:false,error:''});
  render():any{return <><Button icon="check" onClick={()=>void this.open()}>{t('Purchase Guardian','حارس المشتريات')}</Button><Modal open={this.state.open} title={t('Purchase Guardian — Before Posting','حارس المشتريات — قبل الترحيل')} size="lg" onClose={this.close}>{this.state.busy?<p role="status">{t('Reviewing purchase drafts with deterministic LOUREX checks…','مراجعة مسودات الشراء بفحوص LOUREX الحتمية…')}</p>:this.state.error?<div className="inline-error" role="alert">{this.state.error}</div>:<div><div className="product-import-mapping-note"><Icon name="lock"/><span>{t('Review-only. The Guardian never links products, changes costs or posts a purchase automatically. Landed-cost change thresholds are attention signals, not accounting rules.','للمراجعة فقط. لا يقوم الحارس بربط المنتجات أو تغيير التكاليف أو ترحيل شراء تلقائيًا. حدود تغير تكلفة الوصول هي إشارات انتباه وليست قواعد محاسبية.')}</span></div>{this.state.reviews.length?this.state.reviews.map(review=><article key={review.purchaseId} style={{padding:'12px 0'}}><header><strong>{review.purchaseNumber}</strong><small style={{display:'block'}}>{review.status==='clear'?t('Clear deterministic review','مراجعة حتمية سليمة'):`${review.counts.critical} ${t('critical','حرج')} · ${review.counts.warning} ${t('warning','تحذير')} · ${review.counts.info} ${t('info','معلومة')}`}</small></header>{review.issues.length?<ul>{review.issues.map((issue,index)=><li key={`${issue.code}-${issue.lineIndex}-${index}`}><strong>{severityLabel(issue.severity)} · {codeLabel(issue.code)}</strong>{issue.itemName?` · ${issue.itemName}`:''}<br/><small>{issue.detail}</small></li>)}</ul>:<p>{t('No unmatched-item or landed-cost attention signals were detected.','لم يتم اكتشاف إشارات أصناف غير مطابقة أو تكلفة وصول تحتاج انتباهًا.')}</p>}<Button variant={review.counts.critical?'primary':'default'} onClick={()=>{this.close();openPurchase(review.purchaseNumber);}}>{t('Review Purchase Draft','مراجعة مسودة الشراء')}</Button></article>):<p>{t('There are no purchase drafts to review before posting.','لا توجد مسودات شراء لمراجعتها قبل الترحيل.')}</p>}</div>}</Modal></>;}
}
