import type { AppSettings, AutoLockMinutes, CompanySettings } from '../types.js';
import { fileToDataUrl } from '../lib/files.js';
import { Button, ConfirmDialog, Field, Input, Modal, Select, Textarea, Toggle, Icon } from './UI.js';

interface Props {
  open:boolean; company:CompanySettings; appSettings:AppSettings; onClose:()=>void;
  onSaveCompany:(company:CompanySettings)=>Promise<void>; onSaveAppSettings:(settings:AppSettings)=>Promise<void>;
  onChangePin:(currentPin:string,newPin:string)=>Promise<void>; onLock:()=>void;
  onBackup:(pin:string)=>Promise<void>; onRestore:(file:File,pin:string)=>Promise<void>;
}
interface State { tab:'company'|'documents'|'security'|'backup'; company:CompanySettings; appSettings:AppSettings; busy:boolean; message:string; error:string; currentPin:string; newPin:string; confirmPin:string; backupPin:string; restorePin:string; restoreFile:File|null; confirmRestore:boolean; }

export class SettingsModal extends React.Component<Props,State> {
  constructor(props:Props){super(props);this.state={tab:'company',company:structuredClone(props.company),appSettings:structuredClone(props.appSettings),busy:false,message:'',error:'',currentPin:'',newPin:'',confirmPin:'',backupPin:'',restorePin:'',restoreFile:null,confirmRestore:false};}
  componentDidUpdate(prev:Props):void{if(this.props.open&&!prev.open)this.setState({company:structuredClone(this.props.company),appSettings:structuredClone(this.props.appSettings),message:'',error:'',currentPin:'',newPin:'',confirmPin:'',backupPin:'',restorePin:'',restoreFile:null,confirmRestore:false});}
  private setCompany=(key:keyof CompanySettings,value:any)=>this.setState({company:{...this.state.company,[key]:value}});
  private setBank=(key:keyof CompanySettings['bank'],value:string)=>this.setState({company:{...this.state.company,bank:{...this.state.company.bank,[key]:value}}});
  private upload=async(field:'logoDataUrl'|'signatureDataUrl'|'stampDataUrl',file?:File)=>{if(!file)return;try{const data=await fileToDataUrl(file);this.setCompany(field,data);}catch(e){this.setState({error:e instanceof Error?e.message:'Image upload failed.'});}};
  private saveCompany=async()=>{if(!this.state.company.nameEn.trim()){this.setState({error:'Company Name English is required.'});return;}this.setState({busy:true,error:'',message:''});try{await this.props.onSaveCompany(this.state.company);this.setState({busy:false,message:'Company settings saved.'});}catch(e){this.setState({busy:false,error:e instanceof Error?e.message:'Save failed.'});}};
  private saveDocuments=async()=>{this.setState({busy:true,error:'',message:''});try{await this.props.onSaveAppSettings(this.state.appSettings);this.setState({busy:false,message:'Document settings saved.'});}catch(e){this.setState({busy:false,error:e instanceof Error?e.message:'Save failed.'});}};
  private changePin=async()=>{if(!/^\d{4,12}$/.test(this.state.newPin)){this.setState({error:'New PIN must contain 4–12 digits.'});return;}if(this.state.newPin!==this.state.confirmPin){this.setState({error:'New PIN confirmation does not match.'});return;}this.setState({busy:true,error:'',message:''});try{await this.props.onChangePin(this.state.currentPin,this.state.newPin);this.setState({busy:false,message:'PIN changed and local data re-encrypted.',currentPin:'',newPin:'',confirmPin:''});}catch(e){this.setState({busy:false,error:e instanceof Error?e.message:'Unable to change PIN.'});}};
  private backup=async()=>{this.setState({busy:true,error:'',message:''});try{await this.props.onBackup(this.state.backupPin);this.setState({busy:false,message:'Encrypted backup created.',backupPin:''});}catch(e){this.setState({busy:false,error:e instanceof Error?e.message:'Backup failed.'});}};
  private restore=async()=>{if(!this.state.restoreFile){this.setState({error:'Choose a LOUREX backup file first.'});return;}this.setState({busy:true,error:'',message:''});try{await this.props.onRestore(this.state.restoreFile,this.state.restorePin);this.setState({busy:false,message:'Backup restored successfully.',restorePin:'',restoreFile:null,confirmRestore:false});}catch(e){this.setState({busy:false,error:e instanceof Error?e.message:'Restore failed.'});}};
  render():any{const c=this.state.company,s=this.state.appSettings;return <Modal open={this.props.open} title="Settings" size="xl" onClose={this.props.onClose}><div className="settings-layout"><nav className="settings-tabs">{([['company','Company'],['documents','Documents'],['security','Security'],['backup','Backup']] as const).map(([id,label])=><button key={id} className={this.state.tab===id?'active':''} onClick={()=>this.setState({tab:id,error:'',message:''})}>{label}</button>)}</nav><div className="settings-panel">
    {this.state.tab==='company'?<div><div className="settings-title"><div><p className="eyebrow">Company</p><h3>Company details</h3></div><Button variant="primary" disabled={this.state.busy} onClick={this.saveCompany}>Save</Button></div><div className="settings-section"><div className="form-grid two">
      <Field label="Company Name English"><Input value={c.nameEn} onChange={(e:any)=>this.setCompany('nameEn',e.target.value)}/></Field><Field label="Company Name Arabic"><Input dir="rtl" value={c.nameAr} onChange={(e:any)=>this.setCompany('nameAr',e.target.value)}/></Field>
      <Field label="Address English"><Input value={c.addressEn} onChange={(e:any)=>this.setCompany('addressEn',e.target.value)}/></Field><Field label="Address Arabic"><Input dir="rtl" value={c.addressAr} onChange={(e:any)=>this.setCompany('addressAr',e.target.value)}/></Field>
      <Field label="City"><Input value={c.city} onChange={(e:any)=>this.setCompany('city',e.target.value)}/></Field><Field label="Country"><Input value={c.country} onChange={(e:any)=>this.setCompany('country',e.target.value)}/></Field>
      <Field label="Phone"><Input value={c.phone} onChange={(e:any)=>this.setCompany('phone',e.target.value)}/></Field><Field label="Email"><Input value={c.email} onChange={(e:any)=>this.setCompany('email',e.target.value)}/></Field>
      <Field label="Website"><Input value={c.website} onChange={(e:any)=>this.setCompany('website',e.target.value)}/></Field><Field label="VAT Number"><Input value={c.vatNumber} onChange={(e:any)=>this.setCompany('vatNumber',e.target.value)}/></Field>
      <Field label="Tax Number"><Input value={c.taxNumber} onChange={(e:any)=>this.setCompany('taxNumber',e.target.value)}/></Field><Field label="Commercial Registration"><Input value={c.commercialRegistration} onChange={(e:any)=>this.setCompany('commercialRegistration',e.target.value)}/></Field>
    </div><div className="asset-settings"><label><span>Logo</span><div className="asset-preview"><img src={c.logoDataUrl||'./brand/lourex-logo.svg'} alt="Logo"/></div><input type="file" accept="image/png,image/webp,image/jpeg,image/svg+xml" onChange={(e:any)=>this.upload('logoDataUrl',e.target.files?.[0])}/></label><label><span>Signature</span><div className="asset-preview">{c.signatureDataUrl?<img src={c.signatureDataUrl} alt="Signature"/>:<Icon name="upload"/>}</div><input type="file" accept="image/png,image/webp,image/jpeg" onChange={(e:any)=>this.upload('signatureDataUrl',e.target.files?.[0])}/></label><label><span>Stamp</span><div className="asset-preview">{c.stampDataUrl?<img src={c.stampDataUrl} alt="Stamp"/>:<Icon name="upload"/>}</div><input type="file" accept="image/png,image/webp,image/jpeg" onChange={(e:any)=>this.upload('stampDataUrl',e.target.files?.[0])}/></label></div></div>
    <div className="settings-section"><h4>Bank details</h4><div className="form-grid two"><Field label="Bank Name"><Input value={c.bank.bankName} onChange={(e:any)=>this.setBank('bankName',e.target.value)}/></Field><Field label="Account Name"><Input value={c.bank.accountName} onChange={(e:any)=>this.setBank('accountName',e.target.value)}/></Field><Field label="IBAN"><Input value={c.bank.iban} onChange={(e:any)=>this.setBank('iban',e.target.value)}/></Field><Field label="SWIFT / BIC"><Input value={c.bank.swift} onChange={(e:any)=>this.setBank('swift',e.target.value)}/></Field><Field label="Bank Currency"><Input value={c.bank.currency} onChange={(e:any)=>this.setBank('currency',e.target.value)}/></Field></div></div>
    <div className="settings-section"><h4>Defaults</h4><div className="form-grid two"><Field label="Default Currency"><Input value={c.defaultCurrency} onChange={(e:any)=>this.setCompany('defaultCurrency',e.target.value.toUpperCase())}/></Field><Field label="Default Language"><Select value={c.defaultLanguage} onChange={(e:any)=>this.setCompany('defaultLanguage',e.target.value)}><option value="en">English</option><option value="ar">Arabic</option><option value="bilingual">Arabic + English</option></Select></Field><Field label="Default Payment Terms"><Input value={c.defaultPaymentTerms} onChange={(e:any)=>this.setCompany('defaultPaymentTerms',e.target.value)}/></Field><Field label="Default Incoterm"><Input value={c.defaultIncoterm} onChange={(e:any)=>this.setCompany('defaultIncoterm',e.target.value)}/></Field><Field label="Default Delivery Time"><Input value={c.defaultDeliveryTime} onChange={(e:any)=>this.setCompany('defaultDeliveryTime',e.target.value)}/></Field><Field label="Default Validity (days)"><Input type="number" min="0" value={String(c.defaultValidityDays)} onChange={(e:any)=>this.setCompany('defaultValidityDays',Math.max(0,Number(e.target.value)||0))}/></Field><Field label="Default Footer Text" className="span-2"><Input value={c.defaultFooterText} onChange={(e:any)=>this.setCompany('defaultFooterText',e.target.value)}/></Field><Field label="Default Notes" className="span-2"><Textarea rows="3" value={c.defaultNotes} onChange={(e:any)=>this.setCompany('defaultNotes',e.target.value)}/></Field></div></div></div>:null}

    {this.state.tab==='documents'?<div><div className="settings-title"><div><p className="eyebrow">Documents</p><h3>Numbering</h3></div><Button variant="primary" disabled={this.state.busy} onClick={this.saveDocuments}>Save</Button></div><div className="settings-section"><div className="form-grid two"><Field label="Proforma Prefix"><Input value={s.numbering.proformaPrefix} onChange={(e:any)=>this.setState({appSettings:{...s,numbering:{...s.numbering,proformaPrefix:e.target.value.toUpperCase().replace(/[^A-Z0-9]/g,'').slice(0,8)}}})}/></Field><Field label="Invoice Prefix"><Input value={s.numbering.invoicePrefix} onChange={(e:any)=>this.setState({appSettings:{...s,numbering:{...s.numbering,invoicePrefix:e.target.value.toUpperCase().replace(/[^A-Z0-9]/g,'').slice(0,8)}}})}/></Field></div><div className="numbering-preview"><span>{s.numbering.proformaPrefix || 'PI'}-YYYY-0001</span><span>{s.numbering.invoicePrefix || 'INV'}-YYYY-0001</span></div><p className="settings-note">Document sequences only move forward. Deleted numbers are never automatically reused.</p></div></div>:null}

    {this.state.tab==='security'?<div><div className="settings-title"><div><p className="eyebrow">Security</p><h3>Local access</h3></div></div><div className="settings-section"><h4>Auto Lock</h4><Field label="Lock after inactivity"><Select value={String(s.autoLockMinutes)} onChange={async(e:any)=>{const value=Number(e.target.value) as AutoLockMinutes;const next={...s,autoLockMinutes:value};this.setState({appSettings:next});await this.props.onSaveAppSettings(next);}}><option value="0">Never</option><option value="5">5 minutes</option><option value="15">15 minutes</option><option value="30">30 minutes</option></Select></Field><Button icon="lock" onClick={this.props.onLock}>Lock App</Button></div><div className="settings-section"><h4>Change PIN</h4><div className="form-grid one"><Field label="Current PIN"><Input inputMode="numeric" type="password" value={this.state.currentPin} onChange={(e:any)=>this.setState({currentPin:e.target.value.replace(/\D/g,'')})}/></Field><Field label="New PIN"><Input inputMode="numeric" type="password" value={this.state.newPin} onChange={(e:any)=>this.setState({newPin:e.target.value.replace(/\D/g,'')})}/></Field><Field label="Confirm New PIN"><Input inputMode="numeric" type="password" value={this.state.confirmPin} onChange={(e:any)=>this.setState({confirmPin:e.target.value.replace(/\D/g,'')})}/></Field></div><Button variant="primary" disabled={this.state.busy} onClick={this.changePin}>Change PIN</Button><p className="settings-note">Changing the PIN decrypts the current vault in memory and atomically re-encrypts it with a new salt and key.</p></div></div>:null}

    {this.state.tab==='backup'?<div><div className="settings-title"><div><p className="eyebrow">Data Safety</p><h3>Backup / Restore</h3></div></div><div className="backup-cards"><section className="backup-card"><span className="backup-icon"><Icon name="backup"/></span><h4>Backup Data</h4><p>Creates one encrypted .lourex-backup file containing company settings, customers, documents, numbering and preferences.</p><Field label="Current PIN"><Input inputMode="numeric" type="password" value={this.state.backupPin} onChange={(e:any)=>this.setState({backupPin:e.target.value.replace(/\D/g,'')})}/></Field><Button variant="primary" disabled={this.state.busy||!this.state.backupPin} onClick={this.backup}>Backup Data</Button></section><section className="backup-card danger-zone"><span className="backup-icon"><Icon name="restore"/></span><h4>Restore Backup</h4><p>Validated restore replaces the current encrypted local vault. Existing data is not merged.</p><label className="file-picker"><input type="file" accept=".lourex-backup,application/json" onChange={(e:any)=>this.setState({restoreFile:e.target.files?.[0]??null})}/><span>{this.state.restoreFile?.name||'Choose backup file'}</span></label><Field label="Backup PIN / Password"><Input inputMode="numeric" type="password" value={this.state.restorePin} onChange={(e:any)=>this.setState({restorePin:e.target.value.replace(/\D/g,'')})}/></Field><Button variant="danger" disabled={this.state.busy||!this.state.restoreFile||!this.state.restorePin} onClick={()=>this.setState({confirmRestore:true})}>Restore Data</Button></section></div></div>:null}
    {this.state.message?<div className="settings-message success">{this.state.message}</div>:null}{this.state.error?<div className="settings-message error">{this.state.error}</div>:null}
  </div></div><ConfirmDialog open={this.state.confirmRestore} title="Restore data?" message="This will replace the current local data. The backup file is validated before it is written." confirmLabel="Restore" onCancel={()=>this.setState({confirmRestore:false})} onConfirm={()=>{this.setState({confirmRestore:false});void this.restore();}}/></Modal>;}
}
