import type { CompanySettings, PurchaseRecord, Supplier, SupplierPaymentRecord } from '../types.js';
import { displayDate, todayIso } from '../lib/id.js';
import { formatMoney } from '../lib/money.js';
import { getUiLanguage, isArabic, t } from '../lib/i18n.js';
import { createSupplierPayment, postedOnOrBefore, purchasePayableSummary, supplierAccounts, supplierPayablesByCurrency, supplierStatement } from '../lib/payables.js';
import { ensurePayablesStyles } from '../lib/payables-style.js';
import { Button, Icon, Input, Modal, Select, Textarea } from './UI.js';

type PayablesFilter='open'|'overdue'|'all';
interface Props{
  suppliers:Supplier[];
  purchases:PurchaseRecord[];
  supplierPayments:SupplierPaymentRecord[];
  company:CompanySettings;
  onSaveSupplierPayment:(payment:SupplierPaymentRecord)=>Promise<void>;
  onDeleteSupplierPayment:(payment:SupplierPaymentRecord,reason:string)=>Promise<void>;
}
interface State{
  query:string;filter:PayablesFilter;statementSupplierId:string;paymentPurchaseId:string;
  draft:SupplierPaymentRecord|null;working:boolean;error:string;deletePayment:SupplierPaymentRecord|null;voidReason:string;
}

function supplierForPurchase(purchase:PurchaseRecord,suppliers:Supplier[]):Supplier|null{return suppliers.find(item=>item.id===purchase.supplierSnapshot?.sourceSupplierId)??null;}
function supplierIdForPurchase(purchase:PurchaseRecord):string{return purchase.supplierSnapshot?.sourceSupplierId||`legacy-purchase:${purchase.id}`;}
function supplierName(purchase:PurchaseRecord,suppliers:Supplier[]):string{
  const supplier=supplierForPurchase(purchase,suppliers),arabic=isArabic();
  return ((arabic?(supplier?.nameAr||supplier?.nameEn||purchase.supplierSnapshot?.nameAr||purchase.supplierSnapshot?.nameEn):(supplier?.nameEn||supplier?.nameAr||purchase.supplierSnapshot?.nameEn||purchase.supplierSnapshot?.nameAr))||t('Deleted supplier','مورد محذوف')).trim();
}
function accountName(supplier:Supplier|null,id:string):string{return supplier?((isArabic()?(supplier.nameAr||supplier.nameEn):(supplier.nameEn||supplier.nameAr)).trim()||t('Unnamed supplier','مورد بدون اسم')):id.startsWith('legacy-purchase:')?t('Deleted supplier','مورد محذوف'):id;}
function paymentMethodLabel(method:SupplierPaymentRecord['method']):string{return method==='bank-transfer'?t('Bank transfer','تحويل بنكي'):method==='cash'?t('Cash','نقدي'):method==='card'?t('Card','بطاقة'):method==='cheque'?t('Cheque','شيك'):t('Other','أخرى');}
function stateLabel(state:ReturnType<typeof purchasePayableSummary>['state']):string{return state==='paid'?t('Paid','مدفوع'):state==='partial'?t('Partially paid','مدفوع جزئيًا'):state==='overdue'?t('Overdue','متأخر'):state==='unpaid'?t('Unpaid','غير مدفوع'):state==='draft'?t('Draft commitment','التزام مسودة'):t('Reversed','معكوس');}

export class SupplierPayablesPage extends React.Component<Props,State>{
  state:State={query:'',filter:'open',statementSupplierId:'',paymentPurchaseId:'',draft:null,working:false,error:'',deletePayment:null,voidReason:''};
  constructor(props:Props){super(props);ensurePayablesStyles();}
  componentDidMount():void{window.addEventListener('lourex-supplier-payables-open',this.handleExternalOpen as EventListener);window.addEventListener('afterprint',this.afterPrint);}
  componentWillUnmount():void{window.removeEventListener('lourex-supplier-payables-open',this.handleExternalOpen as EventListener);window.removeEventListener('afterprint',this.afterPrint);document.body.classList.remove('printing-supplier-statement');}
  private afterPrint=()=>document.body.classList.remove('printing-supplier-statement');
  private handleExternalOpen=(event:Event)=>{const supplierId=(event as CustomEvent<{supplierId?:string}>).detail?.supplierId||'';if(supplierId)this.setState({query:'',filter:'all',statementSupplierId:supplierId,error:''});};
  private postedPurchases=()=>this.props.purchases.filter(purchase=>purchase.status==='posted'&&postedOnOrBefore(purchase,todayIso())).sort((a,b)=>a.dueDate.localeCompare(b.dueDate)||a.number.localeCompare(b.number));
  private openPayment=(purchase:PurchaseRecord)=>{
    try{const supplier=supplierForPurchase(purchase,this.props.suppliers);const draft=createSupplierPayment(purchase,supplier,this.props.supplierPayments);this.setState({paymentPurchaseId:purchase.id,draft,error:''});}
    catch(error){this.setState({error:error instanceof Error?error.message:String(error)});}
  };
  private closePayment=()=>{if(this.state.working)return;this.setState({paymentPurchaseId:'',draft:null,error:''});};
  private patchDraft=(patch:Partial<SupplierPaymentRecord>)=>this.setState(state=>({draft:state.draft?{...state.draft,...patch}:null} as Pick<State,'draft'>));
  private savePayment=async()=>{
    const draft=this.state.draft;if(!draft)return;
    this.setState({working:true,error:''});
    try{await this.props.onSaveSupplierPayment(draft);this.setState({working:false,paymentPurchaseId:'',draft:null,error:''});}
    catch(error){this.setState({working:false,error:error instanceof Error?error.message:String(error)});}
  };
  private deletePayment=async()=>{
    const payment=this.state.deletePayment,reason=this.state.voidReason.trim();if(!payment)return;if(!reason){this.setState({error:t('Enter a reason for cancelling this payment.','أدخل سبب إلغاء هذه الدفعة.')});return;}
    this.setState({working:true,error:''});
    try{await this.props.onDeleteSupplierPayment(payment,reason);this.setState({working:false,deletePayment:null,voidReason:'',error:''});}
    catch(error){this.setState({working:false,error:error instanceof Error?error.message:String(error)});}
  };
  private printStatement=()=>{document.body.classList.add('printing-supplier-statement');window.setTimeout(()=>window.print(),40);};
  private filteredPurchases():PurchaseRecord[]{
    const q=this.state.query.trim().toLowerCase();
    return this.postedPurchases().filter(purchase=>{
      const summary=purchasePayableSummary(purchase,this.props.supplierPayments);
      const haystack=[purchase.number,purchase.supplierSnapshot?.nameEn,purchase.supplierSnapshot?.nameAr,supplierName(purchase,this.props.suppliers),purchase.currency].filter(Boolean).join(' ').toLowerCase();
      if(q&&!haystack.includes(q))return false;
      if(this.state.filter==='overdue')return summary.state==='overdue';
      if(this.state.filter==='open')return summary.remaining!=='0.00';
      return true;
    });
  }
  private renderStatement():any{
    const supplierId=this.state.statementSupplierId;if(!supplierId)return null;
    const supplier=this.props.suppliers.find(item=>item.id===supplierId)??null;
    const fallbackPurchase=this.props.purchases.find(purchase=>supplierIdForPurchase(purchase)===supplierId);
    const displayName=supplier?accountName(supplier,supplierId):supplierName(fallbackPurchase??({supplierSnapshot:null} as PurchaseRecord),this.props.suppliers);
    const sections=supplierStatement(supplierId,this.props.purchases,this.props.supplierPayments);
    const companyName=((isArabic()?(this.props.company.nameAr||this.props.company.nameEn):(this.props.company.nameEn||this.props.company.nameAr))||'LOUREX').trim();
    const address=supplier?[supplier.address,supplier.city,supplier.country].filter(Boolean).join(', '):[fallbackPurchase?.supplierSnapshot?.address,fallbackPurchase?.supplierSnapshot?.city,fallbackPurchase?.supplierSnapshot?.country].filter(Boolean).join(', ');
    const email=supplier?.email||fallbackPurchase?.supplierSnapshot?.email||'';const phone=supplier?.phone||fallbackPurchase?.supplierSnapshot?.phone||'';
    return <Modal open={Boolean(supplierId)} title={t('Supplier Statement','كشف حساب المورد')} size="xl" onClose={()=>this.setState({statementSupplierId:''})} footer={<div className="ta-modal-actions"><Button onClick={()=>this.setState({statementSupplierId:''})}>{t('Close','إغلاق')}</Button><Button icon="printer" variant="primary" onClick={this.printStatement}>{t('Print / Save PDF','طباعة / حفظ PDF')}</Button></div>}>
      <div className="lx-supplier-statement">
        <header className="lx-supplier-statement-head"><div>{this.props.company.logoDataUrl?<img src={this.props.company.logoDataUrl} alt="" style={{maxHeight:44,maxWidth:140}}/>:null}<h2>{companyName}</h2><p>{t('Supplier statement generated from posted purchases and recorded supplier payments.','كشف المورد مبني على المشتريات المرحلة ومدفوعات المورد المسجلة.')}</p></div><div><small>{t('Statement date','تاريخ الكشف')}</small><strong>{displayDate(todayIso(),getUiLanguage())}</strong></div></header>
        <section><strong>{displayName}</strong>{address?<p>{address}</p>:null}{email||phone?<p>{[email,phone].filter(Boolean).join(' · ')}</p>:null}</section>
        {sections.length?sections.map(section=><section className="lx-supplier-statement-section" key={section.currency}>
          <div className="lx-supplier-statement-summary"><div><span>{t('Purchases','المشتريات')}</span><strong>{formatMoney(section.purchases,section.currency)}</strong></div><div><span>{t('Paid','المدفوع')}</span><strong>{formatMoney(section.paid,section.currency)}</strong></div><div><span>{t('Remaining','المتبقي')}</span><strong>{formatMoney(section.remaining,section.currency)}</strong></div><div><span>{t('Overdue','المتأخر')}</span><strong>{formatMoney(section.overdue,section.currency)}</strong></div></div>
          <div className="ta-table-wrap"><table className="ta-table"><thead><tr><th>{t('Date','التاريخ')}</th><th>{t('Reference','المرجع')}</th><th>{t('Type','النوع')}</th><th>{t('Debit','مدين')}</th><th>{t('Credit','دائن')}</th><th>{t('Balance','الرصيد')}</th></tr></thead><tbody>{section.entries.map((entry,index)=><tr key={`${entry.type}-${entry.reference}-${index}`}><td>{displayDate(entry.date,getUiLanguage())}</td><td><strong>{entry.reference}</strong>{entry.purchaseNumber!==entry.reference?<small>↳ {entry.purchaseNumber}</small>:null}</td><td>{entry.type==='purchase'?t('Purchase','شراء'):t('Payment','دفعة')}</td><td>{entry.debit!=='0.00'?formatMoney(entry.debit,section.currency):'—'}</td><td>{entry.credit!=='0.00'?formatMoney(entry.credit,section.currency):'—'}</td><td><strong>{formatMoney(entry.balance,section.currency)}</strong></td></tr>)}</tbody></table></div>
        </section>):<div className="lx-payables-empty">{t('No posted purchase activity for this supplier.','لا توجد حركة مشتريات مرحلة لهذا المورد.')}</div>}
        <p><small>{t('Currencies remain separate. LOUREX does not perform hidden FX conversion in this statement.','تبقى العملات منفصلة. لا يجري LOUREX أي تحويل عملات مخفي في هذا الكشف.')}</small></p>
      </div>
    </Modal>;
  }
  render():any{
    const currencies=supplierPayablesByCurrency(this.props.purchases,this.props.supplierPayments);
    const accounts=supplierAccounts(this.props.suppliers,this.props.purchases,this.props.supplierPayments);
    const rows=this.filteredPurchases();
    const paymentPurchase=this.props.purchases.find(purchase=>purchase.id===this.state.paymentPurchaseId)??null;
    const paymentSummary=paymentPurchase?purchasePayableSummary(paymentPurchase,this.props.supplierPayments):null;
    const recentPayments=[...this.props.supplierPayments].sort((a,b)=>(b.voidedAt?.slice(0,10)||b.date).localeCompare(a.voidedAt?.slice(0,10)||a.date)||(b.voidedAt||b.createdAt).localeCompare(a.voidedAt||a.createdAt)).slice(0,12);
    return <section className="ta-finance-page lx-payables">
      <header className="ta-page-header ta-finance-header"><div><span className="ta-page-kicker">{t('Finance','المالية')}</span><h1>{t('Supplier Payables','مستحقات الموردين')}</h1><p>{t('Track posted supplier liabilities, due dates, payments, aging and statements. Balances stay separated by currency with no automatic FX conversion.','تابع التزامات الموردين المرحلة وتواريخ الاستحقاق والمدفوعات والأعمار وكشوف الحساب. تبقى الأرصدة منفصلة حسب العملة دون تحويل تلقائي.')}</p></div><div className="ta-header-badges"><span><b>{accounts.filter(account=>account.openPurchases>0).length}</b>{t('Open suppliers','مورد مستحق')}</span><span className={accounts.some(account=>account.hasOverdue)?'is-danger':''}><b>{accounts.filter(account=>account.hasOverdue).length}</b>{t('Overdue','متأخر')}</span></div></header>
      {this.state.error?<div className="ta-settings-toast is-error" role="alert"><Icon name="alert"/><span>{this.state.error}</span></div>:null}
      {currencies.length?<section className="lx-payables-summary" aria-label={t('Supplier payables by currency','مستحقات الموردين حسب العملة')}>{currencies.map(row=><article key={row.currency} className={`lx-payables-card ${row.overduePurchases?'has-alert':''}`}><div className="lx-payables-card-head"><span>{row.currency}</span><span className={`lx-payables-status ${row.overduePurchases?'danger':'ok'}`}>{row.overduePurchases?`${row.overduePurchases} ${t('overdue','متأخرة')}`:t('Current','جاري')}</span></div><small>{t('Remaining payable','المبلغ المتبقي')}</small><strong className="lx-payables-balance">{formatMoney(row.remaining,row.currency)}</strong><div className="lx-payables-card-meta"><span>{t('Purchases','المشتريات')}<b>{formatMoney(row.purchases,row.currency)}</b></span><span>{t('Paid','المدفوع')}<b>{formatMoney(row.paid,row.currency)}</b></span><span>{t('Overdue','المتأخر')}<b>{formatMoney(row.overdue,row.currency)}</b></span><span>{t('Open purchases','مشتريات مفتوحة')}<b>{row.openPurchases}</b></span></div></article>)}</section>:<div className="lx-payables-empty"><Icon name="wallet"/><strong>{t('No posted supplier liabilities yet','لا توجد التزامات موردين مرحلة بعد')}</strong><span>{t('Post a purchase in Purchasing to create a payable.','رحّل عملية شراء من قسم المشتريات لإنشاء مستحق للمورد.')}</span></div>}
      {currencies.length?<section className="ta-panel"><header className="ta-panel-header"><div><span>{t('Aging','أعمار الذمم')}</span><h2>{t('Payables Aging','تحليل أعمار مستحقات الموردين')}</h2></div></header><div className="lx-payables-aging"><table className="ta-table"><thead><tr><th>{t('Currency','العملة')}</th><th>{t('Current','جاري')}</th><th>1–30</th><th>31–60</th><th>61–90</th><th>+90</th><th>{t('Remaining','المتبقي')}</th></tr></thead><tbody>{currencies.map(row=><tr key={row.currency}><td><strong>{row.currency}</strong></td><td>{formatMoney(row.aging.current,row.currency)}</td><td>{formatMoney(row.aging.days1to30,row.currency)}</td><td>{formatMoney(row.aging.days31to60,row.currency)}</td><td>{formatMoney(row.aging.days61to90,row.currency)}</td><td>{formatMoney(row.aging.days90plus,row.currency)}</td><td><strong>{formatMoney(row.remaining,row.currency)}</strong></td></tr>)}</tbody></table></div></section>:null}
      <section className="ta-panel lx-payables-register"><header className="ta-panel-header"><div><span>{t('Accounts payable','الذمم الدائنة')}</span><h2>{t('Supplier liabilities','التزامات الموردين')}</h2><p>{t('Record payments only against posted purchases so every balance remains traceable.','سجّل الدفعات فقط مقابل مشتريات مرحلة ليبقى كل رصيد قابلًا للتتبع.')}</p></div></header><div className="lx-payables-controls"><label className="lx-payables-search"><Icon name="search"/><Input aria-label={t('Search supplier payables','بحث مستحقات الموردين')} value={this.state.query} placeholder={t('Supplier or purchase number','المورد أو رقم الشراء')} onChange={(e:any)=>this.setState({query:String(e.target.value)})}/></label><Select aria-label={t('Filter payables','تصفية المستحقات')} value={this.state.filter} onChange={(e:any)=>this.setState({filter:e.target.value as PayablesFilter})}><option value="open">{t('Open only','المفتوحة فقط')}</option><option value="overdue">{t('Overdue only','المتأخرة فقط')}</option><option value="all">{t('All posted','جميع المرحلة')}</option></Select></div><div className="lx-payables-row is-head"><span>{t('Supplier / Purchase','المورد / الشراء')}</span><span>{t('Due','الاستحقاق')}</span><span>{t('Total','الإجمالي')}</span><span>{t('Paid','المدفوع')}</span><span>{t('Remaining','المتبقي')}</span><span>{t('Status','الحالة')}</span><span>{t('Action','الإجراء')}</span></div>{rows.length?rows.map(purchase=>{const summary=purchasePayableSummary(purchase,this.props.supplierPayments);const supplierId=supplierIdForPurchase(purchase);return <div className="lx-payables-row" key={purchase.id}><span className="lx-payables-name"><strong>{supplierName(purchase,this.props.suppliers)}</strong><small>{purchase.number} · {summary.currency}</small></span><span><strong>{displayDate(purchase.dueDate,getUiLanguage())}</strong><small>{summary.daysOverdue?`${summary.daysOverdue} ${t('days overdue','يوم تأخير')}`:t('On schedule','ضمن الموعد')}</small></span><span className="lx-payables-money">{formatMoney(summary.total,summary.currency)}</span><span className="lx-payables-money">{formatMoney(summary.paid,summary.currency)}</span><span className={`lx-payables-money ${summary.state==='overdue'?'is-danger':''}`}><strong>{formatMoney(summary.remaining,summary.currency)}</strong></span><span><span className={`lx-payables-status ${summary.state==='overdue'?'danger':summary.state==='paid'?'ok':''}`}>{stateLabel(summary.state)}</span></span><span className="lx-payables-actions">{summary.remaining!=='0.00'?<Button variant="primary" onClick={()=>this.openPayment(purchase)}>{t('Record payment','تسجيل دفعة')}</Button>:null}<Button onClick={()=>this.setState({statementSupplierId:supplierId})}>{t('Statement','الكشف')}</Button></span></div>;}):<div className="lx-payables-empty">{t('No supplier payables match this view.','لا توجد مستحقات موردين مطابقة لهذا العرض.')}</div>}</section>
      {recentPayments.length?<section className="ta-panel"><header className="ta-panel-header"><div><span>{t('Payment ledger','سجل المدفوعات')}</span><h2>{t('Recent supplier payments','أحدث مدفوعات الموردين')}</h2></div></header><div className="ta-table-wrap"><table className="ta-table"><thead><tr><th>{t('Date','التاريخ')}</th><th>{t('Supplier','المورد')}</th><th>{t('Purchase','الشراء')}</th><th>{t('Method','الطريقة')}</th><th>{t('Amount','المبلغ')}</th><th></th></tr></thead><tbody>{recentPayments.map(payment=><tr key={payment.id}><td>{displayDate(payment.date,getUiLanguage())}</td><td>{(isArabic()?(payment.supplierNameAr||payment.supplierNameEn):(payment.supplierNameEn||payment.supplierNameAr))||'—'}</td><td><strong>{payment.purchaseNumber}</strong>{payment.reference?<small>{payment.reference}</small>:null}</td><td>{paymentMethodLabel(payment.method)}</td><td><strong>{formatMoney(payment.amount,payment.currency)}</strong>{payment.voidedAt?<small>{t('Voided','ملغاة')} · {displayDate(payment.voidedAt.slice(0,10),getUiLanguage())}{payment.voidReason?` · ${payment.voidReason}`:''}</small>:null}</td><td>{payment.voidedAt?<span>{t('Audit record','سجل تدقيق')}</span>:<Button variant="danger" disabled={this.state.working} onClick={()=>this.setState({deletePayment:payment,voidReason:'',error:''})}>{t('Void','إلغاء')}</Button>}</td></tr>)}</tbody></table></div></section>:null}
      <Modal open={Boolean(paymentPurchase&&this.state.draft)} title={t('Record Supplier Payment','تسجيل دفعة مورد')} size="md" onClose={this.closePayment} footer={<div className="ta-modal-actions"><Button disabled={this.state.working} onClick={this.closePayment}>{t('Cancel','إلغاء')}</Button><Button variant="primary" disabled={this.state.working||!this.state.draft} onClick={this.savePayment}>{this.state.working?t('Saving…','جارٍ الحفظ…'):t('Save Payment','حفظ الدفعة')}</Button></div>}>{paymentPurchase&&this.state.draft&&paymentSummary?<div className="lx-payables-payment-form"><div className="lx-payables-payment-context"><span>{t('Purchase','الشراء')}<strong>{paymentPurchase.number}</strong></span><span>{t('Supplier','المورد')}<strong>{supplierName(paymentPurchase,this.props.suppliers)}</strong></span><span>{t('Remaining','المتبقي')}<strong>{formatMoney(paymentSummary.remaining,paymentSummary.currency)}</strong></span></div><div className="lx-payables-form-grid"><label>{t('Amount','المبلغ')}<Input inputMode="decimal" value={this.state.draft.amount} onChange={(e:any)=>this.patchDraft({amount:String(e.target.value)})}/></label><label>{t('Date','التاريخ')}<Input type="date" value={this.state.draft.date} onChange={(e:any)=>this.patchDraft({date:String(e.target.value)})}/></label><label>{t('Method','طريقة الدفع')}<Select value={this.state.draft.method} onChange={(e:any)=>this.patchDraft({method:e.target.value})}><option value="bank-transfer">{t('Bank transfer','تحويل بنكي')}</option><option value="cash">{t('Cash','نقدي')}</option><option value="card">{t('Card','بطاقة')}</option><option value="cheque">{t('Cheque','شيك')}</option><option value="other">{t('Other','أخرى')}</option></Select></label><label>{t('Reference','المرجع')}<Input value={this.state.draft.reference} onChange={(e:any)=>this.patchDraft({reference:String(e.target.value)})}/></label></div><label>{t('Notes','ملاحظات')}<Textarea rows={3} value={this.state.draft.notes} onChange={(e:any)=>this.patchDraft({notes:String(e.target.value)})}/></label><small>{t(`Currency is fixed to ${paymentSummary.currency}. Automatic FX conversion is disabled.`,`العملة مثبتة على ${paymentSummary.currency}. التحويل التلقائي للعملات معطل.`)}</small></div>:null}</Modal>
      {this.renderStatement()}
      <Modal open={Boolean(this.state.deletePayment)} title={t('Void supplier payment?','إلغاء دفعة المورد؟')} size="sm" onClose={()=>{if(!this.state.working)this.setState({deletePayment:null,voidReason:''});}} footer={<div className="ta-modal-actions"><Button disabled={this.state.working} onClick={()=>this.setState({deletePayment:null,voidReason:''})}>{t('Cancel','إلغاء')}</Button><Button variant="danger" disabled={this.state.working||!this.state.voidReason.trim()} onClick={this.deletePayment}>{this.state.working?t('Saving…','جارٍ الحفظ…'):t('Void Payment','إلغاء الدفعة')}</Button></div>}><div className="lx-payables-payment-form"><p>{t('The original payment stays in the audit history. If it is linked to Cash & Bank, void the treasury entry first.','ستبقى الدفعة الأصلية في سجل التدقيق. إذا كانت مرتبطة بالخزينة، ألغِ قيد الخزينة أولًا.')}</p><label>{t('Cancellation reason (required)','سبب الإلغاء (مطلوب)')}<Textarea rows={3} value={this.state.voidReason} onChange={(e:any)=>this.setState({voidReason:String(e.target.value)})}/></label></div></Modal>
    </section>;
  }
}
