import type { CompanySettings, LourexDocument } from '../types.js';
import { displayDate, todayIso } from '../lib/id.js';
import { formatMoney } from '../lib/money.js';
import { getUiLanguage, t } from '../lib/i18n.js';
import { outputVatReport, type TaxVatDocumentRow } from '../lib/tax-vat.js';
import { Button, Icon, Input, Select } from './UI.js';

type PeriodPreset='month'|'quarter'|'year'|'all';
interface Props{company:CompanySettings;documents:LourexDocument[];}
interface State{from:string;to:string;currency:string;preset:PeriodPreset;}

function startOfMonth(today:string):string{return `${today.slice(0,7)}-01`;}
function startOfQuarter(today:string):string{const year=today.slice(0,4),month=Number(today.slice(5,7)),start=Math.floor((month-1)/3)*3+1;return `${year}-${String(start).padStart(2,'0')}-01`;}
function companyName(company:CompanySettings):string{return (getUiLanguage()==='ar'?(company.nameAr||company.nameEn):(company.nameEn||company.nameAr)||'LOUREX').trim()||'LOUREX';}
const CSV_NUMBER=/^-?(?:\d+|\d*\.\d+)$/;
function csvCell(value:string|number):string{const text=String(value??''),probe=text.trimStart(),formulaRisk=/^[=+@]/.test(probe)||(probe.startsWith('-')&&!CSV_NUMBER.test(probe)),safe=formulaRisk?`'${text}`:text;return /[",\r\n]/.test(safe)?`"${safe.replace(/"/g,'""')}"`:safe;}
function rateLabel(rate:string):string{return `${rate}%`;}
function rowType(row:TaxVatDocumentRow):string{return row.creditNote?t('Credit Note','إشعار دائن'):t('Invoice','فاتورة');}

export class TaxVatCenter extends React.Component<Props,State>{
  state:State={from:`${todayIso().slice(0,4)}-01-01`,to:todayIso(),currency:'ALL',preset:'year'};
  componentDidMount():void{window.addEventListener('afterprint',this.afterPrint);}
  componentWillUnmount():void{window.removeEventListener('afterprint',this.afterPrint);document.body.classList.remove('printing-tax-vat-report');}
  private afterPrint=()=>document.body.classList.remove('printing-tax-vat-report');
  private setPreset=(preset:PeriodPreset)=>{const today=todayIso();if(preset==='month')this.setState({from:startOfMonth(today),to:today,preset});else if(preset==='quarter')this.setState({from:startOfQuarter(today),to:today,preset});else if(preset==='year')this.setState({from:`${today.slice(0,4)}-01-01`,to:today,preset});else this.setState({from:'',to:today,preset});};
  private print=()=>{document.body.classList.add('printing-tax-vat-report');window.setTimeout(()=>window.print(),40);};
  private exportCsv=(rows:TaxVatDocumentRow[])=>{const headers=[t('Date','التاريخ'),t('Type','النوع'),t('Document','المستند'),t('Customer','العميل'),t('Currency','العملة'),t('VAT Rate','نسبة الضريبة'),t('Taxable Amount','المبلغ الخاضع'),t('Output VAT','ضريبة المخرجات'),t('Grand Total','الإجمالي')];const lines=[headers,...rows.map(row=>[row.issueDate,rowType(row),row.number,row.customerName,row.currency,row.taxRate,row.taxableAmount,row.outputVat,row.grandTotal])].map(row=>row.map(csvCell).join(','));const blob=new Blob([`\uFEFF${lines.join('\r\n')}`],{type:'text/csv;charset=utf-8'}),url=URL.createObjectURL(blob),anchor=document.createElement('a');anchor.href=url;anchor.download=`LOUREX-Output-VAT-${this.state.from||'all'}-${this.state.to}.csv`;document.body.appendChild(anchor);anchor.click();anchor.remove();window.setTimeout(()=>URL.revokeObjectURL(url),500);};
  render():any{
    const report=outputVatReport(this.props.documents,this.state.from,this.state.to),currencies=report.currencies.map(row=>row.currency),selected=this.state.currency!=='ALL'&&currencies.includes(this.state.currency)?this.state.currency:'',visibleCurrencies=selected?report.currencies.filter(row=>row.currency===selected):report.currencies,visibleRows=selected?report.rows.filter(row=>row.currency===selected):report.rows,logo=this.props.company.logoDataUrl||'./brand/lourex-logo.svg';
    return <div className="lx-tax-center tax-vat-print">
      <header className="ta-page-header lx-tax-header"><div><span className="ta-page-kicker">{t('Reports & Insights','التقارير والرؤى')}</span><h1>{t('Tax / VAT Center','مركز الضريبة / VAT')}</h1><p>{t('Output VAT from active finalized sales invoices and linked credit notes. Every currency stays separate.','ضريبة المخرجات من فواتير المبيعات النهائية الفعالة والإشعارات الدائنة المرتبطة بها. تبقى كل عملة منفصلة.')}</p></div><div className="ta-page-actions"><Button icon="download" onClick={()=>this.exportCsv(visibleRows)}>{t('Export CSV','تصدير CSV')}</Button><Button icon="printer" variant="primary" onClick={this.print}>{t('Print / Save PDF','طباعة / حفظ PDF')}</Button></div></header>
      <section className="lx-tax-scope" role="note"><Icon name="alert"/><div><strong>{t('Output VAT only','ضريبة المخرجات فقط')}</strong><p>{t('Purchase VAT is not represented in the purchase accounting model yet, so LOUREX does not calculate or claim Input VAT in this center.','ضريبة المشتريات غير ممثلة بعد في نموذج محاسبة الشراء، لذلك لا يحسب LOUREX ولا يدّعي دعم ضريبة المدخلات في هذا المركز.')}</p></div></section>
      <section className="ta-report-filterbar lx-tax-filters" aria-label={t('Tax report filters','فلاتر التقرير الضريبي')}><div className="ta-report-presets" role="group" aria-label={t('Period presets','فترات جاهزة')}><button type="button" aria-pressed={this.state.preset==='month'} onClick={()=>this.setPreset('month')}>{t('This Month','هذا الشهر')}</button><button type="button" aria-pressed={this.state.preset==='quarter'} onClick={()=>this.setPreset('quarter')}>{t('This Quarter','هذا الربع')}</button><button type="button" aria-pressed={this.state.preset==='year'} onClick={()=>this.setPreset('year')}>{t('This Year','هذه السنة')}</button><button type="button" aria-pressed={this.state.preset==='all'} onClick={()=>this.setPreset('all')}>{t('All Time','كل الفترات')}</button></div><label className="ta-report-date"><span>{t('From','من')}</span><Input type="date" value={this.state.from} onChange={(e:any)=>this.setState({from:String(e.target.value),preset:'all'})}/></label><label className="ta-report-date"><span>{t('To','إلى')}</span><Input type="date" value={this.state.to} onChange={(e:any)=>this.setState({to:String(e.target.value),preset:'all'})}/></label><label className="ta-report-currency"><span>{t('Currency','العملة')}</span><Select value={selected||'ALL'} onChange={(e:any)=>this.setState({currency:String(e.target.value)})}><option value="ALL">{t('All currencies — separate','كل العملات — منفصلة')}</option>{currencies.map(currency=><option key={currency} value={currency}>{currency}</option>)}</Select></label></section>
      <div className="report-print-header lx-tax-print-header"><div className="report-print-brand"><img src={logo} alt={companyName(this.props.company)}/><div><strong>{companyName(this.props.company)}</strong><span>{t('Output VAT Report','تقرير ضريبة المخرجات')}</span></div></div><div><strong>{report.from?`${report.from} — ${report.to}`:t(`Through ${report.to}`,`حتى ${report.to}`)}</strong><span>{selected||t('Currencies shown separately','العملات معروضة بشكل منفصل')}</span></div></div>
      {visibleCurrencies.length?<section className="lx-tax-summary">{visibleCurrencies.map(row=><article key={row.currency} className="lx-tax-card"><header><span>{row.currency}</span><small>{row.documents} {t('invoices','فواتير')} · {row.creditNotes} {t('credits','دائن')}</small></header><small>{t('Net Output VAT','صافي ضريبة المخرجات')}</small><strong>{formatMoney(row.outputVat,row.currency)}</strong><div><span><small>{t('Taxable amount','المبلغ الخاضع')}</small><b>{formatMoney(row.taxableAmount,row.currency)}</b></span><span><small>{t('Invoice VAT','ضريبة الفواتير')}</small><b>{formatMoney(row.invoiceVat,row.currency)}</b></span><span><small>{t('Credit VAT','ضريبة الإشعارات')}</small><b>{formatMoney(row.creditVat,row.currency)}</b></span></div></article>)}</section>:<section className="ta-empty-card"><span><Icon name="invoice"/></span><div><strong>{t('No Output VAT activity in this period','لا توجد حركة ضريبة مخرجات ضمن هذه الفترة')}</strong><p>{t('Only tax-enabled active final invoices and valid linked credit notes are included.','يتم تضمين الفواتير النهائية الفعالة المفعّل عليها الضريبة والإشعارات الدائنة المرتبطة الصالحة فقط.')}</p></div></section>}
      {visibleCurrencies.length?<section className="ta-panel lx-tax-rates"><header className="ta-panel-header"><div><span>{t('Rate analysis','تحليل النسب')}</span><h2>{t('VAT by Rate','الضريبة حسب النسبة')}</h2><p>{t('No rates or currencies are blended together.','لا يتم دمج نسب أو عملات مختلفة معًا.')}</p></div></header><div className="ta-table-wrap"><table className="ta-table"><thead><tr><th>{t('Currency','العملة')}</th><th>{t('VAT Rate','نسبة الضريبة')}</th><th>{t('Taxable Amount','المبلغ الخاضع')}</th><th>{t('Output VAT','ضريبة المخرجات')}</th><th>{t('Documents','المستندات')}</th></tr></thead><tbody>{visibleCurrencies.flatMap(row=>row.rates).map(rate=><tr key={`${rate.currency}-${rate.taxRate}`}><td><strong>{rate.currency}</strong></td><td>{rateLabel(rate.taxRate)}</td><td>{formatMoney(rate.taxableAmount,rate.currency)}</td><td><strong>{formatMoney(rate.outputVat,rate.currency)}</strong></td><td>{rate.documents} {t('invoices','فواتير')}{rate.creditNotes?` · ${rate.creditNotes} ${t('credits','دائن')}`:''}</td></tr>)}</tbody></table></div></section>:null}
      <section className="ta-panel lx-tax-register"><header className="ta-panel-header"><div><span>{t('Audit register','سجل التدقيق')}</span><h2>{t('Output VAT Documents','مستندات ضريبة المخرجات')}</h2><p>{t('Credit notes are shown as negative values and reduce Output VAT in the same document currency.','تظهر الإشعارات الدائنة بقيم سالبة وتخفض ضريبة المخرجات ضمن نفس عملة المستند.')}</p></div></header><div className="ta-table-wrap"><table className="ta-table"><thead><tr><th>{t('Date','التاريخ')}</th><th>{t('Document','المستند')}</th><th>{t('Customer','العميل')}</th><th>{t('Currency','العملة')}</th><th>{t('Rate','النسبة')}</th><th>{t('Taxable','الخاضع')}</th><th>{t('Output VAT','ضريبة المخرجات')}</th><th>{t('Total','الإجمالي')}</th></tr></thead><tbody>{visibleRows.map(row=><tr key={row.documentId} className={row.creditNote?'is-credit-note':''}><td>{displayDate(row.issueDate,getUiLanguage())}</td><td><strong>{row.number}</strong><small>{rowType(row)}</small></td><td>{row.customerName||'—'}</td><td><b>{row.currency}</b></td><td>{rateLabel(row.taxRate)}</td><td>{formatMoney(row.taxableAmount,row.currency)}</td><td><strong>{formatMoney(row.outputVat,row.currency)}</strong></td><td>{formatMoney(row.grandTotal,row.currency)}</td></tr>)}</tbody></table></div>{!visibleRows.length?<div className="ta-panel-empty compact"><strong>{t('No tax-enabled sales documents match these filters.','لا توجد مستندات مبيعات مفعّل عليها الضريبة تطابق هذه الفلاتر.')}</strong></div>:null}</section>
      <footer className="report-print-footer">{t('LOUREX Output VAT report. Input VAT is intentionally excluded until Purchase VAT is represented correctly. Currencies are never converted automatically.','تقرير ضريبة المخرجات من LOUREX. ضريبة المدخلات مستبعدة عمدًا حتى يتم تمثيل ضريبة المشتريات بشكل صحيح. لا يتم تحويل العملات تلقائيًا.')}</footer>
    </div>;
  }
}
