import type { BankAccount, CompanySettings, ExpenseRecord, PaymentRecord, SupplierPaymentRecord, TreasuryLedgerRecord, TreasuryReconciliationRecord } from '../types.js';
import { createTreasuryEntry, createTreasuryReconciliation, treasuryProjection, treasuryTotals } from '../lib/treasury-ledger.js';
import { formatMoney } from '../lib/money.js';
import { displayDate } from '../lib/id.js';
import { getUiLanguage, t } from '../lib/i18n.js';
import { mutateVaultSafely } from '../storage/vault-mutation-bridge.js';
import { Button, Input, Select, Textarea } from './UI.js';

interface Props {company:CompanySettings;payments:PaymentRecord[];supplierPayments:SupplierPaymentRecord[];expenses:ExpenseRecord[];treasuryEntries:TreasuryLedgerRecord[];treasuryReconciliations:TreasuryReconciliationRecord[];}
function accounts(company:CompanySettings):BankAccount[]{return [{id:'primary',label:t('Primary bank','البنك الرئيسي'),...company.bank},...company.bankAccounts];}
function sourceLabel(source:string):string{return source==='collection'?t('Collection','تحصيل'):source==='supplier-payment'?t('Supplier payment','دفعة مورد'):source==='expense'?t('Expense','مصروف'):source==='deposit'?t('Deposit','إيداع'):source==='withdrawal'?t('Withdrawal','سحب'):t('Transfer','تحويل');}

export function TreasuryLedgerPage(props:Props):any{
  const bankAccounts=accounts(props.company),defaultAccount=companyDefaultAccount(props.company,bankAccounts);
  const [type,setType]=React.useState<TreasuryLedgerRecord['type']>('deposit'),[date,setDate]=React.useState(new Date().toISOString().slice(0,10)),[currency,setCurrency]=React.useState(props.company.defaultCurrency||'USD'),[amount,setAmount]=React.useState(''),[from,setFrom]=React.useState(defaultAccount),[to,setTo]=React.useState(defaultAccount),[reference,setReference]=React.useState(''),[notes,setNotes]=React.useState(''),[query,setQuery]=React.useState(''),[currencyFilter,setCurrencyFilter]=React.useState('ALL'),[busy,setBusy]=React.useState(false),[error,setError]=React.useState('');
  const rows=treasuryProjection(props.payments,props.supplierPayments,props.expenses,props.treasuryEntries,props.treasuryReconciliations,props.company.defaultCurrency);
  const currencies=Array.from(new Set(rows.map(row=>row.currency).concat(currency))).filter(Boolean).sort();const selected=currencyFilter==='ALL'?'':currencyFilter;
  const visible=rows.filter(row=>(!selected||row.currency===selected)&&(!query.trim()||[row.label,row.reference,row.source,row.amount].join(' ').toLowerCase().includes(query.trim().toLowerCase())));
  const summaryCurrencies=selected?[selected]:currencies;
  const save=async()=>{if(busy)return;setBusy(true);setError('');try{const entry={...createTreasuryEntry(type,currency),date,currency:currency.trim().toUpperCase(),amount:amount.trim(),fromAccountId:type==='deposit'?'':from,toAccountId:type==='withdrawal'?'':to,reference:reference.trim(),notes:notes.trim()};await mutateVaultSafely(vault=>({...vault,treasuryEntries:[...vault.treasuryEntries,entry]}));setAmount('');setReference('');setNotes('');}catch(e){setError(e instanceof Error?e.message:t('Unable to save treasury entry.','تعذر حفظ حركة الخزينة.'));}finally{setBusy(false);}};
  const remove=async(id:string)=>{if(busy)return;setBusy(true);try{await mutateVaultSafely(vault=>({...vault,treasuryEntries:vault.treasuryEntries.filter(item=>item.id!==id),treasuryReconciliations:vault.treasuryReconciliations.filter(item=>item.movementKey!==`treasury:${id}`)}));}catch(e){setError(e instanceof Error?e.message:t('Unable to delete treasury entry.','تعذر حذف حركة الخزينة.'));}finally{setBusy(false);}};
  const toggleReconciled=async(key:string,reconciled:boolean)=>{if(busy)return;setBusy(true);try{await mutateVaultSafely(vault=>({...vault,treasuryReconciliations:reconciled?vault.treasuryReconciliations.filter(item=>item.movementKey!==key):[...vault.treasuryReconciliations,createTreasuryReconciliation(key)]}));}catch(e){setError(e instanceof Error?e.message:t('Unable to update reconciliation.','تعذر تحديث المطابقة.'));}finally{setBusy(false);}};
  return <section className="ta-finance-page lx-treasury-ledger">
    <header className="ta-page-header"><div><span className="ta-page-kicker">{t('Cash & Bank','النقد والبنوك')}</span><h2>{t('Treasury Ledger','دفتر الخزينة')}</h2><p>{t('Collections, supplier payments and expenses remain canonical in their own ledgers. Add only deposits, withdrawals and transfers here.','تبقى التحصيلات ودفعات الموردين والمصروفات في سجلاتها الأصلية. أضف هنا فقط الإيداعات والسحوبات والتحويلات.')}</p></div></header>
    <section className="ta-report-kpi-grid">{summaryCurrencies.length?summaryCurrencies.map(code=>{const totals=treasuryTotals(rows,code);return <article className="ta-report-kpi" key={code}><header><span>{code}</span><small>{totals.reconciled} {t('reconciled','مطابق')}</small></header><div className="ta-report-kpi-primary"><div><span>{t('Inflows','الداخل')}</span><strong>{formatMoney(totals.inflow,code)}</strong></div><div><span>{t('Outflows','الخارج')}</span><strong>{formatMoney(totals.outflow,code)}</strong></div><div><span>{t('Movement net','صافي الحركة')}</span><strong>{formatMoney(totals.net,code)}</strong></div></div><p className="lx-finance-disclaimer">{t('Movement net is not a bank balance. No opening balance is invented.','صافي الحركة ليس رصيدًا بنكيًا. لا يتم اختراع رصيد افتتاحي.')}</p></article>}):<div className="ta-empty-card">{t('No treasury activity yet.','لا توجد حركة خزينة بعد.')}</div>}</section>
    <section className="ta-panel lx-treasury-entry"><header className="ta-panel-header"><div><span>{t('Manual ledger entry','حركة دفتر يدوية')}</span><h3>{t('Deposit / Withdrawal / Transfer','إيداع / سحب / تحويل')}</h3></div></header><div className="lx-form-grid"><label><span>{t('Type','النوع')}</span><Select value={type} onChange={(e:any)=>setType(e.target.value)}><option value="deposit">{t('Deposit','إيداع')}</option><option value="withdrawal">{t('Withdrawal','سحب')}</option><option value="transfer">{t('Transfer','تحويل')}</option></Select></label><label><span>{t('Date','التاريخ')}</span><Input type="date" value={date} onChange={(e:any)=>setDate(e.target.value)}/></label><label><span>{t('Currency','العملة')}</span><Input value={currency} maxLength={8} onChange={(e:any)=>setCurrency(String(e.target.value).toUpperCase())}/></label><label><span>{t('Amount','المبلغ')}</span><Input inputMode="decimal" value={amount} onChange={(e:any)=>setAmount(e.target.value)}/></label>{type!=='deposit'?<label><span>{t('From account','من الحساب')}</span><Select value={from} onChange={(e:any)=>setFrom(e.target.value)}>{bankAccounts.map(a=><option key={a.id} value={a.id}>{a.label||a.bankName||a.id}</option>)}</Select></label>:null}{type!=='withdrawal'?<label><span>{t('To account','إلى الحساب')}</span><Select value={to} onChange={(e:any)=>setTo(e.target.value)}>{bankAccounts.map(a=><option key={a.id} value={a.id}>{a.label||a.bankName||a.id}</option>)}</Select></label>:null}<label><span>{t('Reference','المرجع')}</span><Input value={reference} onChange={(e:any)=>setReference(e.target.value)}/></label><label className="lx-form-wide"><span>{t('Notes','ملاحظات')}</span><Textarea rows={2} value={notes} onChange={(e:any)=>setNotes(e.target.value)}/></label></div>{error?<p className="lifecycle-error" role="alert">{error}</p>:null}<div className="ta-page-actions"><Button variant="primary" icon="plus" disabled={busy} onClick={()=>void save()}>{t('Add ledger entry','إضافة حركة')}</Button></div></section>
    <section className="ta-panel"><header className="ta-panel-header"><div><span>{t('Reconciliation','المطابقة')}</span><h3>{t('Treasury movements','حركات الخزينة')}</h3></div><div className="ta-panel-status">{visible.length}</div></header><div className="ta-report-filterbar"><Input placeholder={t('Search movement…','بحث في الحركة…')} value={query} onChange={(e:any)=>setQuery(e.target.value)}/><Select value={currencyFilter} onChange={(e:any)=>setCurrencyFilter(e.target.value)}><option value="ALL">{t('All currencies','كل العملات')}</option>{currencies.map(code=><option key={code}>{code}</option>)}</Select></div><div className="ta-table-wrap"><table className="ta-table"><thead><tr><th>{t('Date','التاريخ')}</th><th>{t('Type','النوع')}</th><th>{t('Reference','المرجع')}</th><th>{t('Amount','المبلغ')}</th><th>{t('Status','الحالة')}</th><th>{t('Actions','الإجراءات')}</th></tr></thead><tbody>{visible.map(row=><tr key={row.key}><td>{displayDate(row.date,getUiLanguage())}</td><td>{sourceLabel(row.source)}</td><td><strong>{row.label}</strong><small>{row.reference||'—'}</small></td><td>{row.direction==='out'?'-':row.direction==='internal'?'↔':'+'}{formatMoney(row.amount,row.currency)}</td><td><span className={`lx-share-chip ${row.reconciled?'is-accepted':'is-active'}`}>{row.reconciled?t('Reconciled','مطابق'):t('Open','غير مطابق')}</span></td><td><div className="lx-row-actions"><Button disabled={busy} onClick={()=>void toggleReconciled(row.key,row.reconciled)}>{row.reconciled?t('Undo reconcile','إلغاء المطابقة'):t('Reconcile','مطابقة')}</Button>{row.key.startsWith('treasury:')?<Button variant="danger" disabled={busy} onClick={()=>void remove(row.id)}>{t('Delete','حذف')}</Button>:null}</div></td></tr>)}</tbody></table></div></section>
  </section>;
}
function companyDefaultAccount(company:CompanySettings,all:BankAccount[]):string{return all.some(account=>account.id===company.defaultBankAccountId)?company.defaultBankAccountId:(all[0]?.id||'primary');}
