from pathlib import Path

def text(path): return Path(path).read_text()
def write(path,value): Path(path).write_text(value)
def replace(path,old,new,count=1):
    value=text(path); found=value.count(old)
    if found!=count: raise SystemExit(f'{path}: expected {count}, found {found}: {old[:100]!r}')
    write(path,value.replace(old,new,count))

replace('src/types.ts',"export type DocumentEventType = 'created' | 'issued' | 'reissued' | 'revision-started' | 'revision-discarded' | 'voided' | 'credit-note-created' | 'payment-recorded' | 'payment-deleted' | 'converted';","export type DocumentEventType = 'created' | 'issued' | 'reissued' | 'revision-started' | 'revision-discarded' | 'voided' | 'credit-note-created' | 'payment-recorded' | 'payment-deleted' | 'converted' | 'audit';")
replace('src/types.ts',"  currency: string;\n}\n\nexport interface DocumentRevisionRecord {","  currency: string;\n  auditEntityType?: 'document'|'customer'|'supplier'|'product'|'purchase';\n  auditEntityId?: string;\n  auditEntityLabel?: string;\n  auditAction?: 'created'|'updated'|'deleted'|'posted'|'reversed';\n  auditActorKind?: 'user'|'system';\n  workspaceId?: string;\n}\n\nexport interface DocumentRevisionRecord {")
replace('src/lib/defaults.ts',"// v17 adds encrypted recurring workflow definitions and idempotent generated-draft history.\nexport const APP_SCHEMA_VERSION = 17;","// v17 adds encrypted recurring workflow definitions and idempotent generated-draft history.\n// v18 extends the existing encrypted document-event ledger with auditable entity context.\nexport const APP_SCHEMA_VERSION = 18;")
replace('src/storage/vault.ts',"const DOCUMENT_EVENT_TYPES = new Set(['created','issued','reissued','revision-started','revision-discarded','voided','credit-note-created','payment-recorded','payment-deleted','converted']);","const DOCUMENT_EVENT_TYPES = new Set(['created','issued','reissued','revision-started','revision-discarded','voided','credit-note-created','payment-recorded','payment-deleted','converted','audit']);")
replace('src/storage/vault.ts',"id:stringValue(event?.id),documentId:stringValue(event?.documentId),documentNumber:stringValue(event?.documentNumber),type:DOCUMENT_EVENT_TYPES.has(event?.type)?event.type:'created',at:stringValue(event?.at,nowIso()),note:stringValue(event?.note),relatedDocumentId:stringValue(event?.relatedDocumentId),relatedDocumentNumber:stringValue(event?.relatedDocumentNumber),amount:stringValue(event?.amount),currency:cleanCurrency(event?.currency,migrated.appSettings.smartDefaults.currency||'USD')","id:stringValue(event?.id),documentId:stringValue(event?.documentId),documentNumber:stringValue(event?.documentNumber),type:DOCUMENT_EVENT_TYPES.has(event?.type)?event.type:'created',at:stringValue(event?.at,nowIso()),note:stringValue(event?.note),relatedDocumentId:stringValue(event?.relatedDocumentId),relatedDocumentNumber:stringValue(event?.relatedDocumentNumber),amount:stringValue(event?.amount),currency:cleanCurrency(event?.currency,migrated.appSettings.smartDefaults.currency||'USD'),auditEntityType:['document','customer','supplier','product','purchase'].includes(String(event?.auditEntityType||''))?event.auditEntityType:undefined,auditEntityId:stringValue(event?.auditEntityId),auditEntityLabel:stringValue(event?.auditEntityLabel),auditAction:['created','updated','deleted','posted','reversed'].includes(String(event?.auditAction||''))?event.auditAction:undefined,auditActorKind:event?.auditActorKind==='system'?'system':event?.auditActorKind==='user'?'user':undefined,workspaceId:stringValue(event?.workspaceId)")

replace('src/app/index.tsx',"import { registerVaultMutationBridge } from '../storage/vault-mutation-bridge.js';","import { registerVaultMutationBridge } from '../storage/vault-mutation-bridge.js';\nimport { appendAuditEventsForVaultDiff } from '../lib/audit-diff.js';")
replace('src/app/index.tsx',"        const next=mutation(latest);\n        const encrypted=await saveVault(key,next);","        const intended=mutation(latest);\n        const next=appendAuditEventsForVaultDiff(latest,intended);\n        const encrypted=await saveVault(key,next);")

replace('src/components/Customer360LivePanel.tsx',"import { CustomerSharesPanel } from './CustomerSharesPanel.js';","import { CustomerSharesPanel } from './CustomerSharesPanel.js';\nimport { EntityAuditLivePanel } from './EntityAuditLivePanel.js';")
replace('src/components/Customer360LivePanel.tsx',"  return <><Customer360Panel snapshot={snapshot}/><CustomerSharesPanel customer={customer}/></>;","  return <><Customer360Panel snapshot={snapshot}/><CustomerSharesPanel customer={customer}/><EntityAuditLivePanel entityType=\"customer\" entityId={customer.id} title={t('Customer activity','نشاط العميل')}/></>;")
replace('src/components/Supplier360LivePanel.tsx',"import { Supplier360Panel } from './Relationship360Panels.js';","import { Supplier360Panel } from './Relationship360Panels.js';\nimport { EntityAuditLivePanel } from './EntityAuditLivePanel.js';")
replace('src/components/Supplier360LivePanel.tsx',"  return <Supplier360Panel snapshot={snapshot}/>;","  return <><Supplier360Panel snapshot={snapshot}/><EntityAuditLivePanel entityType=\"supplier\" entityId={supplier.id} title={t('Supplier activity','نشاط المورد')}/></>;")

replace('src/components/ProductLibraryWorkspace.tsx',"import { ProductImportModal } from './ProductImportModal.js';","import { ProductImportModal } from './ProductImportModal.js';\nimport { EntityAuditLivePanel } from './EntityAuditLivePanel.js';")
replace('src/components/ProductLibraryWorkspace.tsx',"              {this.state.error?<div className=\"ta-product-error\" role=\"alert\">{this.state.error}</div>:null}\n            </div>","              {this.state.error?<div className=\"ta-product-error\" role=\"alert\">{this.state.error}</div>:null}\n              {this.props.items.some(item=>item.id===edit.id)?<EntityAuditLivePanel entityType=\"product\" entityId={edit.id} title={t('Product activity','نشاط الصنف')}/>:null}\n            </div>")
replace('src/components/OperationsPage.tsx',"import { Supplier360LivePanel } from './Supplier360LivePanel.js';","import { Supplier360LivePanel } from './Supplier360LivePanel.js';\nimport { EntityAuditLivePanel } from './EntityAuditLivePanel.js';")
replace('src/components/OperationsPage.tsx',"</section></fieldset></div>\n      <div className=\"ta-purchase-totals\">","</section></fieldset>{this.props.purchases.some(item=>item.id===edit.id)?<EntityAuditLivePanel entityType=\"purchase\" entityId={edit.id} title={t('Purchase activity','نشاط الشراء')}/>:null}</div>\n      <div className=\"ta-purchase-totals\">")

replace('src/components/SettingsModal.tsx',"import type { AppSettings, CompanySettings } from '../types.js';","import type { AppSettings, CompanySettings, DocumentEventRecord } from '../types.js';")
replace('src/components/SettingsModal.tsx',"import { Button, ConfirmDialog, Field, Input, Modal, Select, Textarea, Icon } from './UI.js';","import { Button, ConfirmDialog, Field, Input, Modal, Select, Textarea, Icon } from './UI.js';\nimport { ActivityLogModal } from './ActivityLogModal.js';")
replace('src/components/SettingsModal.tsx',"  onBackup:(pin:string)=>Promise<void>; onRestore:(file:File,pin:string)=>Promise<void>;\n}","  onBackup:(pin:string)=>Promise<void>; onRestore:(file:File,pin:string)=>Promise<void>; documentEvents:DocumentEventRecord[];\n}")
replace('src/components/SettingsModal.tsx',"  tab:'company'|'commercial'|'documents'|'security'; company:CompanySettings;","  tab:'company'|'commercial'|'documents'|'data'|'security'; company:CompanySettings;")
replace('src/components/SettingsModal.tsx',"  stampOriginalDataUrl:string; stampRebuiltDataUrl:string; stampMode:AssetMode;\n}","  stampOriginalDataUrl:string; stampRebuiltDataUrl:string; stampMode:AssetMode; activityLogOpen:boolean;\n}")
replace('src/components/SettingsModal.tsx',"stampOriginalDataUrl:'',stampRebuiltDataUrl:'',stampMode:'original'};","stampOriginalDataUrl:'',stampRebuiltDataUrl:'',stampMode:'original',activityLogOpen:false};",2)
replace('src/components/SettingsModal.tsx',"if(tab==='company'||tab==='commercial'||tab==='documents'||tab==='security')this.selectSettingsTab(tab);","if(tab==='company'||tab==='commercial'||tab==='documents'||tab==='data'||tab==='security')this.selectSettingsTab(tab);")
p=Path('src/components/SettingsModal.tsx'); value=p.read_text(); marker='  private securitySettings(s:AppSettings,account:CloudUser|null):any{return <div className="ta-settings-page ta-security-page">'
if marker not in value: raise SystemExit('Settings security anchor missing')
value=value.replace(marker,"  private dataCenter():any{return <div className=\"ta-settings-page ta-data-center-page\">{this.pageHeader(t('Data Center','مركز البيانات'),t('Data & activity','البيانات والنشاط'),t('Backup, restore and the encrypted activity log live together here.','النسخ والاستعادة وسجل النشاط المشفر موجودة هنا.'))}{this.card(t('Activity Log','سجل النشاط'),t('Review audited workspace changes without creating a second event system.','راجع تغييرات مساحة العمل المدققة دون إنشاء نظام أحداث ثانٍ.'),<Button icon=\"history\" onClick={()=>this.setState({activityLogOpen:true})}>{t('Open Activity Log','فتح سجل النشاط')}</Button>)}</div>;}\n\n"+marker,1)
old="['documents',t('Documents','المستندات'),'file',t('Output and numbering','الإخراج والترقيم')],['security',t('Security','الأمان'),'lock',t('PIN and recovery','PIN والاستعادة')]] as const)"; new="['documents',t('Documents','المستندات'),'file',t('Output and numbering','الإخراج والترقيم')],['data',t('Data Center','مركز البيانات'),'database',t('Backup and activity','النسخ والنشاط')],['security',t('Security','الأمان'),'lock',t('PIN and recovery','PIN والاستعادة')]] as const)"
if old not in value: raise SystemExit('Settings tabs anchor missing')
value=value.replace(old,new,1).replace("{!accountScope&&this.state.tab==='documents'?this.documentSettings(c,s):null}\n          {!accountScope&&this.state.tab==='security'?this.securitySettings(s,account):null}","{!accountScope&&this.state.tab==='documents'?this.documentSettings(c,s):null}\n          {!accountScope&&this.state.tab==='data'?this.dataCenter():null}\n          {!accountScope&&this.state.tab==='security'?this.securitySettings(s,account):null}",1).replace("      <ConfirmDialog open={this.state.confirmCloudRestore}","      <ActivityLogModal open={this.state.activityLogOpen} events={this.props.documentEvents} onClose={()=>this.setState({activityLogOpen:false})}/>\n      <ConfirmDialog open={this.state.confirmCloudRestore}",1); p.write_text(value)

p=Path('src/app/App.tsx'); value=p.read_text(); needle='<SettingsModal open={this.state.settingsOpen} company={vault.company} appSettings={vault.appSettings}'
if needle not in value: raise SystemExit('SettingsModal app anchor missing')
p.write_text(value.replace(needle,needle+' documentEvents={vault.documentEvents}',1))
p=Path('index.html'); value=p.read_text()
if 'audit-trail-batch13.css' not in value:
    anchor='  <link rel="stylesheet" href="./styles/tailadmin-reliability-bridge-v320.css?v=320-2" data-lourex-tailadmin-reliability-v320="true" />'
    if anchor not in value: raise SystemExit('index reliability anchor missing')
    value=value.replace(anchor,'  <link rel="stylesheet" href="./styles/audit-trail-batch13.css?v=465-1" data-lourex-audit-trail-batch13="true" />\n'+anchor,1)
p.write_text(value)
