from pathlib import Path
p=Path('src/components/ReportsPage.tsx');s=p.read_text()
def rep(old,new):
 global s
 if old not in s: raise SystemExit(f'missing ReportsPage anchor: {old[:100]}')
 s=s.replace(old,new,1)
rep("import type { CompanySettings, Customer, LourexDocument, PaymentRecord } from '../types.js';","import type { CompanySettings, Customer, LourexDocument, PaymentRecord, PurchaseRecord, SavedItem, Supplier } from '../types.js';")
rep("import { TaxVatCenter } from './TaxVatCenter.js';","import { TaxVatCenter } from './TaxVatCenter.js';\nimport { ProfitabilityReports } from './ProfitabilityReports.js';")
rep("interface Props{company:CompanySettings;customers:Customer[];documents:LourexDocument[];payments:PaymentRecord[];}","interface Props{company:CompanySettings;customers:Customer[];documents:LourexDocument[];payments:PaymentRecord[];suppliers:Supplier[];purchases:PurchaseRecord[];items:SavedItem[];}")
rep("interface State{view:'performance'|'tax';from:string;to:string;currency:string;query:string;preset:PeriodPreset|null;}","interface State{view:'performance'|'profitability'|'tax';from:string;to:string;currency:string;query:string;preset:PeriodPreset|null;}")
old="    if(this.state.view==='tax')return <div className=\"ta-reports-shell\"><nav className=\"ta-report-workspace-tabs\" role=\"tablist\" aria-label={t('Report sections','أقسام التقارير')}><button type=\"button\" role=\"tab\" aria-selected={false} onClick={()=>this.setState({view:'performance'})}>{t('Performance','الأداء')}</button><button type=\"button\" role=\"tab\" aria-selected={true} className=\"is-active\">{t('Tax / VAT','الضريبة / VAT')}</button></nav><TaxVatCenter company={this.props.company} documents={this.props.documents}/></div>;"
new="    if(this.state.view==='tax')return <div className=\"ta-reports-shell\"><nav className=\"ta-report-workspace-tabs\" role=\"tablist\" aria-label={t('Report sections','أقسام التقارير')}><button type=\"button\" role=\"tab\" aria-selected={false} onClick={()=>this.setState({view:'performance'})}>{t('Performance','الأداء')}</button><button type=\"button\" role=\"tab\" aria-selected={false} onClick={()=>this.setState({view:'profitability'})}>{t('Profitability','الربحية')}</button><button type=\"button\" role=\"tab\" aria-selected={true} className=\"is-active\">{t('Tax / VAT','الضريبة / VAT')}</button></nav><TaxVatCenter company={this.props.company} documents={this.props.documents}/></div>;\n    if(this.state.view==='profitability')return <div className=\"ta-reports-shell\"><nav className=\"ta-report-workspace-tabs\" role=\"tablist\" aria-label={t('Report sections','أقسام التقارير')}><button type=\"button\" role=\"tab\" aria-selected={false} onClick={()=>this.setState({view:'performance'})}>{t('Performance','الأداء')}</button><button type=\"button\" role=\"tab\" aria-selected={true} className=\"is-active\">{t('Profitability','الربحية')}</button><button type=\"button\" role=\"tab\" aria-selected={false} onClick={()=>this.setState({view:'tax'})}>{t('Tax / VAT','الضريبة / VAT')}</button></nav><ProfitabilityReports customers={this.props.customers} documents={this.props.documents} payments={this.props.payments} suppliers={this.props.suppliers} purchases={this.props.purchases} items={this.props.items}/></div>;"
rep(old,new)
rep("return <div className=\"ta-reports-shell\"><nav className=\"ta-report-workspace-tabs\" role=\"tablist\" aria-label={t('Report sections','أقسام التقارير')}><button type=\"button\" role=\"tab\" aria-selected={true} className=\"is-active\">{t('Performance','الأداء')}</button><button type=\"button\" role=\"tab\" aria-selected={false} onClick={()=>this.setState({view:'tax'})}>{t('Tax / VAT','الضريبة / VAT')}</button></nav>","return <div className=\"ta-reports-shell\"><nav className=\"ta-report-workspace-tabs\" role=\"tablist\" aria-label={t('Report sections','أقسام التقارير')}><button type=\"button\" role=\"tab\" aria-selected={true} className=\"is-active\">{t('Performance','الأداء')}</button><button type=\"button\" role=\"tab\" aria-selected={false} onClick={()=>this.setState({view:'profitability'})}>{t('Profitability','الربحية')}</button><button type=\"button\" role=\"tab\" aria-selected={false} onClick={()=>this.setState({view:'tax'})}>{t('Tax / VAT','الضريبة / VAT')}</button></nav>")
p.write_text(s);print('reports wiring applied')
