from pathlib import Path

# Export lifecycle and filenames: company drafts stay editable; POs use supplier identity.
p=Path('src/app/App.tsx'); s=p.read_text()
old="""  private requestPrint=async(doc:LourexDocument,mode:'print'|'pdf'|'share'):Promise<void>=>{try{const errors=validateDocument(doc);if(Object.keys(errors).length)throw new Error(t('Complete the required document fields before printing or sharing.','أكمل الحقول المطلوبة قبل الطباعة أو المشاركة.'));const vault=this.requireVault();if(vault.documents.some(d=>d.id!==doc.id&&d.number.trim().toLowerCase()===doc.number.trim().toLowerCase()))throw new Error(t('Document number already exists.','رقم المستند مستخدم بالفعل.'));let target:LourexDocument;const existing=vault.documents.find(d=>d.id===doc.id);if(doc.status==='final'&&existing?.status==='final')target=structuredClone(doc);else{target={...structuredClone(doc),status:'final',updatedAt:new Date().toISOString()};await this.saveDocument(target,false);target=structuredClone(this.requireVault().documents.find(saved=>saved.id===target.id)??target);}const customer=target.customerSnapshot?.companyNameEn||target.customerSnapshot?.companyNameAr||'Customer';const prefix=`LOUREX-${safeFilename(target.number)}-${safeFilename(customer)}`;document.title=prefix;await new Promise<void>((resolve,reject)=>this.setState({printDoc:target},()=>{document.body.classList.add('printing');void this.launchPrint().then(resolve,reject);}));}catch(e){const message=e instanceof Error?e.message:t('Unable to prepare document.','تعذر تجهيز المستند.');try{(window as any).__LOUREX_OUTPUT_ERROR__?.(message);}catch{}this.showToast(message,'error');throw e;}};"""
new="""  private requestPrint=async(doc:LourexDocument,mode:'print'|'pdf'|'share'):Promise<void>=>{try{const errors=validateDocument(doc);if(Object.keys(errors).length)throw new Error(t('Complete the required document fields before printing or sharing.','أكمل الحقول المطلوبة قبل الطباعة أو المشاركة.'));const vault=this.requireVault();if(vault.documents.some(d=>d.id!==doc.id&&d.number.trim().toLowerCase()===doc.number.trim().toLowerCase()))throw new Error(t('Document number already exists.','رقم المستند مستخدم بالفعل.'));let target:LourexDocument;const existing=vault.documents.find(d=>d.id===doc.id);if(doc.kind==='draft'){target=structuredClone(doc);}else if(doc.status==='final'&&existing?.status==='final')target=structuredClone(doc);else{target={...structuredClone(doc),status:'final',updatedAt:new Date().toISOString()};await this.saveDocument(target,false);target=structuredClone(this.requireVault().documents.find(saved=>saved.id===target.id)??target);}const party=target.kind==='purchase-order'?(target.supplierSnapshot?.nameEn||target.supplierSnapshot?.nameAr||t('Supplier','المورد')):target.kind==='draft'?(target.letter?.subject||target.letter?.recipient||t('Company Document','مستند شركة')):(target.customerSnapshot?.companyNameEn||target.customerSnapshot?.companyNameAr||t('Customer','العميل'));const prefix=`LOUREX-${safeFilename(target.number)}-${safeFilename(party)}`;document.title=prefix;await new Promise<void>((resolve,reject)=>this.setState({printDoc:target},()=>{document.body.classList.add('printing');void this.launchPrint().then(resolve,reject);}));}catch(e){const message=e instanceof Error?e.message:t('Unable to prepare document.','تعذر تجهيز المستند.');try{(window as any).__LOUREX_OUTPUT_ERROR__?.(message);}catch{}this.showToast(message,'error');throw e;}};"""
if old not in s: raise SystemExit('requestPrint anchor missing')
p.write_text(s.replace(old,new,1))

# Attachments: whitelist safe image formats and verify file magic instead of trusting MIME/name.
p=Path('src/components/DocumentAttachmentsSection.tsx'); s=p.read_text()
s=s.replace("const IMAGE_EXTENSION=/\\.(png|jpe?g|webp|heic|heif)$/i;","const IMAGE_EXTENSION=/\\.(png|jpe?g|webp|gif|heic|heif)$/i;")
old="""function attachmentKind(file:File):AttachmentKind|null{\n  const mime=(file.type||'').trim().toLowerCase();\n  if(mime==='application/pdf')return'pdf';\n  if(mime.startsWith('image/'))return'image';\n  if(!mime||mime==='application/octet-stream'){\n    if(PDF_EXTENSION.test(file.name))return'pdf';\n    if(IMAGE_EXTENSION.test(file.name))return'image';\n  }\n  return null;\n}"""
new="""function attachmentKind(file:File):AttachmentKind|null{\n  const mime=(file.type||'').trim().toLowerCase();\n  const safeImages=new Set(['image/png','image/jpeg','image/webp','image/gif','image/heic','image/heif']);\n  if(mime==='application/pdf')return'pdf';\n  if(safeImages.has(mime))return'image';\n  if(!mime||mime==='application/octet-stream'){\n    if(PDF_EXTENSION.test(file.name))return'pdf';\n    if(IMAGE_EXTENSION.test(file.name))return'image';\n  }\n  return null;\n}\nfunction ascii(bytes:Uint8Array,start:number,length:number):string{return String.fromCharCode(...bytes.slice(start,start+length));}\nasync function genuineAttachment(file:File,kind:AttachmentKind):Promise<boolean>{\n  const bytes=new Uint8Array(await file.slice(0,32).arrayBuffer());\n  if(kind==='pdf')return bytes.length>=5&&ascii(bytes,0,5)==='%PDF-';\n  if(bytes.length>=8&&bytes[0]===0x89&&ascii(bytes,1,3)==='PNG'&&bytes[4]===0x0d&&bytes[5]===0x0a&&bytes[6]===0x1a&&bytes[7]===0x0a)return true;\n  if(bytes.length>=3&&bytes[0]===0xff&&bytes[1]===0xd8&&bytes[2]===0xff)return true;\n  if(bytes.length>=12&&ascii(bytes,0,4)==='RIFF'&&ascii(bytes,8,4)==='WEBP')return true;\n  if(bytes.length>=6&&(ascii(bytes,0,6)==='GIF87a'||ascii(bytes,0,6)==='GIF89a'))return true;\n  if(bytes.length>=12&&ascii(bytes,4,4)==='ftyp'){const brand=ascii(bytes,8,4).toLowerCase();if(['heic','heix','hevc','hevx','heim','heis','mif1','msf1'].includes(brand))return true;}\n  return false;\n}"""
if old not in s: raise SystemExit('attachmentKind anchor missing')
s=s.replace(old,new,1)
s=s.replace("if(lower.endsWith('.webp'))return'image/webp';","if(lower.endsWith('.webp'))return'image/webp';\n  if(lower.endsWith('.gif'))return'image/gif';",1)
old="""    for(const file of files){if(!attachmentKind(file)){this.setState({error:t('Only genuine PDF and image attachments are supported.','المرفقات المدعومة هي ملفات PDF والصور الفعلية فقط.')});input.value='';return;}if(file.size>MAX_FILE_BYTES){this.setState({error:t('Each attachment must be 5 MB or smaller.','يجب ألا يتجاوز حجم كل مرفق 5 ميغابايت.')});input.value='';return;}}"""
new="""    for(const file of files){const kind=attachmentKind(file);if(!kind||!await genuineAttachment(file,kind)){this.setState({error:t('Only genuine PDF, PNG, JPEG, WebP, GIF, HEIC and HEIF files are supported.','تُقبل فقط ملفات PDF وPNG وJPEG وWebP وGIF وHEIC وHEIF الأصلية.')});input.value='';return;}if(file.size>MAX_FILE_BYTES){this.setState({error:t('Each attachment must be 5 MB or smaller.','يجب ألا يتجاوز حجم كل مرفق 5 ميغابايت.')});input.value='';return;}}"""
if old not in s: raise SystemExit('attachment validation loop missing')
s=s.replace(old,new,1)
old="""  state:State={busy:false,error:'',preview:null};private input:HTMLInputElement|null=null;"""
new="""  state:State={busy:false,error:'',preview:null};private input:HTMLInputElement|null=null;\n  componentDidMount():void{document.addEventListener('keydown',this.handleKeyDown);}\n  componentWillUnmount():void{document.removeEventListener('keydown',this.handleKeyDown);}\n  private handleKeyDown=(event:KeyboardEvent)=>{if(event.key==='Escape'&&this.state.preview){event.preventDefault();this.closePreview();}};"""
if old not in s: raise SystemExit('attachment state anchor missing')
s=s.replace(old,new,1)
s=s.replace('accept="image/*,application/pdf,.pdf"','accept="image/png,image/jpeg,image/webp,image/gif,image/heic,image/heif,application/pdf,.pdf,.png,.jpg,.jpeg,.webp,.gif,.heic,.heif"',1)
p.write_text(s)

print('v311 batch 4 applied')
