import { getRecord, putRecord } from './db.js';

export type AssistantTaskScope='business'|'personal';
export interface AssistantTaskRecord{id:string;scope:AssistantTaskScope;workspaceId:string;branchId:string;title:string;notes:string;dueAt:string;relatedEntityType:string;relatedEntityId:string;status:'open'|'done';createdAt:string;updatedAt:string;}
interface AssistantTaskState{version:1;tasks:AssistantTaskRecord[];updatedAt:string;}
interface EncryptedTaskRecord{id:'assistant-tasks';version:1;iv:string;cipher:string;updatedAt:string;}
const RECORD_ID='assistant-tasks' as const,MAX_TASKS=200;
function safe(value:unknown,max:number):string{return String(value??'').normalize('NFKC').replace(/[\u0000-\u001f\u007f]/g,' ').replace(/\s+/g,' ').trim().slice(0,max);}
function now():string{return new Date().toISOString();}
function id():string{return`ai-task-${Date.now().toString(36)}-${Math.random().toString(36).slice(2,9)}`;}
function bytesToB64(bytes:Uint8Array):string{let binary='';for(let i=0;i<bytes.length;i+=0x8000)binary+=String.fromCharCode(...bytes.subarray(i,Math.min(i+0x8000,bytes.length)));return btoa(binary);}
function b64(value:string):ArrayBuffer{const binary=atob(value),bytes=new Uint8Array(binary.length);for(let i=0;i<binary.length;i++)bytes[i]=binary.charCodeAt(i);return bytes.buffer.slice(bytes.byteOffset,bytes.byteOffset+bytes.byteLength) as ArrayBuffer;}
function empty():AssistantTaskState{return{version:1,tasks:[],updatedAt:now()};}
function normalizeTask(value:any):AssistantTaskRecord|null{if(!value||typeof value!=='object')return null;const taskId=safe(value.id,120),scope=value.scope==='personal'?'personal':value.scope==='business'?'business':null,title=safe(value.title,180);if(!taskId||!scope||!title)return null;const createdAt=safe(value.createdAt,40)||now();return{id:taskId,scope,workspaceId:scope==='business'?safe(value.workspaceId,120):'',branchId:scope==='business'?safe(value.branchId,120):'',title,notes:safe(value.notes,1000),dueAt:safe(value.dueAt,40),relatedEntityType:safe(value.relatedEntityType,40),relatedEntityId:safe(value.relatedEntityId,120),status:value.status==='done'?'done':'open',createdAt,updatedAt:safe(value.updatedAt,40)||createdAt};}
export function normalizeAssistantTasks(value:any):AssistantTaskState{const tasks=Array.isArray(value?.tasks)?value.tasks.map(normalizeTask).filter((row:AssistantTaskRecord|null):row is AssistantTaskRecord=>Boolean(row)).sort((a,b)=>b.updatedAt.localeCompare(a.updatedAt)).slice(0,MAX_TASKS):[];return{version:1,tasks,updatedAt:safe(value?.updatedAt,40)||now()};}
async function encrypt(key:CryptoKey,state:AssistantTaskState):Promise<EncryptedTaskRecord>{const iv=crypto.getRandomValues(new Uint8Array(12)),plain=new TextEncoder().encode(JSON.stringify(normalizeAssistantTasks(state))),cipher=new Uint8Array(await crypto.subtle.encrypt({name:'AES-GCM',iv},key,plain));return{id:RECORD_ID,version:1,iv:bytesToB64(iv),cipher:bytesToB64(cipher),updatedAt:now()};}
async function decrypt(key:CryptoKey,record:EncryptedTaskRecord):Promise<AssistantTaskState>{if(record.version!==1||!record.iv||!record.cipher)throw new Error('Unsupported assistant task format.');const plain=await crypto.subtle.decrypt({name:'AES-GCM',iv:b64(record.iv)},key,b64(record.cipher));return normalizeAssistantTasks(JSON.parse(new TextDecoder().decode(plain)));}
export async function loadAssistantTasks(key:CryptoKey):Promise<AssistantTaskState>{const row=await getRecord<any>(RECORD_ID as any) as EncryptedTaskRecord|null;if(!row)return empty();try{return await decrypt(key,row);}catch{throw new Error('LOUREX assistant tasks could not be decrypted for this account.');}}
export async function createAssistantTask(key:CryptoKey,input:{scope:AssistantTaskScope;workspaceId?:string;branchId?:string;title:string;notes?:string;dueAt?:string;relatedEntityType?:string;relatedEntityId?:string;}):Promise<AssistantTaskRecord>{const title=safe(input.title,180);if(!title)throw new Error('Task title is required.');const timestamp=now(),task:AssistantTaskRecord={id:id(),scope:input.scope,workspaceId:input.scope==='business'?safe(input.workspaceId,120):'',branchId:input.scope==='business'?safe(input.branchId,120):'',title,notes:safe(input.notes,1000),dueAt:safe(input.dueAt,40),relatedEntityType:safe(input.relatedEntityType,40),relatedEntityId:safe(input.relatedEntityId,120),status:'open',createdAt:timestamp,updatedAt:timestamp};const state=await loadAssistantTasks(key),next={version:1 as const,tasks:[task,...state.tasks].slice(0,MAX_TASKS),updatedAt:timestamp};await putRecord(await encrypt(key,next) as any);return task;}
export async function setAssistantTaskStatus(key:CryptoKey,taskId:string,status:'open'|'done'):Promise<void>{const state=await loadAssistantTasks(key),timestamp=now(),tasks=state.tasks.map(row=>row.id===taskId?{...row,status,updatedAt:timestamp}:row);await putRecord(await encrypt(key,{version:1,tasks,updatedAt:timestamp}) as any);}
